/**********************************************/
/** READING ABILITY TASK (tag: 'ReadAbil')   **/
/**********************************************/

/***
This reading ability assessment is a lexical decision task based on
Yeatman et al. (2021; https://doi.org/10.1038/s41598-021-85907-x),
whose materials also supply the stimuli. The array `ReadAbil_stimuli` in
'reading_ability_stimuli.js', loaded before this script, is generated by
'stimuli/reading_ability_stimulus_preparation.R', which rebuilds it in a
separate output directory and checks it byte for byte against the
committed copy.

The trial components below are shared by the practice block and the
main block. Some appear in only one block: the instructions and the
feedback are shown during practice only. The blocks also differ in the
`timeline_variables` they use: practice uses `ReadAbil_practice_stimuli`,
while the main block uses `ReadAbil_stimuli`.
***/

// Session-wide welcome and consent are defined in study_welcome.js.
// This file intentionally contains only reading-ability task logic.

var ReadAbil_instructions = {
  type: jsPsychHtmlKeyboardResponse,
  prompt: "<p>Press the space bar to begin.</p>",
  choices: [" "],
  trial_duration: 40000,
  stimulus:
    "<div>Welcome to the first task. Each screen will show a string of letters." +
    "<br><br><button>J</button> = the letters form a <b>real word</b> " +
    "(e.g., <i>flask</i>)" +
    "<br><button>F</button> = the letters do <b>not</b> form a real word " +
    "(e.g., <i>wreet</i>)" +
    "<br><br>Please respond as accurately and fast as possible.</div>",
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(ReadAbil_instructions);

// Fixation cross
var ReadAbil_fixation = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: "+",
  // Choices set below to allow logging any premature response attempts
  choices: ["f", "j"],
  response_ends_trial: false,
  trial_duration: function () {
    // Set fixations with a varying duration to boost participants' attention
    return jsPsych.randomization.sampleWithoutReplacement(
      [400, 450, 500, 550, 600],
      1,
    )[0];
  },
  /* Following the semantic priming convention, only the response-bearing
  'stim' trial carries the task tag; the surrounding components inherit the
  session stage via the sticky `section` labelling in index.html. This keeps
  one identifiable row per trial (the 'stim' row) carrying task + accuracy. */
  css_classes: ["stimulus"],

  // Custom data to be included in output
  on_finish: function (data) {
    // Adjust trial number
    TrialNum += 1;

    // Save trial number
    data.trial = TrialNum;

    // Log premature response attempts by writing 1
    if (data.response != null) {
      data.premature_response_attempts = 1;
    } else {
      data.premature_response_attempts = 0;
    }
  },
};

/* Register any premature response attempts during the first 100 ms after
onset of the stimulus. These attempts are not considered as responses. */

var stim_100ms = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: jsPsych.timelineVariable("stim"),
  // Choices set below to allow logging any premature response attempts
  choices: ["f", "j"],
  response_ends_trial: false,
  trial_duration: 100,
  css_classes: ["stimulus"],

  // Custom data to be included in output
  on_finish: function (data) {
    // Save trial number
    data.trial = TrialNum;

    // Log premature response attempts by writing 1
    if (data.response != null) {
      data.premature_response_attempts = 1;
    } else {
      data.premature_response_attempts = 0;
    }
  },
};

/* In the stim section of trials, all the key data are gathered, 
including information from previous sections of the same trial. */

var stim = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: function () {
    // In practice section, present instructions above stimulus word
    var task = jsPsych.evaluateTimelineVariable("task");
    var stimulus_word = jsPsych.evaluateTimelineVariable("stim");
    if (task === "ReadAbil_practice") {
      return (
        "<div><b>Reminder:</b>" +
        "<br><button>J</button> = real word (e.g., <i>flask</i>)" +
        "<br><button>F</button> = not a real word (e.g., <i>wreet</i>)</div>" +
        '<div style="text-align:center; font-size: 105%;">' +
        stimulus_word +
        "</div>"
      );
    } else {
      return stimulus_word;
    }
  },
  choices: ["f", "j"],

  /* Set 3,000 ms as the maximum trial duration, the same as in the lexical decision
  task of Hutchison et al. (2013; https://doi.org/10.3758/s13428-012-0304-z) and in
  the semantic decision task of Pexman et al. (2017; https://doi.org/10.3758/s13428-016-0720-6).
  The duration is formed of 100 ms in the 'stim_100ms' item and 2,900 ms in the
  'stim' item.

  The practice trials have NO limit. They are the session's comprehension
  check, and Prolific's policy does not permit a time limit on one: a limit of
  40 s used to apply and a timed-out trial counted as a failure, so a slow
  participant could be sent out of the study for being slow. An abandoned
  session now stalls on the word instead, and Prolific returns it at the
  study's maximum time. */
  trial_duration: function () {
    if (jsPsych.evaluateTimelineVariable("task") === "ReadAbil_practice") {
      return null;
    } else {
      return 2900;
    }
  },
  css_classes: ["stimulus"],
  data: {
    // add info to output
    task: jsPsych.timelineVariable("task"),
    stim: jsPsych.timelineVariable("stim"),
    corr_rsp: jsPsych.timelineVariable("corr_rsp"),
  },

  // Custom data to be included in output
  on_finish: function (data) {
    // Save trial number
    data.trial = TrialNum;

    if (data.response != null) {
      // Label correct responses
      if (
        (data.corr_rsp == "no" && data.response == "f") ||
        (data.corr_rsp == "yes" && data.response == "j")
      ) {
        data.accuracy = "correct";
        // Label incorrect responses
      } else if (
        (data.corr_rsp == "no" && data.response == "j") ||
        (data.corr_rsp == "yes" && data.response == "f")
      ) {
        data.accuracy = "incorrect";
      }
      // Label unanswered trials
    } else {
      data.accuracy = "unanswered";
    }

    // Overall accuracy rate so far, ranging between 0 and 1

    var task = jsPsych.evaluateTimelineVariable("task");
    var ReadAbil_total_correct = jsPsych.data
      .get()
      .filter({
        task: task,
        accuracy: "correct",
      })
      .count();

    var ReadAbil_total_incorrect = jsPsych.data
      .get()
      .filter({
        task: task,
        accuracy: "incorrect",
      })
      .count();

    var ReadAbil_total_unanswered = jsPsych.data
      .get()
      .filter({
        task: task,
        accuracy: "unanswered",
      })
      .count();

    data.accuracy_rate =
      ReadAbil_total_correct /
      (ReadAbil_total_correct + ReadAbil_total_incorrect + ReadAbil_total_unanswered);

    /* Aggregate any premature response attempts on this trial. 
    If there were any, write 'yes'. */

    if (
      jsPsych.data.get().last(3).values()[0].premature_response_attempts != 0 ||
      jsPsych.data.get().last(2).values()[0].premature_response_attempts != 0
    ) {
      data.premature_response_attempts = "yes";
    } else {
      data.premature_response_attempts = "no";
    }
  },
};

// At trials 20, 40, 60 and 80, when running accuracy is below 80%
// (preregistration, Procedure). Unlike the priming and MCT triggers, the last
// response need not be incorrect.
var ReadAbil_conditional_instructional_manipulation_check = {
  timeline: [random_number, instructional_manipulation_check],
  conditional_function: function () {
    var last = jsPsych.data.getLastTrialData().values()[0];
    return (
      last != null && [20, 40, 60, 80].includes(last.trial) && last.accuracy_rate < 0.8
    );
  },
};

var ReadAbil_feedback = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: function () {
    if (jsPsych.data.getLastTrialData().values()[0].accuracy == "correct") {
      return "<p><green-button> &check; </green-button></p>";
    } else if (jsPsych.data.getLastTrialData().values()[0].accuracy == "incorrect") {
      return "<p><red-button> &#x2718; </red-button></p>";
    } else if (jsPsych.data.getLastTrialData().values()[0].accuracy == "unanswered") {
      return "<p><red-button> 0 </red-button></p>";
    } else {
      return "<p>&nbsp;</p>";
    }
  },
  choices: "NO_KEYS",
  trial_duration: 800,
  // Custom data to be included in output
  on_finish: function (data) {
    // Save trial number
    data.trial = TrialNum;
  },
};

// The intertrial interval is the last part of every trial
var ReadAbil_intertrial_interval = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: function () {
    // Show progress bar only in main trials
    if (jsPsych.evaluateTimelineVariable("task") === "ReadAbil_main") {
      var pct = Math.round((TrialNum / ReadAbil_stimuli.length) * 100);
      return (
        '<div class="trial-progress-container-centre">' +
        '<div class="trial-progress-bar" style="width:' +
        pct +
        '%"></div></div>'
      );
    }
    return " ";
  },
  trial_duration: function () {
    // Set interval with a varying duration to boost participants' attention
    return jsPsych.randomization.sampleWithoutReplacement(
      [1400, 1450, 1500, 1550, 1600],
      1,
    )[0];
  },
  response_ends_trial: false,
  css_classes: ["stimulus"],
  // Custom data to be included in output
  on_finish: function (data) {
    // trial number
    data.trial = TrialNum;
  },
};

// PRACTICE TRIALS with comprehension check

/* Neither of these practice trials are present in the main part of the
reading ability task or in the semantic priming task. They double as the
session's comprehension check, and the design follows Prolific's policy
(https://researcher-help.prolific.com/en/articles/445153-prolific-s-attention-and-comprehension-check-policy,
checked 2026-08-21), which sets four conditions on such a check. It must come
at the start of the study, which this does, being the first task. The key
information must be re-readable while the check is on screen, which is why the
F and J reminder sits above the word during practice and not in the main block.
The participant must be given at least two chances, which is why the practice
runs in two rounds and why only the second round can end the session. And a
failure may never be grounds for rejection: the exit message asks them to
return their submission instead, which is the outcome the policy names.

Scoring uses the second round only, and ends the session only when both of its
trials are incorrect or unanswered (preregistration, Procedure; ethics
application, section 4). Early key presses repeat the first round but do not
count against the second. Counting both rounds would carry the first round's
mistakes into the verdict, which is precisely what the two-attempt rule avoids. */

var ReadAbil_practice_stimuli = [
  {
    stim: "wreet",
    corr_rsp: "no",
    task: "ReadAbil_practice",
    trial: 1,
  },
  {
    stim: "flask",
    corr_rsp: "yes",
    task: "ReadAbil_practice",
    trial: 2,
  },
];

/* Assemble practice trials timeline using some of the components 
created at the top of this script. */

var ReadAbil_practice_timeline = {
  timeline: [
    ReadAbil_fixation,
    stim_100ms,
    stim,
    ReadAbil_feedback,
    ReadAbil_intertrial_interval,
  ],
  timeline_variables: ReadAbil_practice_stimuli,
  randomize_order: true,
  // restart trial count at the beginning of this timeline
  on_timeline_start: function () {
    TrialNum = 0;
  },
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(ReadAbil_practice_timeline);

// Overall feedback on all the initial practice trials
var ReadAbil_practice_debrief = {
  type: jsPsychHtmlKeyboardResponse,
  choices: [" "],
  trial_duration: 40000,

  stimulus: function () {
    if (window.AUTO_TEST) {
      return "<div>Autotest mode: practice completed. Press space to continue.</div>";
    }

    var round1_result = ReadAbil_practice_result(1);

    // Tailor message to the results.
    //
    // The first round never ends the session, however badly it goes. Prolific
    // requires that "participants must be given at least two chances to get a
    // correct answer", and this study's registered protocol says the practice
    // allows two attempts; ending here on two wrong trials granted only one.
    // A round-1 failure falls through to the results branch below, which sends
    // the participant into the repeat. Only the second round terminates.

    // If results good, keep message short
    if (round1_result.passed) {
      return (
        "<div>Practice completed. In the next part, neither the instructions " +
        "nor the feedback will be shown, and trials will be faster. Please press the " +
        "space bar to begin.</div>"
      );

      // If results valid but not so good, present them
    } else {
      var message =
        "<div><b>Results of the practice</b><br>" +
        "Your accuracy rate was " +
        Math.round(round1_result.accuracy_rate * 100) +
        "%.</div>";

      // Report any premature response attempts
      if (round1_result.premature_attempts === 1) {
        message =
          message +
          "<div>There was a response attempt before the word had been presented. " +
          "Please respond only when you have read the letters and decided whether " +
          "they form a real word.</div>";
      } else if (round1_result.premature_attempts > 1) {
        message =
          message +
          "<div>There were " +
          round1_result.premature_attempts +
          " response attempts before the word had been presented. Please " +
          "respond only when you have read the letters and decided whether " +
          "they form a real word.</div>";
      }

      // Display entire message
      return message + "<div>Please press the space bar to repeat the practice.</div>";
    }
  },

  on_finish: function (data) {
    if (window.AUTO_TEST) {
      // The smoke test answers everything; the marker is still written so
      // the export contract can see the column.
      data.comprehension_check = "autotest";
      return;
    }

    // Save trial number
    data.trial = TrialNum;

    // No termination here, deliberately. See the note in `stimulus` above: the
    // first round is the first of the two attempts the policy requires, so a
    // participant who fails it goes to the repeat rather than out of the study.
    // A session that passes at the first attempt never reaches the second
    // debrief, so the outcome is recorded here for that case.
    data.comprehension_check = ReadAbil_practice_result(1).passed
      ? "passed"
      : "repeated";
  },
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(ReadAbil_practice_debrief);

// Prepare repeated instructions
var repeat_ReadAbil_instructions = {
  type: jsPsychHtmlKeyboardResponse,
  prompt: "<p>Press the space bar to begin.</p>",
  choices: [" "],
  trial_duration: 40000,
  stimulus:
    "<div>Please consider the instructions again. Each screen will show a string of " +
    "letters." +
    "<br><br><button>J</button> = the letters form a <b>real word</b> " +
    "(e.g., <i>flask</i>)" +
    "<br><button>F</button> = the letters do <b>not</b> form a real word " +
    "(e.g., <i>wreet</i>)" +
    "<br><br>Please try to respond as accurately and fast as " +
    "possible.</div>",
};

/* Summarise one practice round: its accuracy, its early key presses, and
   whether it passed. The first-round feedback and the repeat decision share
   this verdict, so the practice repeats unless both trials are correct and no
   key was pressed early (preregistration, Procedure). The second round is not
   judged by `passed`. It ends the session only under the rule in
   ReadAbil_round2_ends_session below. */
function ReadAbil_practice_result(round) {
  var rows = jsPsych.data
    .get()
    .filter({ task: "ReadAbil_practice" })
    .values()
    .filter(function (d) {
      return (
        typeof d.accuracy === "string" &&
        (round === 1 ? d.practice_round == null : d.practice_round === round)
      );
    });
  var correct = rows.filter(function (d) {
    return d.accuracy === "correct";
  }).length;
  var premature_attempts = rows.filter(function (d) {
    return d.premature_response_attempts === "yes";
  }).length;
  var accuracy_rate = rows.length ? correct / rows.length : 0;

  return {
    accuracy_rate: accuracy_rate,
    premature_attempts: premature_attempts,
    passed:
      rows.length === ReadAbil_practice_stimuli.length &&
      premature_attempts === 0 &&
      accuracy_rate >= 0.8,
  };
}

function ReadAbil_should_repeat_practice() {
  return !window.AUTO_TEST && !ReadAbil_practice_result(1).passed;
}

/* The comprehension check ends the session only if both second-round trials
   are incorrect or unanswered, so one correct response of the two is enough
   to continue (preregistration, Procedure; ethics application, section 4).
   Early key presses in the second round are reported on screen but never
   count towards this rule. */
function ReadAbil_round2_ends_session() {
  var failures = jsPsych.data
    .get()
    .filter({ task: "ReadAbil_practice", practice_round: 2 })
    .values()
    .filter(function (d) {
      return d.accuracy === "incorrect" || d.accuracy === "unanswered";
    }).length;
  return failures >= 2;
}

/* Present repeated instructions if there were any premature
response attempts or if accuracy rate < 80%. */
var conditional_repeat_ReadAbil_instructions = {
  timeline: [repeat_ReadAbil_instructions],
  conditional_function: function () {
    return ReadAbil_should_repeat_practice();
  },
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(conditional_repeat_ReadAbil_instructions);

/* Repeat practice trials if there were any premature 
response attempts or if accuracy rate < 80%. */
var ReadAbil_repeated_practice_trials = {
  timeline: [ReadAbil_practice_timeline],
  data: {
    practice_round: 2,
  },
  conditional_function: function () {
    return ReadAbil_should_repeat_practice();
  },
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(ReadAbil_repeated_practice_trials);

// Overall feedback on all the repeated practice trials
var ReadAbil_repeated_practice_debrief = {
  type: jsPsychHtmlKeyboardResponse,
  choices: [" "],
  trial_duration: 20000,

  stimulus: function () {
    // Tailor message introduction to the results
    /* Scored on the second round alone. Counting both rounds would carry the
       first round's mistakes into the verdict, so a participant who failed the
       first attempt and then passed the second would still be sent out, which
       is the one thing the two-attempt rule exists to prevent. */
    if (!ReadAbil_round2_ends_session()) {
      var round2_result = ReadAbil_practice_result(2);

      // Begin message (div closed below)
      var message = "<div>Practice completed. ";

      // Report any premature response attempts of the second round
      if (round2_result.premature_attempts === 1) {
        message =
          message +
          "<br>There was a response attempt before the word had been presented. " +
          "Please respond only when you have read the letters and decided whether " +
          "they form a real word.<br>";
      } else if (round2_result.premature_attempts > 1) {
        message =
          message +
          "<br>There were " +
          round2_result.premature_attempts +
          " response attempts before the word had been presented. " +
          "Please respond only when you have read the letters and " +
          "decided whether they form a real word.<br>";
      }

      // Finish message and display it
      return (
        message +
        "In the next part, neither the instructions nor the " +
        "feedback will be shown, and trials will be faster. Please press " +
        "the space bar to begin.</div><br>"
      );

      /* Both second-round trials were incorrect or unanswered, so the session
      ends with the shared exit message. */
    } else {
      return window.prolificExitMessage("comprehension") + "<br>";
    }
  },

  on_finish: function (data) {
    if (window.AUTO_TEST) {
      return;
    }

    // Apply the rule the screen above applied, or a participant could be shown
    // the exit message while the session quietly continues, or be sent out on
    // a verdict the screen never gave. Unanswered trials can no longer occur,
    // because the practice has no time limit, but they still count so the rule
    // reads as registered. The outcome is written to this row so the data say
    // how the comprehension check ended without reconstructing it from trials.
    var ends_session = ReadAbil_round2_ends_session();
    data.comprehension_check = ends_session ? "failed" : "passed";
    if (ends_session) {
      jsPsych.abortExperiment(window.prolificExitMessage("comprehension"), data);
    }
  },
};

// Show second-round feedback if practice trials were repeated
var conditional_ReadAbil_repeated_practice_debrief = {
  timeline: [ReadAbil_repeated_practice_debrief],
  conditional_function: function () {
    if (window.AUTO_TEST) {
      return false;
    }

    if (
      jsPsych.data
        .get()
        .filter({
          task: "ReadAbil_practice",
          practice_round: 2,
        })
        .count() >= 1
    ) {
      return true;
    } else {
      return false;
    }
  },
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(conditional_ReadAbil_repeated_practice_debrief);

/* Assemble main trials timeline using some of the 
components created near the top of this script. */

var ReadAbil_timeline = {
  timeline: [
    ReadAbil_fixation,
    stim_100ms,
    stim,
    ReadAbil_conditional_instructional_manipulation_check,
    ReadAbil_intertrial_interval,
  ],
  timeline_variables: ReadAbil_stimuli,
  randomize_order: true,
  // restart trial count at the beginning of this timeline
  on_timeline_start: function () {
    TrialNum = 0;
  },
};
// Push to general timeline
language_vision_SemPri_TIMELINE.push(ReadAbil_timeline);

// Transition to next task
language_vision_SemPri_TIMELINE.push(break_between_tasks);
