---
title: Investigating language learning and morphosyntactic transfer longitudinally using artificial languages
authors: ['<span style="font-size:140%;">Pablo Bernabeu, Gabriella Silva, My Ngoc Giang Hoang, Vincent DeLuca, Claudia Poch, Iva Ivanova, Jason Rothman, Jorge González Alonso</span>']
author: ~
date: '2024-09-05'
slug: investigating-language-learning-and-morphosyntactic-transfer-longitudinally-using-artificial-languages
categories:
  - psycholinguistics
tags:
  - multilingualism
  - psycholinguistics
  - crosslinguistic transfer
  - language learning
  - executive functions
  - individual differences
  - artificial languages
  - Norwegian
  - English
  - Spanish
  - event-related potentials
  - electroencephalography
presentation_format: Poster
event: 30th Conference on Architectures and Mechanisms for Language Processing (AMLaP)
event_url: 'https://amlap2024.ed.ac.uk/'
location: ~
address:
  street: ~
  city: ~
  region: ~
  postcode: ~
  country: ~
summary: ~
abstract: "The acquisition of a third language (L3) often involves the transfer of morphosyntactic structures from the first language and/or the second language to the developing L3 grammar, allowing the recycling of previously acquired knowledge (Rothman et al., 2015). Under the assumption that this crosslinguistic influence is somewhat systematic, much research has investigated the mechanisms involved in selecting a source of transfer given various (competing) options. The use of artificial languages (AL) has allowed researchers to investigate this process from the very onset of L3 acquisition, with some initial findings suggesting a facilitative role of attention prior to the selection of a source of transfer (González Alonso et al., 2020; Pereira Soares et al., 2022). The current study examines morphosyntactic transfer longitudinally in two sites. In Norway, participants were randomly assigned to training and testing in Mini-Norwegian or Mini-English, the former AL being typologically closer to Norwegian. In Spain, Mini-Spanish and Mini-English were used. The study comprises six sessions. Session 1 consists of an assessment of attention-related executive functions and a language history questionnaire. A week later, Session 2 begins with a resting-state electroencephalographic measurement, which captures attention skills (Rogala et al., 2020). We hypothesise that attention facilitates learning and transfers. The rest of the session is devoted to the grammatical property of gender agreement (part of Norwegian and Spanish grammars). A week later, Session 3 adds the property of differential object marking (part of Spanish grammar, absent in the other two languages). A week later, Session 4 adds the property of verb-object agreement (absent from the English, Norwegian and Spanish grammars). The grammar part of Sessions 2, 3 and 4 consists of a vocabulary pre-training, a training in the new grammatical property, a behavioural test and an electroencephalography experiment measuring event-related potentials (ERPs) in response to grammatical and ungrammatical instances of each property. A week after Session 4, Session 5 provides a retest of the cognitive battery from Session 1. Last, after a consolidation period of four months, all grammatical properties are retested in Session 6 (see Morgan-Short et al., 2012). Our analyses delve into language learning, morphosyntactic transfer, and their associations with executive functions longitudinally."
date_end: ~
all_day: no
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
url_slides: ~
url_data: https://osf.io/974k8
url_code: https://osf.io/974k8
url_poster: https://osf.io/3ba9y
url_video: ~
projects: []
---


### References

González Alonso, J., Alemán Bañón, J., DeLuca, V., Miller, D., Pereira Soares, S. M., Puig-Mayenco, E., Slaats, S., & Rothman, J. (2020). Event related potentials at initial exposure in third language acquisition: Implications from an artificial mini-grammar study. *Journal of Neurolinguistics, 56*, 100939. https://doi.org/10.1016/j.jneuroling.2020.100939

Morgan-Short, K., Finger, I., Grey, S., & Ullman, M. T. (2012). Second language processing shows increased native-like neural responses after months of no exposure. *PLOS ONE, 7*(3), e32974. https://doi.org/10.1371/journal.pone.0032974

Pereira Soares, S. M., Kupisch, T., & Rothman, J. (2022). Testing potential transfer effects in heritage and adult L2 bilinguals acquiring a mini grammar as an additional language: An ERP approach. *Brain Sciences, 12*(5), Article 5. https://doi.org/10.3390/brainsci12050669

Rogala, J., Kublik, E., Krauz, R., & Wróbel, A. (2020). Resting-state EEG activity predicts frontoparietal network reconfiguration and improved attentional performance. *Scientific Reports, 10*(1), 5064. https://doi.org/10.1038/s41598-020-61866-7

Rothman, J., Alemán Bañón, J., & González Alonso, J. (2015). Neurolinguistic measures of typological effects in multilingual transfer: Introducing an ERP methodology. *Frontiers in Psychology, 6*. https://www.frontiersin.org/articles/10.3389/fpsyg.2015.01087


<div style = 'margin-left: -2em; text-indent: 0em; margin-top: 45px;'>

<a href='https://osf.io/3ba9y'>
      <button style = "background-color: white; color: black; border: 2px solid #196F27; border-radius: 12px;">
      <h3 style = "margin-top: 7px !important; margin-left: 9px !important; margin-right: 9px !important;"> 
      <span style="color:#DBE6DA;"></span> Poster </h3></button></a> &nbsp; 

<div class="document-viewer-container" style="height: 80vh; min-height: 400px;">
<iframe src="https://cdn.jsdelivr.net/gh/pablobernabeu/LESS-Project@main/presentations/Bernabeu%20et%20al%20FAIR%20at%20HILS%202024.pdf" width="100%" height="100%" style="border: none" title="Document Viewer" loading="lazy">
<p>Your browser does not support embedded PDFs. <a href="https://cdn.jsdelivr.net/gh/pablobernabeu/LESS-Project@main/presentations/Bernabeu%20et%20al%20at%20HILS%202024.pdf" target="_blank">Download the PDF</a> instead.</p>
</iframe>
</div>

</div>

