---
title: Do you speak a Scandinavian language(s) and English, but no other languages? Delta i et EEG-eksperiment
author: ''
date: '2023-11-14'
slug: do-you-speak-a-scandinavian-language-s-and-english-but-no-other-languages-delta-i-et-eeg-eksperiment
categories:
  - science
tags:
  - vitenskap
  - electroencephalography
  - eksperiment
  - tromsø
  - tromso
  - uit
  - norges arktiske universitet
  - arctic university of norway
  - universitetet i tromsø
  - s
subtitle: ''
summary: 'Recruitment announcement in Norwegian for participants who speak a Scandinavian language and English (but no other languages) to participate in a paid EEG experiment at UiT The Arctic University of Norway in Tromsø.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


#### Ved å delta i vårt eksperiment og gjøre noen enkle oppgaver på en datamaskin, kan du bidra til forskning og tjene 250 kr i timen (gavekort). EEG er helt smertefritt.

<div>

##### Eksperimentet foregår i Tromsø, ved UiT Norges Arktiske Universitet.

Vi ser etter deltakere med følgende egenskaper:

<div style = 'text-indent:-1.2em; margin-left:2em;'>

   ☑ Alder 18–45 år;

   ☑ Snakker norsk som førstespråk og engelsk flytende. Utenom disse språkene, kan deltakerne også snakke svensk og dansk, men ikke andre språk (utover noen få ord);

   ☑ Ingen språkrelaterte lidelser eller vansker, som f.eks. dysleksi;

   ☑ Ingen oppmerksomhetssvikt
   
</div>


I de fleste tilfeller vil deltakelse innebære å gjennomføre fem økter over en måned, med bonusutbetaling på slutten.

Dersom du oppfyller disse kriteriene og ønsker å delta, vennligst registrer deg nedenfor for å motta mer informasjon, eller kontakt Pablo på epost-adressen p.bernabeu@uit.no.


<div style = 'margin-top: 4%;'></div>

<a href='https://rb.gy/9zbhfv'> 
  <button style = "background-color: white; color: black; border: 2px solid #4CAF50; border-radius: 12px;">
  <h3 style = "margin-top: 7px !important; margin-left: 9px !important; margin-right: 9px !important;"> 
  <span style="color:#86ea8d;"><i class="fa fa-envelope" aria-hidden="true"></i></span>
  Meld deg på
  </h3></button>
</a>

<div style = 'margin-top: 5%;'></div>

Tusen takk for din interesse i denne studien.

<div style = 'margin-top: 5%;'></div>

</div>

---

<span style='color:darkgrey;'>Takk til Mona Kirknes Fossum og Marit Westergaard for hjelpen med oversettelsen av denne annonsen.</span>

