---
title: Reproducibilidad en torno a una aplicación web
author: Pablo
date: 2020-10-08
event: Reprohack en español, LatinR Conference 2020
slug: 2020-10-08-reproducibilidad-en-torno-a-una-aplicacion-web
categories: 
  - research and teaching applications
tags:
  - programming
  - programación
  - web application
  - aplicación web
  - data simulation
  - simulación de datos
  - statistics
  - estadística
  - R
  - Software Sustainability Institute Fellowship
presentation_format: Talk
event_url: ~
location: ~
address:
  street: ~
  city: ~
  region: ~
  postcode: ~
  country: ~
summary: 'Las aplicaciones web nos ayudan a facilitar el uso de nuestro trabajo, ya que no requieren programación para utilizarlas. Crear estas aplicaciones en R, mediante paquetes como "shiny" o "flexdashboard", ofrece múltiples ventajas. Entre ellas destaca la reproducibilidad, tal como veremos en torno a una aplicación para la simulación de datos (https://github.com/pablobernabeu/Experimental-data-simulation).'
abstract: ~
date_end: ~
all_day: no
publishDate: ~
authors: []
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
url_slides: ~
url_code: ~
url_fulltext: ~
url_video: ~
slides: ''
projects: []
---


### Resumen

Las aplicaciones web nos ayudan a facilitar el uso de nuestro trabajo, ya que no requieren programación para utilizarlas ([ver ejemplos](https://shiny.rstudio.com/gallery/)). Crear estas aplicaciones en R, mediante paquetes como "shiny" o "flexdashboard", ofrece múltiples ventajas. Entre ellas destaca la reproducibilidad, tal como veremos en torno a una [aplicación para la simulación de datos](https://github.com/pablobernabeu/Experimental-data-simulation). Por un lado, los usuarios pueden exportar un registro de su actividad. Por otro lado, el código utilizado para crear estas aplicaciones se puede compartir, investigar y editar con la facilidad que ofrece un lenguaje de código abierto como R. Esto facilita el uso gratuito, el desarrollo colaborativo y una documentación accesible sobre cualquiera de los paquetes utilizados. Por último, la reproducibilidad se puede maximizar si se facilita a los usuarios que lo deseen la exportación de un código de R ajustado a sus requerimientos (más allá del código de la aplicación en general), lo cual añadiría a la aplicación las ventajas de un paquete de R. Esta última opción (no disponible actualmente en la aplicación de simulación, ni en la mayoría de las aplicaciones) se puede habilitar adaptando el código de la aplicación a funciones básicas de R.

### Vídeo y filminas

<center>

<iframe width="700" height="394" style="margin-top:20px; margin-bottom:5px;" src="https://www.youtube-nocookie.com/embed/1njLOAWqLPM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe src="https://www.slideshare.net/slideshow/embed_code/key/AlE6wv2USddNP6" width="700" height="394" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="margin-top:20px; border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>

</center>

