---
title: 'Job: Part-time research assistant in experimental research'
author: ''
date: '2024-03-27'
slug: job-part-time-research-assistant-in-experimental-research
categories:
  - job
tags:
  - job
  - research assistant
  - UIT The Arctic University of Norway
  - Tromsø
  - electroencephalography
  - s
subtitle: ''
summary: 'Part-time research assistant position to help recruit participants and conduct an EEG experiment on language learning and multilingualism at UiT The Arctic University of Norway.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


We are seeking to appoint a part-time research assistant to help us recruit participants and conduct an experiment. In the current project, led by Jorge González Alonso and funded by the Research Council of Norway, we investigate language learning and the neurophysiological basis of multilingualism. To this end, we are conducting an **electroencephalography (EEG) experiment**.

Your work as a research assistant will be mentored and supervised primarily by Pablo Bernabeu, and secondarily by the head of our project and the directors of our lab. The role involves **20 hours a week** of on-site work in the Department of Language and Culture at UiT The Arctic University of Norway. The appointment should begin in early April 2024, or soon thereafter, and will span until mid-August (an extension thereafter might be possible).

By the end of your appointment, you will be able to conduct EEG sessions on your own, and will have a better understanding of EEG, experimental research and the psychology of language. This experience will be most useful for subsequent work in academic research; for instance, in a PhD. Yet, the post also involves more general skills, such as planning, documentation and data management.

## Person specification

Please consider the essential (required) criteria and the desirable criteria listed below.

### Essential criteria

-	not being currently enrolled in an on-site degree programme at UiT or any other university;

-	availability for the on-site work at UiT throughout the appointment;

-	attention to detail;

-	computer literacy;

-	written and spoken fluency in English

### Desirable criteria

-	previous experience in running EEG sessions, or related qualifications;

-	previous experience in any experimental research, or related qualifications;

-	schedule flexibility to accommodate the lab sessions;

-	interest in experimental linguistics, psychology or neuroscience

## How to apply 

Please submit your CV and a personal statement of up to 400 words to Pablo Bernabeu (p.bernabeu@uit.no) and Jorge González Alonso (jorge.gonzalez.alonso@uit.no), with the subject  ‘RA post’. Any questions are also welcome. In the personal statement, please describe how your background fits with the above criteria. We will review applications on a rolling basis. 


