---
title: Reducing the impedance in electroencephalography using a blunt needle, electrolyte gel and wiggling
authors: 
date: '2024-10-17'
slug: lowering-impedance-in-electroencephalography-using-a-blunt-needle-electrolyte-gel-and-wiggling
categories:
  - research methods
tags: 
  - electroencephalography
  - impedance
  - s
subtitle: ~
summary: Reducing the impedance in electroencephalography (EEG) is crucial for capturing high-quality brain activity signals. This process involves ensuring that electrodes make optimal contact with the skin without harming the participant. Below are a few tips to achieve this using a blunt needle, electrolyte gel and gentle wiggling.
external_link: ~
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


Reducing the impedance in electroencephalography (EEG) is crucial for capturing high-quality brain activity signals. This process involves ensuring that electrodes make optimal contact with the skin without harming the participant. Below are a few tips to achieve this using a blunt needle, electrolyte gel and gentle wiggling.


## First, Do No Harm

The primary goal is to reduce the impedance without damaging the skin or causing discomfort. Only use disposable, blunt needles, and never let the needle pierce the skin. While wiggling the needle under each electrode, do not any apply any force down on the skin. To achieve this, hold the syringe with the minimum grip force needed to control it. 

## Manage the Angle and Depth of the Needle

The needle should be positioned at an angle of around 20--50 degrees relative to the participant's skin. To attain such an angle, you may rotate the electrodes, move yourself or move the participant.

Control the depth of the needle to prevent scratching the skin. Usually, only half of the needle has to be inside, as the key work area is right under the electrode. 


<div>
  <div style="position: relative; padding-top: 56.25%; margin-top: 7%;">
  <iframe src="https://www.youtube.com/embed/4KLtp-WnOOo" frameborder="0" allowfullscreen
      style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>
  </div>
</div>

<br>


## Apply Gel Strategically

Use just enough electrolyte gel to reduce the impedance, but avoid creating bridges between adjacent electrodes. A small amount of gel should be visible on the opening of each electrode, and any large lumps should be carefully removed. This ensures that each electrode maintains a distinct connection with the skin.

## Control the Swing of the Electrode

Place your finger on the electrode throughout the wiggling to feel and control its movement. This helps prevent excess gel from forming a bump under the electrode, which could lead to inaccurate readings. 

## Wiggle with Precision

Position yourself comfortably to work on each electrode, allowing for precise movements and minimising participant discomfort. Wiggle the needle in small circular motions to move hair aside and ensure good skin contact. Be careful not to scratch the skin in the process. 

By following these tips, you’ll achieve lower impedance without causing harm, ensuring high-quality EEG data and a better experience for the participant. In short, you'll have moved the needle. 

