---
title: 'Linguistic and embodied systems in conceptual processing: Variation across individuals and items'
authors: ['<span style="font-size:140%;">Pablo Bernabeu, Dermot Lynott and Louise Connell</span>']
date: '2021-05-24'
slug: linguistic-and-embodied-systems-in-conceptual-processing-variation-across-individuals-and-items
categories:
  - conceptual processing
tags:
  - cognition
  - conceptual processing
  - language comprehension
  - statistics
  - power analysis
presentation_format: Talk
event: 'Lancaster University Postgraduate Psychology Conference 2021 ([see YouTube playlist](https://www.youtube.com/watch?v=qr9w9xvVeOs&list=PLT4E8k3PmUSYYyvcgeIpX4nP-26nEiu_j&ab_channel=LancasterPsychologyLancasterPsychology))'
event_url: ~
location: ~
address:
  street: ~
  city: ~
  region: ~
  postcode: ~
  country: ~
summary: 'The first study (Bernabeu et al., 2021) will merge existing datasets (Lynott et al., 2020; Pexman et al., 2017; Pexman & Yap, 2018; Wingfield & Connell, 2019). The second study will collect novel data to investigate questions such as the unique roles of vocabulary size, sensorimotor experience and attentional control.'
abstract: ~
date_end: ~
all_day: no
publishDate: '2021-05-07T23:01:48+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
url_slides: ~
url_code: ~
url_fulltext: ~
url_video: ~
projects: []
---


&nbsp; &nbsp; &nbsp;&nbsp; [**Video**](https://www.youtube.com/watch?v=y2bopgYWYvE&ab_channel=LancasterPsychology) 

&nbsp; &nbsp; &nbsp;&nbsp; [**Slides**](/presentation/linguistic-and-embodied-systems-in-conceptual-processing-variation-across-individuals-and-items/slides)


```{r embed-xaringan, echo = FALSE}

library(xaringanExtra)

xaringanExtra::embed_xaringan(url = "/presentation/linguistic-and-embodied-systems-in-conceptual-processing-variation-across-individuals-and-items/slides", ratio = "4:3")

```


### Abstract

Research in conceptual processing has suggested that the comprehension of words draws on complementary cognitive systems. In the milliseconds during which a word is processed, the linguistic system is activated first. Reading the word *entity*, for instance, may activate words such as *being*, *thing* and *object* (https://smallworldofwords.org/en/project/explore; De Deyne et al., 2019). Thereupon, the embodied system is activated, incorporating sensorimotor, emotional and social dimensions (Borghi et al., 2019). For instance, *entity* activates visual, auditory and head-specific meanings (https://embodiedcognitionlab.shinyapps.io/sensorimotor_norms; Lynott et al., 2020). Research has also suggested that the linguistic system is more important for relatively abstract words—e.g., *attempt*—, whereas the embodied system is more important for more concrete words—e.g., *building* (Bolognesi & Steen, 2018). The role of individual differences has also been investigated (Dils & Boroditsky, 2010), although to a lesser extent. An individual’s linguistic experience (e.g., larger vocabulary) facilitates word processing and task-relevant attention (Pexman & Yap, 2018; Yap et al., 2017), while greater sensorimotor experience enables more detailed meaning activation within specific conceptual areas (e.g., space: Vukovic & Williams, 2015). The variation across individuals and items, within both the linguistic and embodied systems, is seldom considered simultaneously. We are undertaking this in two studies. The first study (Bernabeu et al., 2021) will merge existing datasets (Lynott et al., 2020; Pexman et al., 2017; Pexman & Yap, 2018; Wingfield & Connell, 2019). The second study will collect novel data to investigate questions such as the unique roles of vocabulary size, sensorimotor experience and attentional control. To determine the sample size for the latter study, two pilot studies with larger-than-average samples were conducted, using the aforementioned datasets and that of Hutchison et al. (2013). Simulation-based, prospective power curves were performed. These pilots revealed important roles for linguistic and embodied information, vocabulary size, and attentional control, as well as statistical power considerations.

### References

Bernabeu, P., Lynott, D., & Connell, L. (2021). *Preregistration: The interplay between linguistic and embodied systems in conceptual processing*. OSF. https://osf.io/ftydw/

Bolognesi, M., & Steen, G. (2018). Abstract concepts: Structure, processing, and modeling. *Topics in Cognitive Science, 10*(3), 490–500. https://doi.org/10.1111/tops.12354

Borghi, A., M., Barca, L., Binkofski, F., Castelfranchi, C., Pezzulo, G., & Tummolini, L. (2019). Words as social tools: Language, sociality and inner grounding in abstract concepts. *Physics of Life Reviews, 29*, 120–53. https://doi.org/10.1016/j.plrev.2018.12.001

De Deyne, S., Navarro, D. J., Perfors, A., Brysbaert, M., & Storms, G. (2019). The “Small World of Words” English word association norms for over 12,000 cue words. *Behavior Research Methods, 51*, 987–1006. http://dx.doi.org/10.3758/s13428-018-1115-7

Dils, A. T., & Boroditsky, L. (2010). Visual motion aftereffect from understanding motion language. *Proceedings of the National Academy of Sciences, 107*(37), 16396-16400. https://doi.org/10.1073/pnas.1009438107

Hutchison, K. A., Balota, D. A., Neely, J. H., Cortese, M. J., Cohen-Shikora, E. R., Tse, C.-S., Yap, M. J., Bengson, J. J., Niemeyer, D., & Buchanan, E. (2013). The semantic priming project. *Behavior Research Methods, 45*, 1099–1114. https://doi.org/10.3758/s13428-012-0304-z

Lynott, D., Connell, L., Brysbaert, M., Brand, J., & Carney, J. (2020). The Lancaster Sensorimotor Norms: Multidimensional measures of perceptual and action strength for 40,000 English words. *Behavior Research Methods, 52*, 1-21. https://doi.org/10.3758/s13428-019-01316-z

Pexman, P. M., Heard, A., Lloyd, E., & Yap, M. J. (2017). The Calgary semantic decision project: Concrete/abstract decision data for 10,000 English words. *Behavior Research Methods, 49*(2), 407–417. https://doi.org/10.3758/s13428-016-0720-6

Pexman, P. M., & Yap, M. J. (2018). Individual differences in semantic processing: Insights from the Calgary semantic decision project. *Journal of Experimental Psychology: Learning, Memory, and Cognition, 44*(7), 1091–1112. 
https://doi.org/10.1037/xlm0000499

Vukovic, N., & Williams, J. N. (2015). Individual differences in spatial cognition influence mental simulation of language. *Cognition, 142*, 110–122. 
https://doi.org/10.1016/j.cognition.2015.05.017

Wingfield, C., & Connell, L. (2019). *Understanding the role of linguistic distributional knowledge in cognition*. PsyArXiv. https://doi.org/10.31234/osf.io/hpm4z

Yap, M. J., Hutchison, K. A., & Tan, L. C. (2017). Individual differences in semantic priming performance: Insights from the semantic priming project. In M. N. Jones (Ed.), *Frontiers of cognitive psychology. Big data in cognitive science* (p. 203–226). Routledge/Taylor & Francis Group.

