---
title: A session logbook for a longitudinal study using conditional formatting in
  Excel
author: ''
date: '2023-12-02'
slug: a-session-logbook-for-a-longitudinal-study-using-conditional-formatting-in-excel
categories:
  - research methods
tags:
  - research methods
  - session logbook
  - longitudinal study
  - Excel formulas
  - conditional formatting
  - s
subtitle: ''
summary: 'An Excel workbook template with conditional formatting to facilitate planning, registration, and tracking of sessions in longitudinal studies involving multiple session conductors.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


Longitudinal studies consist of several sessions, and often involve session session conductors. To facilitate the planning, registration and tracking of sessions, a session logbook becomes even more necessary than usual. To this end, an Excel workbook with conditional formatting can help automatise some formats and visualise the progress. 

Below is an example that is [available on OneDrive](https://1drv.ms/x/s!AouK9kQQrXKooGKVLbdBzz-DStmj?e=mbNZE4). To fully access this workbook, it may be downloaded via <kbd>File</kbd> > <kbd>Save as</kbd> > <kbd>Download a copy</kbd>. Alternatively, the workbook can be exported to one's own account on OneDrive.

The conditional formats include:

- fill in blanks in columns A, C or D to remove the background

- fill in blanks in F and G, or I and J, or L and M, etc, to highlight the entire session in green

- fill in any notes columns to highlight them in red

<iframe style='margin-top: 1%; margin-bottom: 3%;' width="700" height="365" frameborder="0" scrolling="no" src="https://1drv.ms/x/c/a872ad1044f68a8b/UQSLivZEEK1yIICoYhAAAAAAABsHnSAl4C4iZLc?em=2&AllowTyping=True&ActiveCell='in'!A1&Item='in'!A1%3AW7&wdHideGridlines=True&wdDownloadButton=True&wdInConfigurator=True&wdInConfigurator=True"></iframe>

These conditional formats can be consulted (and edited) from the <kbd>Home</kbd> tab by opening <kbd>Conditional Formatting</kbd> > <kbd>Manage Rules</kbd>. At the top, the option <kbd>This Worksheet</kbd> should be selected to view all formulas.


