---
title: Preprocessing the Norwegian Web as Corpus (NoWaC) in R
author: ''
date: '2023-09-28'
slug: preprocessing-the-norwegian-web-as-corpus-nowac-in-r
categories:
  - R
tags:
  - R
  - corpora
  - corpus
  - Norwegian
  - NoWaC
  - linguistics
  - language
  - research methods
  - s
subtitle: ''
summary: 'An R script for preprocessing frequency list data from the Norwegian Web as Corpus (NoWaC), including instructions for downloading and preparing the corpus data.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


### The present script can be used to preprocess data from a frequency list of the Norwegian as Web Corpus (NoWaC; Guevara, 2010).

Before using the script, the frequency list should be downloaded from [this URL](https://www.hf.uio.no/iln/english/about/organization/text-laboratory/projects/nowac/nowac-frequency.html). The list is described as 'frequency list sorted primary alphabetic and secondary by frequency within each character', and [this is the direct URL](https://www.tekstlab.uio.no/nowac/download/nowac-1.1.lemma.frek.sort_alf_frek.txt.gz). The download requires signing in to an institutional network. Last, the downloaded file should be unzipped.

The script is shown below.

<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fpablobernabeu%2Fpreprocessing-NoWaC-Corpus-in-R%2Fblob%2Fmain%2Fpreprocessing_NoWaC_Corpus.R%23L19-L102&style=a11y-dark&type=code&showLineNumbers=on&showFileMeta=on&showCopy=on"></script>


## References

Guevara, E. R. (2010). NoWaC: A large web-based corpus for Norwegian. In *Proceedings of the NAACL HLT 2010 Sixth Web as Corpus Workshop* (pp. 1-7). https://aclanthology.org/W10-1501

Rodina, Y., & Westergaard, M. (2015). Grammatical gender in Norwegian: Language acquisition and language change. *Journal of Germanic Linguistics, 27*(2), 145–187. https://doi.org/10.1017/S1470542714000245

Rodina, Y., & Westergaard, M. (2021). Grammatical gender and declension class in language change: A study of the loss of feminine gender in Norwegian. *Journal of Germanic Linguistics, 33*(3), 235–263. https://doi.org/10.1017/S1470542719000217

