<!doctype html><html lang=en-gb><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=generator content="Source Themes Academic 4.7.0"><meta name=author content="Pablo Bernabeu"><meta name=description content="This reproducible descriptive analysis uses annual Scopus counts to compare how often records in nine query-defined literatures use a form of “speculate” in their titles, abstracts or keywords. The count is a proxy for explicit wording in indexed records, not a measure of evidential quality."><meta name=indexnow-key content="ba7d2697a8f44966bd90543d188a8aac"><meta name=indexnow-host content="pablobernabeu.github.io"><meta name=indexnow-key-location content="https://pablobernabeu.github.io/ba7d2697a8f44966bd90543d188a8aac.txt"><link rel=alternate hreflang=en-gb href=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/><meta name=theme-color content="#2962ff"><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin=anonymous><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin=anonymous><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin=anonymous><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css crossorigin=anonymous title=hl-light><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css crossorigin=anonymous title=hl-dark disabled><script src=https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin=anonymous async></script><link rel=stylesheet href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap"><style>/*!* Source Themes Academic v4.7.0 (https://sourcethemes.com/academic/)*/</style><link rel=stylesheet href=/css/academic.css><link rel=manifest href=/index.webmanifest><link rel=icon type=image/png href=/images/icon_hu125e1cde4fb125eb9c515e372e2310e0_537990_32x32_fill_lanczos_center_2.png><link rel=apple-touch-icon type=image/png href=/images/icon_hu125e1cde4fb125eb9c515e372e2310e0_537990_192x192_fill_lanczos_center_2.png><link rel=canonical href=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/><meta property="twitter:card" content="summary_large_image"><meta property="og:site_name" content="Pablo Bernabeu"><meta property="og:url" content="https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/"><meta property="og:title" content="Speculation across various scientific topics | Pablo Bernabeu"><meta property="og:description" content="This reproducible descriptive analysis uses annual Scopus counts to compare how often records in nine query-defined literatures use a form of “speculate” in their titles, abstracts or keywords. The count is a proxy for explicit wording in indexed records, not a measure of evidential quality."><meta property="og:image" content="https://pablobernabeu.github.io/img/default_preview_image.jpg"><meta property="twitter:image" content="https://pablobernabeu.github.io/img/default_preview_image.jpg"><meta property="og:locale" content="en-GB"><meta property="article:published_time" content="2026-09-02T00:00:00+00:00"><meta property="article:modified_time" content="2026-09-02T00:00:00+00:00"><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/"},"headline":"Speculation across various scientific topics","datePublished":"2026-09-02T00:00:00Z","dateModified":"2026-09-02T00:00:00Z","author":{"@type":"Person","name":"Pablo Bernabeu"},"publisher":{"@type":"Organization","name":"Pablo Bernabeu","logo":{"@type":"ImageObject","url":"https://pablobernabeu.github.io/images/icon_hu125e1cde4fb125eb9c515e372e2310e0_537990_192x192_fill_lanczos_center_2.png"}},"description":"This reproducible descriptive analysis uses annual Scopus counts to compare how often records in nine query-defined literatures use a form of “speculate” in their titles, abstracts or keywords. The count is a proxy for explicit wording in indexed records, not a measure of evidential quality."}</script><link rel=preconnect href=https://fonts.gstatic.com crossorigin><script>(function(){"use strict";function getThemeMode(){try{const storedMode=localStorage.getItem("dark_mode");return parseInt(storedMode||2);}catch(e){return 2;}}
function shouldUseDarkTheme(){let currentThemeMode=getThemeMode();switch(currentThemeMode){case 0:return false;case 1:return true;default:try{if(localStorage.getItem("dark_mode")===null){return false;}}catch(e){}
return(window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches);}}
function selectHighlightTheme(isDark){var light=document.querySelector('link[title="hl-light"]');var dark=document.querySelector('link[title="hl-dark"]');if(!light||!dark)return;light.disabled=isDark;dark.disabled=!isDark;}
var useDarkTheme=shouldUseDarkTheme();selectHighlightTheme(useDarkTheme);if(useDarkTheme){document.documentElement.setAttribute("data-theme","dark");document.documentElement.style.backgroundColor="#0f172a";document.documentElement.style.color="#e2e8f0";document.addEventListener("DOMContentLoaded",function(){document.body.classList.add("dark");});}})();</script><link rel=stylesheet href=/css/publication-type-badges.css><link rel=stylesheet href=/css/custom-nav.css><script src=/js/open-science-badges.js defer></script><script src=/js/publication-type-badge-colors.js defer></script><script src=/js/publication-type-badge-popup.js defer></script><script src=/js/github-button-fix.js defer></script><script src=/js/abstract-heading-style.js defer></script><link rel=stylesheet href=/css/search-modal.css><meta name=format-detection content="telephone=no"><script>(function fixSearchLink(){function neutralize(){var triggers=document.querySelectorAll('.js-search-trigger');for(var i=0;i<triggers.length;i++){var a=triggers[i].closest('a');if(a){a.classList.add('js-search-trigger');a.setAttribute('href','#search');a.setAttribute('role','button');a.setAttribute('aria-label','Search');}}}
if(document.body){neutralize();}
var observer=new MutationObserver(function(){neutralize();if(document.querySelector('.js-search-trigger')){observer.disconnect();}});observer.observe(document.documentElement,{childList:true,subtree:true});})();</script><script>document.addEventListener("DOMContentLoaded",function(){setTimeout(function(){const searchModal=document.getElementById("search");if(!searchModal)return;let savedQuery=localStorage.getItem("searchQuery")||"";let savedResults=localStorage.getItem("searchResults")||"";window.searchModalPreventClose=false;function hasSearchResults(){const searchHits=document.getElementById("search-hits");return(searchHits&&searchHits.querySelectorAll(".search-hit").length>0);}
function saveSearchResults(){const searchHits=document.getElementById("search-hits");if(searchHits&&hasSearchResults()){savedResults=searchHits.innerHTML;localStorage.setItem("searchResults",savedResults);}}
function restoreSearchResults(){if(savedResults){const searchHits=document.getElementById("search-hits");if(searchHits){searchHits.innerHTML=savedResults;}}}
function isModalVisible(){return(getComputedStyle(searchModal).display!=="none"&&searchModal.offsetParent!==null);}
function saveQuery(){const searchInput=document.getElementById("search-query");if(searchInput&&searchInput.value.trim()){savedQuery=searchInput.value;localStorage.setItem("searchQuery",savedQuery);}}
function forceRestoreQuery(){if(savedQuery){const searchInput=document.getElementById("search-query");if(searchInput){searchInput.value=savedQuery;searchInput.setAttribute("value",savedQuery);searchInput.defaultValue=savedQuery;searchInput.dispatchEvent(new Event("input",{bubbles:true}));}}}
const searchInput=document.getElementById("search-query");if(searchInput){const originalDescriptor=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value");Object.defineProperty(searchInput,"value",{get:function(){const currentValue=originalDescriptor.get.call(this);if(!currentValue&&savedQuery&&isModalVisible()){return savedQuery;}
return currentValue;},set:function(newValue){if(!newValue&&savedQuery&&isModalVisible()){return;}
originalDescriptor.set.call(this,newValue);if(newValue&&newValue.trim()){savedQuery=newValue;localStorage.setItem("searchQuery",newValue);}},configurable:true,});searchInput.addEventListener("input",function(){if(this.value&&this.value.trim()){savedQuery=this.value;localStorage.setItem("searchQuery",this.value);}
const hasResults=hasSearchResults();const hasQuery=this.value.trim().length>0;window.searchModalPreventClose=hasResults||hasQuery;if(hasResults){setTimeout(saveSearchResults,200);}});if(savedQuery){originalDescriptor.set.call(searchInput,savedQuery);}}
new MutationObserver(function(mutations){mutations.forEach(function(mutation){if(mutation.type==="attributes"&&(mutation.attributeName==="style"||mutation.attributeName==="class")){const isVisible=isModalVisible();if(isVisible&&!this.wasVisible){if(savedQuery&&searchInput){const originalDescriptor=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value");originalDescriptor.set.call(searchInput,savedQuery);if(savedResults){restoreSearchResults();}
searchInput.dispatchEvent(new Event("input",{bubbles:true}));}}
this.wasVisible=isVisible;}});}).observe(searchModal,{attributes:true,attributeFilter:["style","class"],});searchModal.addEventListener("click",function(e){if(e.target===searchModal){const hasResults=hasSearchResults();const hasQuery=searchInput&&searchInput.value.trim().length>0;if(hasResults||hasQuery){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return false;}}});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&isModalVisible()){saveQuery();saveSearchResults();}});const searchHits=document.getElementById("search-hits");if(searchHits){new MutationObserver(function(mutations){mutations.forEach(function(mutation){if(mutation.type==="childList"&&hasSearchResults()){setTimeout(saveSearchResults,300);}});}).observe(searchHits,{childList:true,subtree:true});}},1000);});</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"Person","name":"Pablo Bernabeu","url":"https:\/\/pablobernabeu.github.io\/","jobTitle":"Researcher","worksFor":{"@type":"Organization","name":"University of Oxford"},"sameAs":["https://orcid.org/0000-0003-1083-2460","https://scholar.google.com/citations?user=DxD0QDoAAAAJ&hl=en","https://github.com/pablobernabeu","https://www.researchgate.net/profile/Pablo-Bernabeu","https://osf.io/25u3x/","https://figshare.com/authors/Pablo_Bernabeu/820703","https://www.linkedin.com/in/pablobernabeu/","https://www.youtube.com/@pablo-bernabeu"]}</script><title>Speculation across various scientific topics | Pablo Bernabeu</title></head><body id=top data-spy=scroll data-offset=70 data-target=#TableOfContents><aside class=search-results id=search><div class=container><section class=search-header><div class="row no-gutters justify-content-between mb-3"><div class=col-6><h2>Search</h2></div><div class="col-6 col-search-close"><a class=js-search href=# role=button aria-label="Close search"><i class="fas fa-times-circle text-muted" aria-hidden=true></i></a></div></div><div id=search-box><input name=q id=search-query aria-label=Search placeholder=Search... autocapitalize=off autocomplete=off autocorrect=off spellcheck=false type=search></div></section><section class=section-search-results><div id=search-hits></div></section></div></aside><nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id=navbar-main><a class=skip-link href=#main-content>Skip to main content</a><div class=container><div class="d-none d-lg-inline-flex"><a class=navbar-brand href=/>Pablo Bernabeu</a></div><button type=button class=navbar-toggler data-toggle=collapse data-target=#navbar-content aria-controls=navbar-content aria-expanded=false aria-label="Toggle navigation">
<span><i class="fas fa-bars"></i></span></button><div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none"><a class=navbar-brand href=/>Pablo Bernabeu</a></div><div class="navbar-collapse main-menu-item collapse justify-content-start" id=navbar-content><ul class="navbar-nav d-md-inline-flex"><li class=nav-item><a class=nav-link href=/#publication><span>Publications</span></a></li><li class=nav-item><a class=nav-link href=/#software><span><span data-toggle=tooltip1 data-placement=bottom title="&nbsp; Applications, dashboards and research packages &nbsp;">Software</span></span></a></li><li class=nav-item><a class=nav-link href=/#workshops><span><span data-toggle=tooltip1 data-placement=bottom title="&nbsp; Presentations and workshops &nbsp;">Presentations</span></span></a></li><li class=nav-item><a class=nav-link href=/#bio><span><span data-toggle=tooltip1 data-placement=bottom title="&nbsp; Contact &nbsp; | &nbsp; CV &nbsp; | &nbsp; Work &nbsp; | &nbsp; Education &nbsp; | &nbsp; Teaching and supervision &nbsp; | &nbsp; Funding &nbsp; | &nbsp; Other work &nbsp; | &nbsp; Skills &nbsp;">CV+</span></span></a></li><li class=nav-item><a class=nav-link href=/#multimedia><span><span data-toggle=tooltip1 data-placement=bottom title="&nbsp; Videos and podcasts &nbsp;">Multimedia</span></span></a></li><li class=nav-item><a class=nav-link href=/#blog><span><span data-toggle=tooltip1 data-placement=bottom title="&nbsp; Short essays &nbsp; | &nbsp; Tutorials &nbsp; | &nbsp; Inquiries &nbsp; | &nbsp; Functions for the implementation of experiments, data analysis and other purposes &nbsp;">Resources</span></span></a></li><li class=nav-item><a class=nav-link href=/#><span><i class="fas fa-search js-search-trigger" aria-hidden=true></i><span class="d-lg-none js-search-trigger">Search</span></span></a></li></ul></div><ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2"><li class="nav-item dropdown"><button type=button class="nav-link js-font-size-toggle" aria-label="Text size options" aria-haspopup=true aria-expanded=false><i class="fas fa-text-height" aria-hidden=true></i></button><div class="dropdown-menu dropdown-menu-right font-size-menu"><a class="dropdown-item js-font-increase" href=javascript:void(0)><i class="fas fa-plus"></i>Larger font</a>
<a class="dropdown-item js-font-reset" href=javascript:void(0)><i class="fas fa-undo"></i>Reset</a>
<a class="dropdown-item js-font-decrease" href=javascript:void(0)><i class="fas fa-minus"></i>Smaller font</a></div></li><li class="nav-item dropdown theme-dropdown"><button type=button class="nav-link js-theme-toggle" aria-label="Colour theme options" aria-haspopup=true aria-expanded=false><i class="fas fa-adjust" aria-hidden=true></i></button><div class="dropdown-menu dropdown-menu-right theme-menu"><a class="dropdown-item js-set-theme-light" href=javascript:void(0)><i class="fas fa-sun"></i>Light</a>
<a class="dropdown-item js-set-theme-dark" href=javascript:void(0)><i class="fas fa-moon"></i>Dark</a></div></li></ul></div><a id=main-content class=skip-target tabindex=-1></a></nav><article class=article><div class="article-container pt-3"><h1>Speculation across various scientific topics</h1><div style=display:flex;align-items:center;flex-wrap:wrap><div class=article-metadata><span style=font-size:100%>2026</span>
<span class=middot-divider></span><span class=article-categories><i class="fas fa-folder mr-1"></i><a href=/categories/science/>science</a>, <a href=/categories/bibliometrics/>bibliometrics</a></span></div></div></div><div class=article-container><section class="article-abstract mb-4" aria-labelledby=article-abstract-heading><h2 id=article-abstract-heading>Abstract</h2><p>This descriptive bibliometric analysis compares annual Scopus counts that mention speculat* in the title, abstract or keywords across nine query-defined literatures. It treats the percentage as an indicator of explicit wording in indexed records, not as a direct measure of evidential quality, theoretical progress or the amount of speculation in the full literature, and makes the queries and refreshed data available for inspection.</p></section><div class=article-style><script src=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/index.en_files/clipboard/clipboard.min.js></script><link href=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/index.en_files/xaringanExtra-clipboard/xaringanExtra-clipboard.css rel=stylesheet><script src=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/index.en_files/xaringanExtra-clipboard/xaringanExtra-clipboard.js></script><script>window.xaringanExtraClipboard(null,{"button":"Copy Code","success":"Copied!","error":"Press Ctrl+C to Copy"})</script><h2>Introduction</h2><div class="alert alert-info" role=alert style=padding-bottom:0;margin-bottom:6%><p>Given all of the data that E&L [Evans & Levinson, 2009] cite, how could anyone maintain the notion of a universal grammar with linguistic content? Traditionally, there have been three basic strategies. First, just as we may force English grammar into the Procrustean bed of Latin grammar – that is how I was taught the structure of English in grade school – the grammars of the world’s so-called exotic languages may be forced into an abstract scheme based mainly on European languages.</p><p>— Tomasello (2009)</p></div><p>Some research topics invite more explicit conjecture than others. In a review of language evolution, Pieter Vogt and I noted that direct evidence is necessarily limited for many proposed historical processes (Bernabeu & Vogt, 2015). That observation is not an empirical ranking of literatures, and database counts cannot supply one. They can, however, show how often authors use a particular family of words in the title, abstract or keyword fields that Scopus indexes.</p><p>Authors who speculate in print sometimes say so, in phrases such as “we speculate that” or “it is tempting to speculate”. The share of records that contain a form of <code>speculat*</code> is therefore an indicator of explicit wording in indexed metadata. It is not a measure of how much speculation an article contains, how well supported its claims are or how mature a research area is. Conventions for hedging, abstract writing and indexing can all affect the count.</p><p>This post compares that share, year by year from 1980 to the present, across nine reference literatures. Six of them concern language: language evolution, language comprehension, language disorders, linguistic relativity, language teaching and the bilingual advantage. A seventh, sensorimotor simulation, is the topic of my own doctoral work on conceptual processing. The last two, artificial general intelligence and the hadron collider, sit outside the language sciences and serve as points of comparison, one being a field where speculation might be expected and the other a field of large instruments and large collaborations. Each reference literature is defined by a query on the title, abstract and keywords, and the comparison counts, within each year, the records that also match <code>speculat*</code> in the same fields.</p><div id=development-the-searches class="section level2"><h2>Development: the searches</h2><p>An earlier draft of this post ran the searches through a set of functions that I had written around the rscopus package. Those functions have since become the <a href=/2026/scopusflow-a-literature-search-you-can-rerun/>scopusflow package</a>, and the searches now live in a script in the <a href=https://github.com/pablobernabeu/website-files/blob/master/scripts/update_post_searches.R>website’s repository</a> that a GitHub Actions workflow runs on request, with the Scopus key held as a repository secret. The workflow commits the counts to the post’s directory, so the figures below can be rebuilt from the committed data without a key, and the searches can be refreshed by anyone with a key by dispatching the workflow. The nine queries are given below.</p><pre class=r><code>library(scopusflow)

years &lt;- 1980:as.integer(format(Sys.Date(), &#39;%Y&#39;))

topics &lt;- c(
  &#39;language evolution&#39;              = &#39;&quot;language evolution&quot; OR &quot;evolution of language&quot;&#39;,
  &#39;language comprehension&#39;          = &#39;&quot;language comprehension&quot;&#39;,
  &#39;language disorders&#39;              = &#39;&quot;language disorders&quot; OR &quot;language disorder&quot;&#39;,
  &#39;linguistic relativity&#39;           = &#39;&quot;linguistic relativity&quot;&#39;,
  &#39;language teaching&#39;               = &#39;&quot;language teaching&quot;&#39;,
  &#39;bilingual advantage&#39;             = &#39;&quot;bilingual advantage&quot; OR &quot;bilingual advantages&quot;&#39;,
  &#39;sensorimotor simulation&#39;         = &#39;&quot;sensorimotor simulation&quot;&#39;,
  &#39;artificial general intelligence&#39; = &#39;&quot;artificial general intelligence&quot;&#39;,
  &#39;hadron collider&#39;                 = &#39;&quot;hadron collider&quot;&#39;
)

comparisons &lt;- lapply(names(topics), function(label) {
  cmp &lt;- scopus_compare_topics(
    reference_query  = topics[[label]],
    comparison_terms = &#39;speculat*&#39;,
    years            = years,
    field            = &#39;TITLE-ABS-KEY&#39;
  )
  cmp$topic &lt;- label
  cmp
})</code></pre><p>The function counts, for every year, the records matching the reference query and the records matching both the reference query and the comparison term, so the nine comparisons cost 846 count requests. Each row of the result holds a year, the count for the reference literature, the count for the comparison and the comparison as a percentage of the reference.</p><pre class=r><code>library(dplyr)
library(ggplot2)

comparisons &lt;- readRDS(&#39;searches/speculation_comparisons.rds&#39;)
retrieved &lt;- attr(comparisons, &#39;retrieved&#39;)
retrieved</code></pre><pre><code>#&gt; [1] &quot;2026-09-02 06:36 UTC&quot;</code></pre><pre class=r><code>speculation &lt;- bind_rows(comparisons) |&gt;
  filter(query_type == &#39;comparison&#39;) |&gt;
  transmute(topic, year, reference_n, n,
            percentage = comparison_percentage)
head(speculation)</code></pre><pre><code>#&gt; # A tibble: 6 × 5
#&gt;   topic               year reference_n     n percentage
#&gt;   &lt;chr&gt;              &lt;int&gt;       &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 language evolution  1980           5     0          0
#&gt; 2 language evolution  1981           4     0          0
#&gt; 3 language evolution  1982           4     0          0
#&gt; 4 language evolution  1983           1     0          0
#&gt; 5 language evolution  1984           5     0          0
#&gt; 6 language evolution  1985           6     0          0</code></pre><p>The searches were run on 2 September 2026, so the final year is incomplete and its share rests on fewer records than the years before it.</p></div><div id=results-sizes-of-the-literatures class="section level2"><h2>Results: sizes of the literatures</h2><p>The nine literatures differ in size by orders of magnitude, and the size matters for reading the percentages. A share computed on a few dozen records moves by several points when one or two abstracts mention speculation, whereas a share computed on thousands of records barely moves at all.</p><pre class=r><code>totals &lt;- speculation |&gt;
  group_by(topic) |&gt;
  summarise(records = sum(reference_n), with_speculation = sum(n),
            share = 100 * with_speculation / records,
            first_year_with_records = min(year[reference_n &gt; 0])) |&gt;
  arrange(desc(share))
totals</code></pre><pre><code>#&gt; # A tibble: 9 × 5
#&gt;   topic                           records with_speculation share first_year_with_records
#&gt;   &lt;chr&gt;                             &lt;dbl&gt;            &lt;dbl&gt; &lt;dbl&gt;                   &lt;int&gt;
#&gt; 1 artificial general intelligence    1913               49 2.56                     2006
#&gt; 2 language evolution                 3376               48 1.42                     1980
#&gt; 3 linguistic relativity               739                9 1.22                     1980
#&gt; 4 bilingual advantage                 637                4 0.628                    1993
#&gt; 5 language comprehension             6543               24 0.367                    1980
#&gt; 6 language disorders                14255               36 0.253                    1980
#&gt; 7 language teaching                 22957               42 0.183                    1980
#&gt; 8 hadron collider                   18457               20 0.108                    1980
#&gt; 9 sensorimotor simulation             132                0 0                        2003</code></pre><p>Across the whole period, the share of records that mention speculation is highest in the literature on artificial general intelligence (2.6%) and lowest in sensorimotor simulation (0.0%), with the language literatures spread between those two.</p><pre class=r><code># Nine literatures against an eight-colour palette, so the Okabe-Ito set is
# extended with one grey. Nine lines on one panel are hard to tell apart by
# colour alone, which is why the figure that follows gives each its own panel.
nine_colours &lt;- c(&#39;#E69F00&#39;, &#39;#56B4E9&#39;, &#39;#009E73&#39;, &#39;#F0E442&#39;, &#39;#0072B2&#39;,
                  &#39;#D55E00&#39;, &#39;#CC79A7&#39;, &#39;#999999&#39;, &#39;#000000&#39;)
ggplot(filter(speculation, reference_n &gt; 0),
       aes(year, reference_n, colour = topic)) +
  geom_line(linewidth = 0.8) +
  scale_y_log10(labels = scales::label_comma()) +
  scale_colour_manual(values = nine_colours) +
  labs(x = NULL, y = &#39;Records per year (log scale)&#39;, colour = NULL) +
  theme_minimal(base_size = 12) +
  theme(legend.position = &#39;right&#39;)</code></pre><p><img src=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/index.en_files/figure-html/unnamed-chunk-4-1.png alt="Line chart on a logarithmic axis of the number of Scopus records per year in each of the nine reference literatures from 1980 onwards" width=768 style=display:block;margin:auto></p></div><div id=the-share-of-records-that-mention-speculation class="section level3"><h3>The share of records that mention speculation</h3><p>Each panel below shows one literature. The line is the yearly percentage of records that also match <code>speculat*</code>, the shaded band is a stability range computed by the Wilson method from the two yearly counts, which conveys how much the share would move with a handful of records, and the panels are ordered from the most to the least speculative literature over the whole period. The axis is cut at 15%, which clips the bands in the early years of the small literatures, where a single abstract would move the share by tens of points. The highest share in the data, the 33% that 1 of the 3 records on bilingual advantage in 2006 represent, sits above that cut and is clipped with them. Years in which a literature has no records break the line.</p><pre class=r><code>wilson &lt;- function(k, n, z = 1.96) {
  p &lt;- k / n
  centre &lt;- (p + z^2 / (2 * n)) / (1 + z^2 / n)
  half &lt;- z * sqrt(p * (1 - p) / n + z^2 / (4 * n^2)) / (1 + z^2 / n)
  data.frame(lower = 100 * pmax(0, centre - half), upper = 100 * pmin(1, centre + half))
}

# Years with no records keep their row but carry NA, so that ggplot2 breaks the
# line there instead of drawing a segment across a gap in the literature.
panel_data &lt;- speculation |&gt;
  mutate(topic = factor(topic, levels = totals$topic)) |&gt;
  bind_cols(wilson(speculation$n, speculation$reference_n)) |&gt;
  mutate(across(c(percentage, lower, upper), ~ ifelse(reference_n &gt; 0, .x, NA_real_)))

panel_labels &lt;- totals |&gt;
  mutate(label = sprintf(&#39;%s\n%s records, %.1f%% with speculat*&#39;,
                         topic, format(records, big.mark = &#39;,&#39;), share))
labeller_topic &lt;- setNames(panel_labels$label, panel_labels$topic)

ggplot(panel_data, aes(year, percentage)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = &#39;#0072B2&#39;, alpha = 0.15) +
  geom_line(colour = &#39;#0072B2&#39;, linewidth = 0.7) +
  geom_point(colour = &#39;#0072B2&#39;, size = 0.9) +
  facet_wrap(~ topic, ncol = 3, labeller = as_labeller(labeller_topic)) +
  scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  coord_cartesian(ylim = c(0, 15)) +
  labs(x = NULL, y = &#39;Records mentioning speculation (%)&#39;) +
  theme_minimal(base_size = 12) +
  theme(strip.text = element_text(size = 10, hjust = 0),
        panel.spacing = unit(1.2, &#39;lines&#39;))</code></pre><p><img src=https://pablobernabeu.github.io/2026/speculation-across-various-scientific-topics/index.en_files/figure-html/unnamed-chunk-5-1.png alt="Nine panels, one per literature, each showing the yearly percentage of Scopus records that mention speculation over the years in which that literature has records, with a shaded Wilson interval" width=864 style=display:block;margin:auto></p><pre class=r><code>recent &lt;- speculation |&gt;
  filter(year &gt;= 2016, year &lt;= max(year) - 1) |&gt;
  group_by(topic) |&gt;
  summarise(records = sum(reference_n),
            share = 100 * sum(n) / sum(reference_n)) |&gt;
  arrange(desc(share))
recent</code></pre><pre><code>#&gt; # A tibble: 9 × 3
#&gt;   topic                           records  share
#&gt;   &lt;chr&gt;                             &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 artificial general intelligence    1377 2.54  
#&gt; 2 linguistic relativity               374 1.60  
#&gt; 3 language evolution                 1734 1.56  
#&gt; 4 bilingual advantage                 445 0.449 
#&gt; 5 language comprehension             3298 0.334 
#&gt; 6 language disorders                 6511 0.230 
#&gt; 7 language teaching                 15193 0.178 
#&gt; 8 hadron collider                    7682 0.0781
#&gt; 9 sensorimotor simulation              88 0</code></pre><p>Restricting the comparison to the last ten complete years, 88 to 15,193 records per literature, gives the ranking above. The literature on artificial general intelligence leads with 2.5% of its records mentioning speculation, and that on sensorimotor simulation closes the list with 0.0%.</p></div><div id=discussion-what-the-counts-can-and-cannot-show class="section level2"><h2>Discussion: what the counts can and cannot show</h2><p>The measure is crude in ways that the figures make visible. A form of ‘speculate’ in an abstract is as often a mark of candour as of conjecture, since the authors who write ‘we speculate that’ are labelling a claim that others would present without a label, and a literature with a strong convention of hedged abstracts will score higher for that reason alone. The wildcard also catches ‘speculative’ in senses that have nothing to do with scientific conjecture, such as speculative execution in computing or speculative investment in economics, and both senses can occur in the literatures on artificial general intelligence and on the hadron collider, whose funding is discussed in economic terms. The queries define each literature by a phrase, so records that belong to a field without using its name are missed, and the literatures on language teaching and language disorders are far larger than their phrases suggest. Percentages for the early years, when a literature had a handful of records, are shown with their intervals so that a single abstract is not read as a trend.</p><p>The smallest literature, sensorimotor simulation, contains no record that mentions speculation at all, which with 132 records over the whole period says more about the size of the literature than about its habits.</p><p>With those limits in mind, the observed differences describe the wording of these particular queries and records, rather than an ordering of fields by evidence or maturity. Some literatures may use more explicit hedging in abstracts, and query design can change both the numerator and denominator. The data are most useful as a transparent starting point for reading records and revising searches. Anyone who wants to add a topic or inspect a later refresh can dispatch the workflow from the repository.</p><div id=references class="section level2"><h2>References</h2><p>Bernabeu, P., & Vogt, P. (2015). <em>Language evolution: Current status and future directions</em> [Paper presentation]. Tenth Language at the University of Essex (LangUE) Postgraduate Conference, Colchester, United Kingdom. <a href=https://www.researchgate.net/publication/280858062_Language_evolution_Current_status_and_future_directions class=uri>https://www.researchgate.net/publication/280858062_Language_evolution_Current_status_and_future_directions</a></p><p>Evans, N., & Levinson, S. C. (2009). The myth of language universals: Language diversity and its importance for cognitive science. <em>Behavioral and Brain Sciences</em>, <em>32</em>(5), 429–492. <a href=https://doi.org/10.1017/S0140525X0999094X class=uri>https://doi.org/10.1017/S0140525X0999094X</a></p><p>Tomasello, M. (2009). Universal grammar is dead. <em>Behavioral and Brain Sciences</em>, <em>32</em>(5), 470–471. <a href=https://doi.org/10.1017/S0140525X09990744 class=uri>https://doi.org/10.1017/S0140525X09990744</a></p></div></div></div><div class=article-tags><a class="badge badge-light" href=/tags/s/>s</a>
<a class="badge badge-light" href=/tags/linguistics/>linguistics</a>
<a class="badge badge-light" href=/tags/language/>language</a>
<a class="badge badge-light" href=/tags/bibliometrics/>bibliometrics</a>
<a class="badge badge-light" href=/tags/scopus/>Scopus</a>
<a class="badge badge-light" href=/tags/research-methods/>research methods</a></div><section id=comments><div id=disqus_thread><p class=text-muted>Comments are provided by Disqus and are not loaded automatically. Loading them connects your browser to Disqus, which may use cookies and process data under its
<a href=https://help.disqus.com/en/articles/1717103-disqus-privacy-policy>privacy policy</a>.
See this site's <a href=/privacy/>privacy notice</a> for details.</p><button type=button id=load-disqus-comments class="btn btn-outline-primary">Load comments from Disqus</button><p id=disqus-status class="small text-muted mt-2" role=status aria-live=polite></p><noscript>JavaScript is required to load Disqus comments.</noscript></div><script>(function(){var button=document.getElementById('load-disqus-comments');var status=document.getElementById('disqus-status');if(!button){return;}
button.addEventListener('click',function(){button.disabled=true;status.textContent='Loading comments from Disqus…';window.disqus_config=function(){};var script=document.createElement('script');script.src='https://pablobernabeu-github-io.disqus.com/embed.js';script.async=true;script.setAttribute('data-timestamp',String(+new Date()));script.addEventListener('error',function(){button.disabled=false;button.textContent='Try loading comments again';status.textContent='Disqus could not be loaded.';});(document.head||document.body).appendChild(script);});})();</script></section></div></article><script src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin=anonymous></script><script src=https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin=anonymous></script><script src=https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin=anonymous></script><script src=https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin=anonymous></script><script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin=anonymous></script><script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js></script><script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/htmlbars.min.js></script><script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/css.min.js></script><script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/javascript.min.js></script><script>const code_highlighting=true;</script><script>const isSiteThemeDark=false;</script><script>const search_config={"indexURI":"/index.json","minLength":2,"threshold":0.3};const i18n={"no_results":"No results found","placeholder":"   Search...","results":"results found"};const content_type={'post':"Posts",'project':"Projects",'publication':"Publications",'presentation':"Presentations"};</script><script id=search-hit-fuse-template type=text/x-template>
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}" onclick="event.preventDefault(); window.location.href = this.href;">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script><script src=https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin=anonymous></script><script src=https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin=anonymous></script><script src=/js/academic.min.20e4368ae396e7ff1db471634ab9e548.js></script><script src=/js/indexnow.js></script><script>document.addEventListener('DOMContentLoaded',function(){if(window.innerWidth<=991){const toggler=document.querySelector('.navbar-toggler');const navbarCollapse=document.querySelector('#navbar-content');if(toggler&&navbarCollapse){toggler.addEventListener('mouseenter',function(){if(!navbarCollapse.classList.contains('show')){$(navbarCollapse).collapse('show');}});}}
if(typeof $!=='undefined'){$('[data-toggle="tooltip"]').tooltip('disable');$('[data-toggle="popover"]').popover('disable');}});</script><script src=/js/article-ancillary-tags.js defer></script><div class=container><footer class=site-footer><p class=powered-by><a href=/privacy/>Privacy notice</a></p><p class=powered-by>Pablo Bernabeu, 2015–2026. Licence: <a href=https://creativecommons.org/licenses/by/4.0/>CC BY 4.0</a>. Email: <a href=mailto:pcbernabeu@gmail.com>pcbernabeu@gmail.com</a>. Third-party content may use cookies. &#183;
Website powered by the <a href=https://themes.gohugo.io/themes/starter-hugo-academic rel=noopener>Academic theme</a> for <a href=https://gohugo.io rel=noopener>Hugo</a> and by <a href=https://github.com/rstudio/blogdown rel=noopener>blogdown</a>.
<span class=float-right><a href=# class=back-to-top style=background-image:none aria-label="Back to top"><span class=button_icon style=background-image:none><i class="fas fa-chevron-up fa-2x" style=background-image:none aria-hidden=true></i></span></a></span></p></footer></div><div id=modal class="modal fade" role=dialog><div class=modal-dialog><div class=modal-content><div class=modal-header><h5 class=modal-title>Citation</h5><button type=button class=close data-dismiss=modal aria-label=Close>
<span aria-hidden=true>&#215;</span></button></div><div class=modal-body><pre><code class="tex hljs"></code></pre></div><div class=modal-footer><a class="btn btn-outline-primary my-1 js-copy-cite" href=#><i class="fas fa-copy"></i>Copy</a>
<a class="btn btn-outline-primary my-1 js-download-cite" href=#><i class="fas fa-download"></i>Download</a><div id=modal-error></div></div></div></div></div></body></html>