---
title: A Python inline script for OpenSesame to send EEG triggers via serial port
author: ''
date: '2023-09-09'
slug: an-inline-script-for-opensesame-to-send-eeg-triggers-via-the-serial-port
categories:
  - 
tags:
  - 
subtitle: ''
summary: 'Python inline script for OpenSesame enabling EEG trigger transmission via serial port for event-related potential experiments, synthesizing solutions from parallel port implementations and various Python platforms.'
authors: []
lastmod: ''
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


The [OpenSesame](https://osdoc.cogsci.nl) user base is skyrocketing but---of course---remains small in comparison to many other user bases that we are used to. Therefore, when developing an experiment in OpenSesame, there are still many opportunities to break the mould. When you need to do something beyond the standard operating procedure, it may take longer to find suitable resources than it takes when a more widespread tool is used. So, why would you still want to use OpenSesame? There are many reasons: it is free, open source, based on Python, stable enough thanks to more than a decade of usage and development, [well maintained](https://github.com/open-cogsci/OpenSesame), and has a [community forum](https://forum.cogsci.nl). 

I recently faced a challenge when developing an EEG experiment that uses event-related potentials. I couldn't find a way to send triggers through a *serial* port. Online, I could find several resources, such as a [script by Kate Stone that draws on a parallel port](https://stonekate.github.io/blog/opensesame), an [outdated plugin that also draws on a parallel port](https://github.com/esdalmaijer/opensesame_serial_port_trigger), and resources based on Python scripts in [PsychoPy](https://discourse.psychopy.org/t/sending-triggers-to-brainvision-eeg-system-from-psychopy-coderview/11011/11) and in [base Python](https://pyserial.readthedocs.io/en/latest/shortintro.html). By standing on these giants' shoulders, and on even more shoulders from [StackOverflow](https://stackoverflow.com/a/76829646/7050882), I put together the following inline script for OpenSesame. The code must be placed in the [`Prepare` phase](https://osdoc.cogsci.nl/4.0/manual/python/about/#inline_script-items). The `Run` phase can be empty. 

This script is used to set up the system for sending triggers to the EEG recording software (e.g., BrainVision Recorder). The code automatically looks for an available serial port at the beginning of the session. If there are any available ports, a connection is established to the first port in the list. If there are no available ports, no connection is established, and a warning is shown on the screen, informing the user that no triggers will be sent to the EEG recorder. In the latter case, the triggers are only printed in the OpenSesame console.

<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fpablobernabeu%2FEEG-tools-and-tips%2Fblob%2Fmain%2FOpenSesame_inline_script_to_send_EEG_triggers_via_serial_port%23L12-L300&style=a11y-dark&type=code&showLineNumbers=on&showFileMeta=on&showCopy=on"></script> 

