---
title: Intermixing stimuli from two loops randomly in OpenSesame
author: ''
date: '2023-06-24'
slug: intermixing-stimuli-from-two-loops-randomly-in-opensesame
categories:
  - research methods
tags:
  - OpenSesame
  - s
subtitle: ''
summary: 'Solution for randomly intermixing stimuli from two different loops in OpenSesame by distributing sentence words across columns and using conditional Run if statements to control presentation.'
authors: []
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


I'm developing a slightly tricky design in [OpenSesame](https://osdoc.cogsci.nl) (a Python-based experiment builder). My stimuli comprise two kinds of sentences that contain different elements, and different numbers of elements. These sentences must be presented word by word. Furthermore, I need to attach triggers to some words in the first kind of sentences but not in the second kind. Last, these kinds of sentences must be intermixed within a block (or a `sequence`) of trials, because the first kind are targets and the second kind are fillers.

I need to present stimuli randomly from either of two `loop`s within a `sequence`. Currently, when I try this arrangement using the interface, the resulting script ends up with `run loop1` followed by `run loop2`, but I can't find a way to ensure that the overarching sequence pulls randomly from either loop over successive trials. In other words, my goal is to intermix the stimuli from both loops. 

I have searched for clues in the OpenSesame tutorials, in the OpenSesame forum, and elsewhere online, but to no avail. 

## Solution

Finally, I solved this by first distributing all the words in each sentence across different columns in the stimulus file, yielding 'word1', 'word2', etc. Next, in OpenSesame, I created a sketchpad for each word. Last, to prevent showing any words that were blank, I entered conditions such as `[word7] != NA` in the <kbd>Run if</kbd> field of the sequence. 

