---
title: Unpacking ERP responses in artificial language learning 
authors: ['<span style="font-size:140%;">Pablo Bernabeu, Christina Athanasiadi, Gabriella Silva, Stella Lucia Pischinger, My Ngoc Giang Hoang, Vincent DeLuca, Jason Rothman, Claudia Poch, Iva Ivanova, Jorge González Alonso</span>']
author: ~
date: '2025-02-13'
slug: unpacking-erp-responses-in-artificial-language-learning
categories:
  - psycholinguistics
tags:
  - Third language acquisition
  - L3 learning
  - Artificial languages
  - Crosslinguistic influence
  - Crosslinguistic transfer
  - Language transfer
  - Bilingualism
  - Multilingualism
  - Cognitive functions
  - EEG
  - Language processing
  - Executive functions
  - Longitudinal study
  - Morphosyntax
  - Typological similarity
  - Individual differences
  - Language dominance
presentation_format: Talk
event: Lunch Seminar at the Center for Language, Brain and Learning (C-LaBL), UiT The Arctic University of Norway
event_url: 'https://uit.no/research/clabl'
location: ~
address:
  street: ~
  city: ~
  region: ~
  postcode: ~
  country: ~
summary: ~
abstract: "Third language acquisition often involves morphosyntactic transfer from previously acquired languages. Research suggests that crosslinguistic influence follows systematic patterns, with attention playing a role in selecting the source of transfer. This study investigates morphosyntactic transfer longitudinally using artificial languages distributed between groups in two sites: Norway (Mini-Norwegian and Mini-English) and Spain (Mini-Spanish and Mini-English). <br> The study consists of six sessions. Session 1 assesses attention-related executive functions and language history. Session 2 begins with resting-state electroencephalography (EEG) to measure attentional skills, followed by training on gender agreement (present in Norwegian and Spanish). Sessions 3 and 4 introduce differential object marking (present in Spanish) and verb-object agreement (absent from all three languages), respectively. Each session includes vocabulary pre-training, grammar training, a behavioural test, and an EEG experiment measuring event-related potentials (ERPs) in response to grammatical violations in a grammaticality judgement task. Session 5 reassesses cognitive measures, and Session 6, after four months, tests retention of all grammatical properties. <br> This presentation will focus on preliminary results with a methodological emphasis. We will first examine accuracy in the grammaticality judgements, which was generally high, before analysing a consistent P600-like effect associated with a control violation involving misplaced definite articles (e.g., *jestreet*), relative to a grammatical condition (e.g., *je street*). This effect likely reflects increased attentional demands during syntactic processing. Notably, this control effect is observed across artificial languages, sessions and brain regions (with greater strength in medial and posterior regions), providing a reference point for evaluating the ERPs associated with the grammatical properties of interest. After demonstrating and discussing this comparison, forthcoming analyses will be outlined, and feedback will be welcome."
date_end: ~
all_day: no
publishDate: ~
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
url_slides: https://osf.io/xevr9
url_data: https://osf.io/974k8
url_code: https://osf.io/974k8
url_poster: ~
url_video: ~
# links:
# - name: 
#   url: 
projects: []
---


<a href='https://mfr.osf.io/render?url=https://osf.io/xevr9/?direct%26mode=render%26action=download%26mode=render'>
      <button style = "background-color: white; color: black; border: 2px solid #196F27; border-radius: 12px;">
      <h3 style = "margin-top: 7px !important; margin-left: 9px !important; margin-right: 9px !important;"> 
      <span style="color:#DBE6DA;"></span> PDF slides </h3></button></a> &nbsp; 

<iframe src="https://www.slideshare.net/slideshow/embed_code/key/FWeoCwR0OycM7m?startSlide=1" width="700" height="394" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px;max-width: 100%;" allowfullscreen></iframe>


## Longer summary

Third language acquisition often involves morphosyntactic transfer from previously acquired languages. Research suggests that crosslinguistic influence follows systematic patterns, with attention playing a role in selecting the source of transfer. This study investigates morphosyntactic transfer longitudinally using artificial languages distributed between groups in two sites: Norway (Mini-Norwegian and Mini-English) and Spain (Mini-Spanish and Mini-English).

The study consists of six sessions. Session 1 assesses attention-related cognitive functions and language history through a home-based session that includes tasks such as the digit span task to evaluate working memory, the Stroop task for inhibitory control, and a serial reaction time task to assess implicit learning. Additionally, participants complete the Language History Questionnaire (LHQ3; Li et al., 2020) to provide comprehensive background information.

Session 2 commences with resting-state electroencephalography (EEG) recordings, conducted with eyes open and closed in counterbalanced order to measure attentional skills. This is followed by training on gender agreement, a property present in both Norwegian and Spanish. Participants engage in vocabulary pre-training, grammatical training, and a behavioural test, culminating in an EEG experiment where event-related potentials (ERPs) are recorded in response to grammatical violations.

A week later, Session 3 introduces differential object marking, which is present in Spanish but absent in Norwegian and English. Training focuses solely on this new property, while the EEG experiment tests both gender agreement and differential object marking together. Next, after another week, Session 4 introduces verb-object agreement, a property absent from all three languages, using the same training and testing structure.&#x20;

Session 5 involves a retest of executive functions, mirroring the tasks from Session 1 to examine longitudinal stability and pre-post changes. Due to the absence of a control group, pre-post changes are to be analysed only in relation to the baseline effects of the executive functions on Session 2 performance.&#x20;

Finally, Session 6, conducted four months later, tests the retention of all grammatical properties and includes control tests to assess knowledge of the relevant properties in the natural languages.

The artificial languages were designed with minimal confounding factors by avoiding cognates and ensuring morphological consistency across languages. Linguistic stimuli were counterbalanced across conditions to prevent spurious effects, with gender and number equally distributed. Stimuli creation and presentation were facilitated through modular R scripts and OpenSesame software, ensuring reproducibility, testability and reusability.

This presentation focusses on preliminary results from the Norwegian site, with a methodological emphasis. We first examine accuracy in the grammaticality judgements, which was generally high across participants. The Mini-English group exhibited higher accuracy than the Mini-Norwegian group, particularly for the property of gender agreement.&#x20;

Next, we will describe the ERP results for the various grammaticality conditions. The properties of interest did not exhibit clear effects. Instead, a P600-like positivity was observed in response to misplaced definite articles (e.g., *thestreet* versus *the street*), predominantly in medial and posterior brain regions. This positivity suggests increased syntactic processing demands when encountering ungrammatical forms. This control effect provides a useful point of reference to assess the results for the properties of interest. 

The mixed-effects models for gender agreement suggested that grammaticality interacted with session number, working memory and implicit learning. Cross-linguistic differences were also evident, with the Mini-English group displaying more robust effects than the Mini-Norwegian group.

These preliminary findings suggest that language learning is influenced by attentional mechanisms, with individual differences in executive functions playing a role. The P600 effects associated with the control condition of article misplacement provides a useful point of reference. Audience feedback on the methods and interpretations will be welcomed to guide the next stages of this research.


### References

Alday, P. M. (2019). How much baseline correction do we need in ERP research? Extended GLM model can replace baseline correction while lifting its limits. *Psychophysiology*, *56*(12), e13451. <https://doi.org/10.1111/psyp.13451>

Bardel, C., & Falk, Y. (2012). The L2 status factor and the declarative/procedural distinction. In J. Cabrelli, S. Flynn, & J. Rothman (Eds.), *Third Language Acquisition in Adulthood* (pp. 61--78). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.46.06bar>

Brauer, M., & Curtin, J. J. (2018). Linear mixed-effects models and the analysis of nonindependent data: A unified framework to analyze categorical and continuous independent variables that vary within-subjects and/or within-items. *Psychological Methods*, *23*(3), 389--411. <https://doi.org/10.1037/met0000159>

Desbordes, T., Lakretz, Y., Chanoine, V., Oquab, M., Badier, J.-M., Trébuchon, A., Carron, R., Bénar, C.-G., Dehaene, S., & King, J.-R. (2023). Dimensionality and ramping: Signatures of sentence integration in the dynamics of brains and deep language models. *Journal of Neuroscience*, *43*(29), 5350--5364. <https://doi.org/10.1523/JNEUROSCI.1163-22.2023>

Flynn, S., Foley, C., & Vinnitskaya, I. (2004). The cumulative-enhancement model for language acquisition: Comparing adults' and children's patterns of development in first, second and third language acquisition of relative clauses. *International Journal of Multilingualism*, *1*(1), 3--16. <https://doi.org/10.1080/14790710408668175>

Friederici, A. D., Steinhauer, K., & Pfeifer, E. (2002). Brain signatures of artificial language processing: Evidence challenging the critical period hypothesis. *Proceedings of the National Academy of Sciences*, *99*(1), 529--534. <https://doi.org/10.1073/pnas.012611199>

Fuhs, M. W., Nesbitt, K. T., Farran, D. C., & Dong, N. (2014). Longitudinal associations between executive functioning and academic skills across content areas. *Developmental Psychology*, *50*(6), 1698--1709. <https://doi.org/10.1037/a0036633>

González Alonso, J., Alemán Bañón, J., DeLuca, V., Miller, D., Pereira Soares, S. M., Puig-Mayenco, E., Slaats, S., & Rothman, J. (2020). Event related potentials at initial exposure in third language acquisition: Implications from an artificial mini-grammar study. *Journal of Neurolinguistics*, *56*, 100939. <https://doi.org/10.1016/j.jneuroling.2020.100939>

González Alonso, J., Bernabeu, P., Silva, G., DeLuca, V., Poch, C., Ivanova, I., & Rothman, J. (2025). Starting from the very beginning: Unraveling third language (L3) development with longitudinal data from artificial language learning and EEG. *International Journal of Multilingualism*, *22*(1), 119--142. <https://doi.org/10.1080/14790718.2024.2415993>

Grossmann, J. A., Aschenbrenner, S., Teichmann, B., & Meyer, P. (2023). Foreign language learning can improve response inhibition in individuals with lower baseline cognition: Results from a randomized controlled superiority trial. *Frontiers in Aging Neuroscience*, *15*. <https://doi.org/10.3389/fnagi.2023.1123185>

Hudson Kam, C. L., & Newport, E. L. (2005). Regularizing unpredictable variation: The roles of adult and child learners in language formation and change. *Language Learning and Development*, *1*(2), 151--195. <https://doi.org/10.1080/15475441.2005.9684215>

Just, M. A., & Carpenter, P. A. (1980). A theory of reading: From eye fixations to comprehension. *Psychological Review*, *87*(4), 329--354. <https://doi.org/10.1037/0033-295X.87.4.329>

Kidd, E. (2012). Implicit statistical learning is directly associated with the acquisition of syntax. *Developmental Psychology*, *48*(1), 171--184. <https://doi.org/10.1037/a0025405>

Kliesch, M., Pfenninger, S. E., Wieling, M., Stark, E., & Meyer, M. (2022). Cognitive benefits of learning additional languages in old adulthood? Insights from an intensive longitudinal intervention study. *Applied Linguistics*, *43*(4), 653--676. <https://doi.org/10.1093/applin/amab077>

Li, P., Zhang, F., Yu, A., & Zhao, X. (2020). Language History Questionnaire (LHQ3): An enhanced tool for assessing multilingual experience. *Bilingualism: Language and Cognition*, *23*(5), 938--944. <https://doi.org/10.1017/S1366728918001153>

Meister, C., Pimentel, T., Clark, T., Cotterell, R., & Levy, R. (2022). Analyzing wrap-up effects through an information-theoretic lens. In S. Muresan, P. Nakov, & A. Villavicencio (Eds.), *Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 2: Short Papers)* (pp. 20--28). Association for Computational Linguistics. <https://doi.org/10.18653/v1/2022.acl-short.3>

Meltzer, J. A., Kates Rose, M., Le, A. Y., Spencer, K. A., Goldstein, L., Gubanova, A., Lai, A. C., Yossofzai, M., Armstrong, S. E. M., & Bialystok, E. (2023). Improvement in executive function for older adults through smartphone apps: A randomized clinical trial comparing language learning and brain training. *Aging, Neuropsychology, and Cognition*, *30*(2), 150--171. <https://doi.org/10.1080/13825585.2021.1991262>

Monaghan, P., Donnelly, S., Alcock, K., Bidgood, A., Cain, K., Durrant, S., Frost, R. L. A., Jago, L. S., Peter, M. S., Pine, J. M., Turnbull, H., & Rowland, C. F. (2023). Learning to generalise but not segment an artificial language at 17 months predicts children's language skills 3 years later. *Cognitive Psychology*, *147*, 101607. <https://doi.org/10.1016/j.cogpsych.2023.101607>

Morgan-Short, K., Finger, I., Grey, S., & Ullman, M. T. (2012). Second language processing shows increased native-like neural responses after months of no exposure. *PLOS ONE*, *7*(3), e32974. <https://doi.org/10.1371/journal.pone.0032974>

Pereira Soares, S. M., Kupisch, T., & Rothman, J. (2022). Testing potential transfer effects in heritage and adult L2 bilinguals acquiring a mini grammar as an additional language: An ERP approach. *Brain Sciences*, *12*(5), 669. <https://doi.org/10.3390/brainsci12050669>

Rothman, J. (2011). L3 syntactic transfer selectivity and typological determinacy: The typological primacy model. *Second Language Research*, *27*(1), 107--127. <https://doi.org/10.1177/0267658310386439>

Rothman, J., Alemán Bañón, J., & González Alonso, J. (2015). Neurolinguistic measures of typological effects in multilingual transfer: Introducing an ERP methodology. *Frontiers in Psychology*, *6*. <https://doi.org/10.3389/fpsyg.2015.01087>

Sala, G., & Gobet, F. (2017). Does far transfer exist? Negative evidence from chess, music, and working memory training. *Current Directions in Psychological Science*, *26*(6), 515--520. <https://doi.org/10.1177/0963721417712760>

Samuels, W. E., Tournaki, N., Blackman, S., & Zilinski, C. (2016). Executive functioning predicts academic achievement in middle school: A four-year longitudinal study. *The Journal of Educational Research*, *109*(5), 478--490. <https://doi.org/10.1080/00220671.2014.979913>

Stowe, L. A., Kaan, E., Sabourin, L., & Taylor, R. C. (2018). The sentence wrap-up dogma. *Cognition*, *176*, 232--247. <https://doi.org/10.1016/j.cognition.2018.03.011>

Swanson, H. L. (2015). Growth in working memory and inhibition predicts literacy in English language learners: A cross-sectional and longitudinal study. *Memory*, *23*(5), 748--773. <https://doi.org/10.1080/09658211.2014.927504>

Uddén, J., & Männel, C. (2018). Artificial grammar learning and its neurobiology in relation to language processing and development. In S.-A. Rueschemeyer & M. G. Gaskell (Eds.), *The Oxford Handbook of Psycholinguistics* (p. 0). Oxford University Press. <https://doi.org/10.1093/oxfordhb/9780198786825.013.33>

Wendebourg, K., Öttl, B., Meurers, D., & Kaup, B. (2025). Semantic information boosts the acquisition of a novel grammatical system in different presentation formats. *Language and Cognition*, *17*, e30. <https://doi.org/10.1017/langcog.2023.47>

Westergaard, M., Mitrofanova, N., Mykhaylyk, R., & Rodina, Y. (2017). Crosslinguistic influence in the acquisition of a third language: The Linguistic Proximity Model. *International Journal of Bilingualism*, *21*(6), 666--682. <https://doi.org/10.1177/1367006916648859>

