---
title: '`4authors-year-doi-url`: Minimal, numeric CSL style for documents with extreme space constraints'
author: ''
date: '2025-10-22'
slug: 4authors-year-doi-url
categories:
  - research methods
tags:
  - bibliometrics
  - CSL
  - reference styles
  - s
subtitle: ''
summary: '`4authors-year-doi-url` is a CSL style designed to be as compact as possible while retaining the three most critical pieces of information for a reference: who (authors), when (year), and where to find it (DOI/URL).'
authors: []
lastmod: ~
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


The [`4authors-year-doi-url` CSL style](https://github.com/pablobernabeu/4authors-year-doi-url/blob/main/4authors-year-doi-url.csl) is designed to be as compact as possible---ideal for posters, slides and abstracts---while retaining the three most critical pieces of information for a reference: **who** (authors), **when** (year) and **where** (DOI/URL). 

## Features

- **In-Text Citations:** Simple, superscripted numbers (e.g., <sup>1</sup>, <sup>2</sup>, <sup>3</sup>).

- **Bibliography:**

  - Numeric: A numbered list, ordered by appearance in the text.

  - No Titles: Article and book titles are completely omitted to save space.

- **Authors:**

  - 1-3 Authors: All authors are listed.

  - 4+ Authors: Lists the first 3 authors, followed by an ellipsis (…) and the last author.

- **Year:** The publication year is included in parentheses.

- **(DOI) URL:** The reference ends with a DOI URL or another available URL.

## Examples

### In-Text Citation

> We also recognise the many-to-many relationship between forms of knowledge and skills.<sup>2</sup> To build a predictive model, we will analyse interactions between reader-level factors and a comprehensive set of computationally-derived text variables.<sup>5–8</sup>

### Bibliography

<blockquote class = 'no-bullets' style = 'font-size: 67%; padding-left: -45%; padding-top: 2%; padding-bottom: 0.03%;'>

1. Orben, A., & Przybylski, A. K. (2019). https://doi.org/10.1177/0956797619830329

2. Hattan, C., & Kendeou, P. (2024). https://doi.org/10.1080/00461520.2024.2418048

3. Mathers, S. J., Kolancali, P., Jelley, F., … Murphy, V. A. (2025). https://doi.org/10.1016/j.edurev.2025.100665

4. Li, S., Hiver, P., & Papi, M. (Eds). (2022). https://doi.org/10.4324/9781003270546

5. Nielsen, J. L., Christensen, R. V., & Poulsen, M. (2025). https://doi.org/10.1002/rrq.70003

6. Kaup, B., Günther, F., & Dudschig, C. (2025). https://doi.org/10.1016/bs.plm.2025.08.001

7. Martinc, M., Pollak, S., & Robnik-Šikonja, M. (2021). https://doi.org/10.1162/coli_a_00398

8. Bernabeu, P. (2022). https://doi.org/10.17635/lancaster/thesis/1795

9. Blasi, D. E., Henrich, J., Adamou, E., … Majid, A. (2022). https://doi.org/10.1016/j.tics.2022.09.015

</blockquote>

## How to Use

1. Download the [4authors-year-doi-url.csl file](https://github.com/pablobernabeu/4authors-year-doi-url/blob/main/4authors-year-doi-url.csl) from GitHub.

2. Add the file to your reference manager:

  - Zotero:

    1. Go to Edit > Preferences.

    2. Go to the Cite tab and click the Styles sub-tab.

    3. Click the + button and select the .csl file you downloaded.

  - Mendeley:

    1. Go to View > Citation Style > More Styles....

    2. Go to the Custom Styles tab.

    3. Drag and drop the .csl file onto the page.

  - Other Platforms: Most reference managers (e.g., EndNote, Papers) have an option to add a custom CSL style. Consult their documentation for specific instructions.

3. Select `4authors-year-doi-url` as the citation style in your reference manager and word processor. 
