---
title: 'Starting from the very beginning: Unraveling third language (L3) development with longitudinal data from artificial language learning and related epistemology'
authors: ['González Alonso, J., **Bernabeu, P.**, Silva, G., DeLuca, V., Poch, C., Ivanova, I., & Rothman, J.']
publishDate: '2024-11-01'
date: '2025-01-01'
slug: third-language-longitudinal-data-artificial-language-learning-eeg
categories:
  - research methods
  - psycholinguistics
tags:
  - Third language acquisition
  - L3 learning
  - Artificial languages
  - Crosslinguistic influence
  - Crosslinguistic transfer
  - Language transfer
  - Bilingualism
  - Multilingualism
  - Cognitive functions
  - EEG
  - Language processing
  - Executive functions
  - Longitudinal study
  - Morphosyntax
  - Typological similarity
  - Individual differences
  - Language dominance
doi: 10.1080/14790718.2024.2415993
publication_types:
  - '2'
preregistered: true
open_materials: true
open_data: false
publication: '*International Journal of Multilingualism*'
publication_short: ''
abstract: "The burgeoning field of third language (L3) acquisition has increasingly focused on intermediate stages of language development, aiming to establish the groundwork for comprehensive models of L3 learning that encompass the entire developmental sequence. This article underscores the importance of a robust epistemological foundation, advocating for incremental knowledge building through longitudinal research. In the study presented here, we use artificial languages to investigate L3 acquisition from initial exposure with complete input control, factoring in individual differences in executive functions and history of bilingual exposure/engagement to assess the role of these variables in shaping learning trajectories and modulating cross-linguistic influence (CLI). This approach not only advances our understanding of L3 development under controlled conditions but also links L3 acquisition research to broader cognitive science inquiries."
summary: ~
featured: no
url_fulltext: https://www.tandfonline.com/doi/epdf/10.1080/14790718.2024.2415993
url_code: https://osf.io/974k8
url_data: ~
url_poster: https://osf.io/3ba9y
url_project: https://osf.io/974k8
url_slides: https://osf.io/4wfvb
url_source: ~
url_video: ~
links:
- name: Preregistration
  url: https://osf.io/tjr54
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
slides: ''
---


#### &nbsp; <i class="fa fa-file"></i>&nbsp; <a href='https://osf.io/tjr54'>Read the preregistration</a>

### Reference

González Alonso, J., Bernabeu, P., Silva, G., DeLuca, V., Poch, C., Ivanova, I., & Rothman, J. (2025). Starting from the very beginning: Unraveling third language (L3) development with longitudinal data from artificial language learning and related epistemology. *International Journal of Multilingualism, 1*(22), 119–142. https://doi.org/10.1080/14790718.2024.2415993

### Materials

Documentation practices and open-source software (namely, R and OpenSesame) were used to prepare the materials for the current study. In previous similar studies, the materials have not generally been very Findable, Accessible, Interoperable or Reusable (Cross et al., 2021; González Alonso et al., 2020; Mitrofanova et al., 2023; Morgan-Short et al., 2012; Pereira Soares et al., 2022). In contrast, in our current study, the stimuli were prepared in R using a modular framework that consisted of interoperable components (see https://osf.io/974k8). The modularity of this method facilitates the expansion of the materials within the same languages and to other languages. Specifically, the minimal components of each language were contained in a base file in the ‘stimulus_preparation’ folder. Furthermore, for the creation of the final stimuli, several controls were exerted to prevent spurious effects. For instance, gender and number were counterbalanced across experimental conditions, words were rotated across grammatical properties and sessions, and frequency of occurrence was controlled. The final stimuli can be recreated using the script ‘compile_all_stimuli.R’, and the resulting stimuli are saved to the ‘session_materials’ folder. Furthermore, the final stimuli were presented using OpenSesame, which is a free-of-charge software supporting experiments in the social sciences. The implementation of the four lab-based sessions in OpenSesame involved the use of conditions for controlling the engagement of certain items. In conclusion, the materials of the current study are accessible, and the workflow is reproducible. As a result, the final materials are testable, modifiable and expandable, improving long-term efficiency.

#### References

Cross, Z. R., Zou-Williams, L., Wilkinson, E. M., Schlesewsky, M., & Bornkessel-Schlesewsky, I. (2021). Mini Pinyin: A modified miniature language for studying language learning and incremental sentence processing. *Behavior Research Methods, 53*(3), 1218–1239. https://doi.org/10.3758/s13428-020-01473-6

González Alonso, J., Alemán Bañón, J., DeLuca, V., Miller, D., Pereira Soares, S. M., Puig-Mayenco, E., Slaats, S., & Rothman, J. (2020). Event related potentials at initial exposure in third language acquisition: Implications from an artificial mini-grammar study. *Journal of Neurolinguistics, 56*, 100939. https://doi.org/10.1016/j.jneuroling.2020.100939

Mitrofanova, N., Leivada, E., & Westergaard, M. (2023). Crosslinguistic influence in L3 acquisition: Evidence from artificial language learning. *Linguistic Approaches to Bilingualism, 13*(5), 717-742. https://doi.org/10.1075/lab.22063.mit

Morgan-Short, K., Finger, I., Grey, S., & Ullman, M. T. (2012). Second language processing shows increased native-like neural responses after months of no exposure. *PLOS ONE, 7*(3), e32974. https://doi.org/10.1371/journal.pone.0032974

Pereira Soares, S. M., Kupisch, T., & Rothman, J. (2022). Testing potential transfer effects in heritage and adult L2 bilinguals acquiring a mini grammar as an additional language: An ERP approach. *Brain Sciences, 12*(5), Article 5. https://doi.org/10.3390/brainsci12050669


### Podcast

<i class="fa-solid fa-wand-magic-sparkles" style='color:darkgrey;'></i> <span style='color:darkgrey; font-style:italic; font-size:85%;'>Created using Google Gemini and NotebookLM.</span>

<iframe allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write" frameborder="0" height="175" style="width:100%;max-width:660px;overflow:hidden;border-radius:10px;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.podcasts.apple.com/us/podcast/third-language-learning-and-morphosyntactic-transfer/id1837010092?i=1000733160897"></iframe>

<iframe allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write" frameborder="0" height="175" style="width:100%;max-width:660px;overflow:hidden;border-radius:10px;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.podcasts.apple.com/us/podcast/the-modular-mini-grammar-building-testable/id1837010092?i=1000736318852"></iframe>


### Contributors and acknowledgements

The present materials were created, documented and curated by Pablo Bernabeu, Gabriella Silva, Jorge González Alonso, My Ngoc Giang Hoang, Jason Rothman, Vincent DeLuca, Claudia Poch and Iva Ivanova.

We also received invaluable help and advice in various regards, as we gratefully acknowledge below. Any oversights or errors that remain are entirely our own and should not reflect on the generosity and expertise of those who assisted us.

* My Ngoc Giang Hoang (recruitment of participants and piloting of sessions)

* Mona Kirkness Fossum (translation of materials)

* Gaute Berglund, Anders Gabrielsen, Tekabe Legesse Feleke (piloting of sessions)

* Teodóra Vékony (alternating serial reaction time task)

* Björn Lundquist (implementation in OpenSesame)

* Antonio Fábregas, Natalia Mitrofanova, Yulia Rodina, Marit Westergaard (design and translation of materials and recruitment of participants)

* Merete Anderssen, Fatih Bayram (recruitment of participants)


### Lay summary

Do people learn a third language differently from their second one? For those already fluent in two languages, acquiring a third one introduces specific complexities. We are investigating this process using artificial languages, which allow for precise control and observation of the learning experience.

In this study, we developed 'mini-languages' that replicate grammatical structures of real languages while minimising the need to learn a new vocabulary. The study, conducted in Norway and Spain, follows participants over time, aiming to understand how previous bilingual experience—especially based on structural similarities between languages—influences the learning of a new language.

By using electroencephalography to monitor brain activity, we will examine which prior language(s) serve as sources of transfer in the learning of the new language. This line of inquiry is guided by previous findings in third language acquisition suggesting that learners might rely on both previous languages, though one may be more—or uniquely—influential at the onset of learning.

The study also examines how core cognitive functions---specifically, working memory, inhibitory control and implicit learning---may affect learning outcomes. Similar to how focusing in a noisy environment requires specific mental skills, third language acquisition may depend on particular cognitive abilities. For instance, participants with strong working memory might have an advantage in recognising patterns or recalling grammatical rules.

By better understanding the processes of third language acquisition, this work could also contribute to broader inquiries in cognitive science regarding how we use existing knowledge to adapt to new tasks.


### Related references

<div class = 'related-references'>

<div class = 'hanging-indent'>

Abbas, N., Degani, T., & Prior, A. (2021). Equal Opportunity Interference: Both L1 and L2 Influence L3 Morpho-Syntactic Processing. *Frontiers in Psychology*, *12*, 673535. <https://doi.org/10.3389/fpsyg.2021.673535>

Adelhöfer, N., & Beste, C. (2019). Validity expectancies shape the interplay of cueing and task demands during inhibitory control associated with right inferior frontal regions. *Brain Structure and Function*, *224*(5), 1911--1924. <https://doi.org/10.1007/s00429-019-01884-y>

Adelhöfer, N., Gohil, K., Passow, S., Teufert, B., Roessner, V., Li, S., & Beste, C. (2018). The system‐neurophysiological basis for how methylphenidate modulates perceptual--attentional conflicts during auditory processing. *Human Brain Mapping*, *39*(12), 5050--5061. <https://doi.org/10.1002/hbm.24344>

Adelhöfer, N., Schreiter, M. L., & Beste, C. (2020). Cardiac cycle gated cognitive-emotional control in superior frontal cortices. *NeuroImage*, *222*, 117275. <https://doi.org/10.1016/j.neuroimage.2020.117275>

Ågren, M., Michot, M.-E., Granget, C., Gerolimich, S., Hadermann, P., & Stabarin, I. (2020). "Les copains *dit au revoir": On Subject--Verb Agreement in L2 French and Cross-Linguistic Influence. *Languages*, *6*(1), 7. <https://doi.org/10.3390/languages6010007>

Aguasvivas, J. A., & Carreiras, M. (2022). Bilingualism, Foreign Language Learning, and Cognition: Insights for Education. In M. V. Alves, R. Ekuni, M. J. Hermida, & J. Valle-Lisboa (Eds.), *Cognitive Sciences and Education in Non-WEIRD Populations* (pp. 153--168). Springer International Publishing. <https://doi.org/10.1007/978-3-031-06908-6_10>

Alarcón, I. (2021). Adjectival and verbal agreement in the oral production of early and late bilinguals: Fluency, complexity, and integrated knowledge. *Revista Española de Lingüística Aplicada/Spanish Journal of Applied Linguistics*, *34*(2), 371--401. <https://doi.org/10.1075/resla.19050.ala>

Albirini, A., Saadah, E., & Alhawary, M. T. (2020). L1 and L2 transfer to L3 in L3 and L2 learners of Standard Arabic. *Linguistic Approaches to Bilingualism*, *10*(6), 745--774. <https://doi.org/10.1075/lab.18013.alb>

Alemán Bañón, J., Fiorentino, R., & Gabriele, A. (2018). Using event-related potentials to track morphosyntactic development in second language learners: The processing of number and gender agreement in Spanish. *PLOS ONE*, *13*(7), e0200791. <https://doi.org/10.1371/journal.pone.0200791>

Alemán Bañón, J., Fiorentino, R., & Gabriele, A. (2023). The Neurolinguistics of the Second Language Syntactic System. In K. Morgan-Short & J. G. Van Hell, *The Routledge Handbook of Second Language Acquisition and Neurolinguistics* (1st ed., pp. 133--147). Routledge. <https://doi.org/10.4324/9781003190912-13>

Alemán Bañón, J., & Martin, C. (2021). The role of crosslinguistic differences in second language anticipatory processing: An event-related potentials study. *Neuropsychologia*, *155*, 107797. <https://doi.org/10.1016/j.neuropsychologia.2021.107797>

Alemán Bañón, J., & Rothman, J. (2019). Being a Participant Matters: Event-Related Potentials Show That Markedness Modulates Person Agreement in Spanish. *Frontiers in Psychology*, *10*, 746. <https://doi.org/10.3389/fpsyg.2019.00746>

Al-Ezzi, A., Kamel, N., Faye, I., & Gunaseli, E. (2020). Review of EEG, ERP, and Brain Connectivity Estimators as Predictive Biomarkers of Social Anxiety Disorder. *Frontiers in Psychology*, *11*, 730. <https://doi.org/10.3389/fpsyg.2020.00730>

Alhawary, M. T. (Ed.). (2018). *The Routledge Handbook of Arabic Second Language Acquisition* (1st ed.). Routledge. <https://doi.org/10.4324/9781315674261>

Allgäuer-Hackl, E., & Jessner, U. (2019). 15. Cross-linguistic Interaction and Multilingual Awareness. In S. Montanari & S. Quay (Eds.), *Multidisciplinary Perspectives on Multilingualism* (pp. 325--350). De Gruyter. <https://doi.org/10.1515/9781501507984-015>

Alyan, E., Wascher, E., Arnau, S., Kaesemann, R., & Reiser, J. E. (2023). Operator State in a Workplace Simulation Modulates Eye-Blink Related EEG Activity. *IEEE Transactions on Neural Systems and Rehabilitation Engineering*, *31*, 1167--1179. <https://doi.org/10.1109/TNSRE.2023.3241962>

Amaro, J. C., & Iverson, M. (2018a). Third Language Acquisition. In K. L. Geeslin (Ed.), *The Cambridge Handbook of Spanish Linguistics* (1st ed., pp. 737--757). Cambridge University Press. <https://doi.org/10.1017/9781316779194.034>

Amaro, J. C., & Iverson, M. (2018b). Third Language Acquisition. In K. L. Geeslin (Ed.), *The Cambridge Handbook of Spanish Linguistics* (1st ed., pp. 737--757). Cambridge University Press. <https://doi.org/10.1017/9781316779194.034>

Amora, K. K., Tretow, A., Verwimp, C., Tijms, J., Leppänen, P. H. T., & Csépe, V. (2022). Typical and Atypical Development of Visual Expertise for Print as Indexed by the Visual Word N1 (N170w): A Systematic Review. *Frontiers in Neuroscience*, *16*, 898800. <https://doi.org/10.3389/fnins.2022.898800>

Amoruso, L., García, A. M., Pusil, S., Timofeeva, P., Quiñones, I., & Carreiras, M. (2024). Decoding bilingualism from resting‐state oscillatory network organization. *Annals of the New York Academy of Sciences*, *1534*(1), 106--117. <https://doi.org/10.1111/nyas.15113>

Andersen, S.-O. (2020). Toward Real-life Teaching: Theories and Students' Perceptive Hypothesis Concerning Technology-enhanced Approaches in the L3 German Classroom. In P.-A. Mather (Ed.), *Technology-enhanced Learning and Linguistic Diversity: Strategies and Approaches to Teaching Students in a 2nd or 3rd Language* (pp. 75--90). Emerald Publishing Limited. <https://doi.org/10.1108/978-1-83982-128-820201006>

Anderson, N. E., Maurer, J. M., Steele, V. R., & Kiehl, K. A. (2018). Psychopathic traits associated with abnormal hemodynamic activity in salience and default mode networks during auditory oddball task. *Cognitive, Affective, & Behavioral Neuroscience*, *18*(3), 564--580. <https://doi.org/10.3758/s13415-018-0588-2>

Andersson, A., Sayehli, S., & Gullberg, M. (2019). Language background affects online word order processing in a second language but not offline. *Bilingualism: Language and Cognition*, *22*(04), 802--825. <https://doi.org/10.1017/S1366728918000573>

Andriani, L., D'Alessandro, R., Frasson, A., Van Osch, B., Sorgini, L., & Terenghi, S. (2022). Adding the microdimension to the study of language change in contact. Three case studies. *Glossa: A Journal of General Linguistics*, *7*(1). <https://doi.org/10.16995/glossa.5748>

Angelovska, T. (2022). 4 The Multilingual Language Classroom: Applying Linguistically Diverse Approaches for Handling Prior Languages in Teaching English as a Third Language. In A. Krulatz, G. Neokleous, & A. Dahl (Eds.), *Theoretical and Applied Perspectives on Teaching Foreign Languages in Multilingual Settings* (pp. 67--81). Multilingual Matters. <https://doi.org/10.21832/9781788926423-009>

Angelovska, T., Roehm, D., & Weinmüller, S. (2023). Uncovering transfer effects of dominance and proficiency in L3 English acquisition using the visual moving window paradigm and grammaticality judgments. *Applied Linguistics Review*, *14*(1), 115--143. <https://doi.org/10.1515/applirev-2019-0075>

Antonicelli, G., & Rastelli, S. (2023). Event-related potentials in the study of L2 sentence processing: A scoping review of the decade 2010-2020. *Language Acquisition*, *30*(2), 163--200. <https://doi.org/10.1080/10489223.2022.2141633>

Araujo, F. A., Jacobi, E. B., Avila-Souza, J., Rodrigues, J. F., Moioli, R. C., Araujo, M. F. P., & Peres, A. S. C. (2019). Characterization of Auditory Evoked Potential for Different Tones in Marmoset Primary Auditory Cortex. In R. Costa-Felix, J. C. Machado, & A. V. Alvarenga (Eds.), *XXVI Brazilian Congress on Biomedical Engineering* (Vol. 70/2, pp. 95--101). Springer Singapore. <https://doi.org/10.1007/978-981-13-2517-5_15>

Archibald, J. (2021). Turtles all the way down: Micro-cues and piecemeal transfer in L3 phonology and syntax. *Second Language Research*, *37*(3), 415--421. <https://doi.org/10.1177/0267658320941036>

Archibald, J. (2022). Segmental and Prosodic Evidence for Property-by-Property Transfer in L3 English in Northern Africa. *Languages*, *7*(1), 28. <https://doi.org/10.3390/languages7010028>

Archibald, J. (2023a). Phonological parsing via an integrated I-language: The emergence of property-by-property transfer effects in L3 phonology. *Linguistic Approaches to Bilingualism*, *13*(6), 743--766. <https://doi.org/10.1075/lab.21017.arc>

Archibald, J. (2023b). Using a contrastive hierarchy to formalize structural similarity as I-proximity in L3 phonology. *Linguistic Approaches to Bilingualism*, *13*(5), 614--637. <https://doi.org/10.1075/lab.22051.arc>

Archibald, J. (2024a). Chapter 11. "And yet it moves": Finding a place for phonology in the GenSLA cosmos. In M. Velnić, A. Dahl, & K. F. Listhaug (Eds.), *Language Acquisition and Language Disorders* (Vol. 70, pp. 264--289). John Benjamins Publishing Company. <https://doi.org/10.1075/lald.70.11arc>

Archibald, J. (2024b). *Phonology in Multilingual Grammars: Representational Complexity and Linguistic Interfaces* (1st ed.). Oxford University PressNew York. <https://doi.org/10.1093/oso/9780190923334.001.0001>

Arıbaş, D. Ş., & Cele, F. (2021). Acquisition of articles in L2 and L3 English: The influence of L2 proficiency on positive transfer from L2 to L3. *Journal of Multilingual and Multicultural Development*, *42*(1), 19--36. <https://doi.org/10.1080/01434632.2019.1667364>

Armstrong, A., Bulkes, N., & Tanner, D. (2018). QUANTIFICATIONAL CUES MODULATE THE PROCESSING OF ENGLISH SUBJECT-VERB AGREEMENT BY NATIVE CHINESE SPEAKERS: AN ERP STUDY. *Studies in Second Language Acquisition*, *40*(4), 731--754. <https://doi.org/10.1017/S0272263118000013>

Babaeeghazvini, P., Rueda-Delgado, L. M., Gooijers, J., Swinnen, S. P., & Daffertshofer, A. (2021). Brain Structural and Functional Connectivity: A Review of Combined Works of Diffusion Magnetic Resonance Imaging and Electro-Encephalography. *Frontiers in Human Neuroscience*, *15*, 721206. <https://doi.org/10.3389/fnhum.2021.721206>

Babaie-Janvier, T., & Robinson, P. A. (2020). Neural Field Theory of Evoked Response Potentials With Attentional Gain Dynamics. *Frontiers in Human Neuroscience*, *14*, 293. <https://doi.org/10.3389/fnhum.2020.00293>

Bagherzadeh, Y., Baldauf, D., Pantazis, D., & Desimone, R. (2020). Alpha Synchrony and the Neurofeedback Control of Spatial Attention. *Neuron*, *105*(3), 577-587.e5. <https://doi.org/10.1016/j.neuron.2019.11.001>

Bailey, N. W., Hill, A. T., Biabani, M., Murphy, O. W., Rogasch, N. C., McQueen, B., Miljevic, A., & Fitzgerald, P. B. (2023). RELAX part 2: A fully automated EEG data cleaning algorithm that is applicable to Event-Related-Potentials. *Clinical Neurophysiology*, *149*, 202--222. <https://doi.org/10.1016/j.clinph.2023.01.018>

Bañón, J. A., Miller, D., & Rothman, J. (2021). EXAMINING THE CONTRIBUTION OF MARKEDNESS TO THE L2 PROCESSING OF SPANISH PERSON AGREEMENT: AN EVENT‑RELATED POTENTIALS STUDY. *Studies in Second Language Acquisition*, *43*(4), 699--728. <https://doi.org/10.1017/S0272263120000479>

Baptista, M. (2020). Competition, selection, and the role of congruence in Creole genesis and development. *Language*, *96*(1), 160--199. <https://doi.org/10.1353/lan.2020.0005>

Bar On, S., & Meir, N. (2022). Requests and apologies in two languages among bilingual speakers: A comparison of heritage English speakers and English- and Hebrew-dominant bilinguals. *Frontiers in Psychology*, *13*, 1017715. <https://doi.org/10.3389/fpsyg.2022.1017715>

Barbey, F. M., Farina, F. R., Buick, A. R., Danyeli, L., Dyer, J. F., Islam, Md. N., Krylova, M., Murphy, B., Nolan, H., Rueda-Delgado, L. M., Walter, M., & Whelan, R. (2022). Neuroscience from the comfort of your home: Repeated, self-administered wireless dry EEG measures brain function with high fidelity. *Frontiers in Digital Health*, *4*, 944753. <https://doi.org/10.3389/fdgth.2022.944753>

Bardel, C., & Falk, Y. (2021). L1, L2 and L3: Same or different? *Second Language Research*, *37*(3), 459--464. <https://doi.org/10.1177/0267658320941033>

Bardel, C., Gyllstad, H., & Tholin, J. (2023). Research on foreign language learning, teaching, and assessment in Sweden 2012--2021. *Language Teaching*, *56*(2), 223--260. <https://doi.org/10.1017/S0261444823000022>

Barkov, M., Santiago, F., & Peralta, T. (2022). Production of Vowel Reduction by Mexican Learners of English as L2 and Russian as L3. *Canadian Journal of Linguistics/Revue Canadienne de Linguistique*, *67*(1--2), 88--117. <https://doi.org/10.1017/cnj.2022.6>

Barwasser, A., Calhoon, M. B., Knaak, T., & Grünke, M. (2024). English L2 vocabulary acquisition through storytelling for adolescents with and without learning disabilities. *Language Teaching Research*, 13621688241263492. <https://doi.org/10.1177/13621688241263492>

Bauer, A.-K. R., Bleichner, M. G., Jaeger, M., Thorne, J. D., & Debener, S. (2018a). Dynamic phase alignment of ongoing auditory cortex oscillations. *NeuroImage*, *167*, 396--407. <https://doi.org/10.1016/j.neuroimage.2017.11.037>

Bauer, A.-K. R., Bleichner, M. G., Jaeger, M., Thorne, J. D., & Debener, S. (2018b). Dynamic phase alignment of ongoing auditory cortex oscillations. *NeuroImage*, *167*, 396--407. <https://doi.org/10.1016/j.neuroimage.2017.11.037>

Bayram, F., & Rothman, J. (2020). Formal Linguistics and Language Education: A View from Bilingualism Research. In A. Trotzke & T. Kupisch (Eds.), *Formal Linguistics and Language Education* (Vol. 43, pp. 11--19). Springer International Publishing. <https://doi.org/10.1007/978-3-030-39257-4_2>

Beatty‐Martínez, A. L., Bruni, M. R., Bajo, M. T., & Dussias, P. E. (2021). Brain potentials reveal differential processing of masculine and feminine grammatical gender in native Spanish speakers. *Psychophysiology*, *58*(3), e13737. <https://doi.org/10.1111/psyp.13737>

Benmamoun, E., & Albirini, A. (2018a). IS LEARNING A STANDARD VARIETY SIMILAR TO LEARNING A NEW LANGUAGE?: Evidence from Heritage Speakers of Arabic. *Studies in Second Language Acquisition*, *40*(1), 31--61. <https://doi.org/10.1017/S0272263116000383>

Benmamoun, E., & Albirini, A. (2018b). IS LEARNING A STANDARD VARIETY SIMILAR TO LEARNING A NEW LANGUAGE?: Evidence from Heritage Speakers of Arabic. *Studies in Second Language Acquisition*, *40*(1), 31--61. <https://doi.org/10.1017/S0272263116000383>

Bensmann, W., Roessner, V., Stock, A.-K., & Beste, C. (2018). Catecholaminergic Modulation of Conflict Control Depends on the Source of Conflicts. *International Journal of Neuropsychopharmacology*, *21*(10), 901--909. <https://doi.org/10.1093/ijnp/pyy063>

Bensmann, W., Vahid, A., Beste, C., & Stock, A.-K. (2019). The Intensity of Early Attentional Processing, but Not Conflict Monitoring, Determines the Size of Subliminal Response Conflicts. *Frontiers in Human Neuroscience*, *13*, 53. <https://doi.org/10.3389/fnhum.2019.00053>

Bensmann, W., Zink, N., Arning, L., Beste, C., & Stock, A.-K. (2020). Dopamine D1, but not D2, signaling protects mental representations from distracting bottom-up influences. *NeuroImage*, *204*, 116243. <https://doi.org/10.1016/j.neuroimage.2019.116243>

Berthele, R. (2021). The Extraordinary Ordinary: Re‐engineering Multilingualism as a Natural Category. *Language Learning*, *71*(S1), 80--120. <https://doi.org/10.1111/lang.12407>

Beste, C., Mückschel, M., Rosales, R., Domingo, A., Lee, L., Ng, A., Klein, C., & Münchau, A. (2018). The Basal Ganglia Striosomes Affect the Modulation of Conflicts by Subliminal Information---Evidence from X-Linked Dystonia Parkinsonism. *Cerebral Cortex*, *28*(7), 2243--2252. <https://doi.org/10.1093/cercor/bhx125>

Beste, C., Stock, A.-K., Zink, N., Ocklenburg, S., Akgün, K., & Ziemssen, T. (2019). How minimal variations in neuronal cytoskeletal integrity modulate cognitive control. *NeuroImage*, *185*, 129--139. <https://doi.org/10.1016/j.neuroimage.2018.10.053>

Bi, X. Y., Ma, X., Abulaiti, A., Yang, J., & Tao, Y. (2022). The influence of pride emotion on executive function: Evidence from ERP. *Brain and Behavior*, *12*(8), e2678. <https://doi.org/10.1002/brb3.2678>

Bialystok, E. (2024). Bilingualism modifies cognition through adaptation, not transfer. *Trends in Cognitive Sciences*, *28*(11), 987--997. <https://doi.org/10.1016/j.tics.2024.07.012>

Bian, J., Zhang, H., & Sun, C. (2021). An ERP Study on Attraction Effects in Advanced L2 Learners. *Frontiers in Psychology*, *12*, 616804. <https://doi.org/10.3389/fpsyg.2021.616804>

Bice, K., Yamasaki, B. L., & Prat, C. S. (2020). Bilingual Language Experience Shapes Resting-State Brain Rhythms. *Neurobiology of Language*, *1*(3), 288--318. <https://doi.org/10.1162/nol_a_00014>

Bitner, R. A., & Le, N.-T. (2022). Can EEG-devices differentiate attention values between incorrect and correct solutions for problem-solving tasks? *Journal of Information and Telecommunication*, *6*(2), 121--140. <https://doi.org/10.1080/24751839.2021.1950319>

Bitner, R., Le, N.-T., & Pinkwart, N. (2020). A Concurrent Validity Approach for EEG-Based Feature Classification Algorithms in Learning Analytics. In N. T. Nguyen, B. H. Hoang, C. P. Huynh, D. Hwang, B. Trawiński, & G. Vossen (Eds.), *Computational Collective Intelligence* (Vol. 12496, pp. 568--580). Springer International Publishing. <https://doi.org/10.1007/978-3-030-63007-2_44>

Bodmer, B., Mückschel, M., Roessner, V., & Beste, C. (2017). Neurophysiological variability masks differences in functional neuroanatomical networks and their effectiveness to modulate response inhibition between children and adults. *Brain Structure and Function*. <https://doi.org/10.1007/s00429-017-1589-6>

Boetzel, C., Stecher, H. I., & Herrmann, C. S. (2024). Aligning Event-Related Potentials with Transcranial Alternating Current Stimulation for Modulation---A Review. *Brain Topography*, *37*(6), 933--946. <https://doi.org/10.1007/s10548-024-01055-1>

Boetzel, C., Stecher, H. I., Kasten, F. H., & Herrmann, C. S. (2024). Modulating the difficulty of a visual oddball-like task and P3m amplitude. *Scientific Reports*, *14*(1), 1505. <https://doi.org/10.1038/s41598-023-50857-z>

Bohnacker, U. (2021). On transfer and third language acquisition: A commentary on Schwartz & Sprouse. *Linguistic Approaches to Bilingualism*, *11*(1), 37--44. <https://doi.org/10.1075/lab.20101.boh>

Bojorges-Valdez, E., & Yanez-Suarez, O. (2018). Association between EEG spectral power dynamics and event related potential amplitude on a P300 speller. *Biomedical Physics & Engineering Express*, *4*(2), 025028. <https://doi.org/10.1088/2057-1976/aaa15e>

Bolibaugh, C., & Foster, P. (2021). Implicit Statistical Learning in Naturalistic and Instructed Morphosyntactic Attainment: An Aptitude‐Treatment Interaction Design. *Language Learning*, *71*(4), 959--1003. <https://doi.org/10.1111/lang.12465>

Bordag, D., & Opitz, A. (2022). Employing General Linguistic Knowledge in Incidental Acquisition of Grammatical Properties of New L1 and L2 Lexical Representations: Toward Reducing Fuzziness in the Initial Ontogenetic Stage. *Frontiers in Psychology*, *12*, 768362. <https://doi.org/10.3389/fpsyg.2021.768362>

Borra, D., Magosso, E., Castelo-Branco, M., & Simões, M. (2022). A Bayesian-optimized design for an interpretable convolutional neural network to decode and analyze the P300 response in autism. *Journal of Neural Engineering*, *19*(4), 046010. <https://doi.org/10.1088/1741-2552/ac7908>

Branets, A., & Backus, A. (2020). L2 knowledge facilitating L3 learning: The role of Russian linguistic factors in understanding of Ukrainian by Estonians. *Philologia Estonica Tallinnensis*, *5*. <https://doi.org/10.22601/PET.2020.05.02>

Bringas Vega, M. L., Liu, S., Zhang, M., Pedroso Ibañez, I., Morales Chacon, L. M., Galan Garcia, L., Perez Bocourt, V., Jahanshahi, M., & Valdes-Sosa, P. A. (2020). Flanker Task-Elicited Event-Related Potential Sources Reflect Human Recombinant Erythropoietin Differential Effects on Parkinson's Patients. *Parkinson's Disease*, *2020*, 1--10. <https://doi.org/10.1155/2020/8625794>

Brown-Bousfield, M. M., & Chang, C. B. (2023). Regressive cross-linguistic influence in multilingual speech rhythm: The role of language similarity. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 49--71). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.03bro>

Bruchmann, M., Schindler, S., & Straube, T. (2020). The spatial frequency spectrum of fearful faces modulates early and mid‐latency ERPs but not the N170. *Psychophysiology*, *57*(9), e13597. <https://doi.org/10.1111/psyp.13597>

Busterud, G., Dahl, A., Kush, D., & Listhaug, K. F. (2023). Verb placement in L3 French and L3 German: The role of language-internal factors in determining cross-linguistic influence from prior languages. *Linguistic Approaches to Bilingualism*, *13*(5), 693--716. <https://doi.org/10.1075/lab.22058.bus>

Cabrelli, J., & Iverson, M. (2024). Why do learners overcome non-facilitative transfer faster from an L2 than an L1? The cumulative input threshold hypothesis. *International Journal of Multilingualism*, *21*(3), 1594--1620. <https://doi.org/10.1080/14790718.2023.2200252>

Cabrelli, J., Iverson, M., Giancaspro, D., & Halloran González, B. (2020). The roles of L1 Spanish versus L2 Spanish in L3 Portuguese morphosyntactic development. In K. V. Molsing, C. Becker Lopes Perna, & A. M. Tramunt Ibaños (Eds.), *Issues in Hispanic and Lusophone Linguistics* (Vol. 24, pp. 11--33). John Benjamins Publishing Company. <https://doi.org/10.1075/ihll.24.01cab>

Cabrelli, J., & Pichan, C. (2021). Initial phonological transfer in L3 Brazilian Portuguese and Italian. *Linguistic Approaches to Bilingualism*, *11*(2), 131--167. <https://doi.org/10.1075/lab.18048.cab>

Cabrelli, J., Pichan, C., Ward, J., Rothman, J., & Serratrice, L. (2023). Factors that moderate global similarity in initial L3 transfer: Intervocalic voiced stops in heritage Spanish/English bilinguals' L3 Italian. *Linguistic Approaches to Bilingualism*, *13*(5), 638--662. <https://doi.org/10.1075/lab.22062.cab>

Cabrelli, J., & Puig-Mayenco, E. (2021). Theoretical and methodological considerations for a robust evaluation of the Linguistic Proximity Model. *Second Language Research*, *37*(3), 465--471. <https://doi.org/10.1177/0267658320943661>

Cabuk-Balli, S. (2023). Gauging sensitivity to grammaticality violations of adpositional phrases: Self-paced reading evidence from third language acquisition. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 205--235). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.09cab>

Çabuk-Ballı, S. (2023). Cross-linguistic influence in the acquisition of adpositions in L3. *International Journal of Multilingualism*, *20*(3), 697--716. <https://doi.org/10.1080/14790718.2021.1914061>

Caffarra, S., Dias, P., & Costello, B. (2020). The learnability of gender agreement in Spanish bilinguals. In M. Schlechtweg (Ed.), *The Learnability of Complex Constructions* (pp. 183--218). De Gruyter. <https://doi.org/10.1515/9783110695113-008>

Cai, C., Zhang, L., Quan, Z., Fang, X., Cai, S., & Zhang, J. (2024). Search flavor labels in beverages: An electrophysiological investigation of color-flavor congruency and association strength in visual search. *Neuropsychologia*, *203*, 108985. <https://doi.org/10.1016/j.neuropsychologia.2024.108985>

Cai, W., Wang, L., Chen, T., Zhao, S., Feng, C., & Feng, W. (2020). Auditory attentional biases in young males with physical stature dissatisfaction. *Psychophysiology*, *57*(10), e13635. <https://doi.org/10.1111/psyp.13635>

Cal, Z., & Sypiańska, J. (2020). The interaction of L2 and L3 levels of proficiency in third language acquisition. *Poznan Studies in Contemporary Linguistics*, *56*(4), 577--603. <https://doi.org/10.1515/psicl-2020-0019>

Cal, Z., & Wrembel, M. (2024). Developmental acquisition of stops by multilingual speakers. *International Journal of Multilingualism*, 1--23. <https://doi.org/10.1080/14790718.2024.2363777>

Calafato, R. (2024). Multilingual pedagogies in first versus foreign language contexts: A cross-country study of language teachers. *International Review of Applied Linguistics in Language Teaching*, *62*(2), 249--273. <https://doi.org/10.1515/iral-2022-0019>

Calvo, N., & Bialystok, E. (2021). Electrophysiological signatures of attentional control in bilingual processing: Evidence from proactive interference. *Brain and Language*, *222*, 105027. <https://doi.org/10.1016/j.bandl.2021.105027>

Calvo, N., Grundy, J. G., & Bialystok, E. (2023). Bilingualism modulates neural efficiency at rest through alpha reactivity. *Neuropsychologia*, *180*, 108486. <https://doi.org/10.1016/j.neuropsychologia.2023.108486>

Cantelon, J. A., & Giles, G. E. (2021). A Review of Cognitive Changes During Acute Aerobic Exercise. *Frontiers in Psychology*, *12*, 653158. <https://doi.org/10.3389/fpsyg.2021.653158>

Carvalho, A. (2021). *A close look at how context of acquisition of previous languages influences third language pedagogy: Does one model fit all?* Zenodo. <https://doi.org/10.5281/ZENODO.4449770>

Cayado, D. K. T., & Chan, R. K. W. (2023). The Influence of Prior Linguistic Knowledge on Second Language Semantic Implicit Learning: Evidence from Cantonese--English Bilinguals. *Language Learning*, *73*(3), 657--682. <https://doi.org/10.1111/lang.12546>

Cepeda-Freyre, H. A., Garcia-Aguilar, G., Eguibar, J. R., & Cortes, C. (2020). Brain Processing of Complex Geometric Forms in a Visual Memory Task Increases P2 Amplitude. *Brain Sciences*, *10*(2), 114. <https://doi.org/10.3390/brainsci10020114>

Chami, R., Treasure, J., Cardi, V., Lozano-Madrid, M., Eichin, K. N., McLoughlin, G., & Blechert, J. (2020). Exploring Changes in Event-Related Potentials After a Feasibility Trial of Inhibitory Training for Bulimia Nervosa and Binge Eating Disorder. *Frontiers in Psychology*, *11*, 1056. <https://doi.org/10.3389/fpsyg.2020.01056>

Chan, I. L., & Chang, C. B. (2019). Perception of nonnative tonal contrasts by Mandarin-English and English-Mandarin sequential bilinguals. *The Journal of the Acoustical Society of America*, *146*(2), 956--972. <https://doi.org/10.1121/1.5120522>

Chan, R. K., & Leung, J. H. (2020). WHY ARE LEXICAL TONES DIFFICULT TO LEARN?: INSIGHTS FROM THE INCIDENTAL LEARNING OF TONE-SEGMENT CONNECTIONS. *Studies in Second Language Acquisition*, *42*(1), 33--59. <https://doi.org/10.1017/S0272263119000482>

Chan, R. K. W., & Leung, J. H. C. (2018). Implicit knowledge of lexical stress rules: Evidence from the combined use of subjective and objective awareness measures. *Applied Psycholinguistics*, *39*(1), 37--66. <https://doi.org/10.1017/S0142716417000376>

Chau, L. T., Leijten, M., Bernolet, S., & Vangehuchten, L. (2022). Envisioning multilingualism in source-based writing in L1, L2, and L3: The relation between source use and text quality. *Frontiers in Psychology*, *13*, 914125. <https://doi.org/10.3389/fpsyg.2022.914125>

Chen, H. C., & Tian, J. X. (2024). The roles of Cantonese speakers' L1 and L2 phonological features in L3 pronunciation acquisition. *International Journal of Multilingualism*, *21*(1), 1--17. <https://doi.org/10.1080/14790718.2021.1993231>

Chen, J. (2020). How do L3 words find conceptual parasitic hosts in typologically distant L1 or L2? Evidence from a cross-linguistic priming effect. *International Journal of Bilingual Education and Bilingualism*, *23*(10), 1238--1253. <https://doi.org/10.1080/13670050.2018.1439879>

Chen, J., Kwok, A. P. K., & Li, Y. (2023). Effective utilization of attentional resources in postural control in athletes of skill-oriented sports: An event-related potential study. *Frontiers in Human Neuroscience*, *17*, 1219022. <https://doi.org/10.3389/fnhum.2023.1219022>

Chen, S., Xie, H., Yang, H., Fan, C., Hou, Z., & Zhang, C. (2023). A Classification Framework Based on Multi-modal Features for Detection of Cognitive Impairments. In Z. Yu, X. Hei, D. Li, X. Song, & Z. Lu (Eds.), *Intelligent Robotics* (Vol. 1770, pp. 349--361). Springer Nature Singapore. <https://doi.org/10.1007/978-981-99-0301-6_27>

Chen, Z., Qin, Y., Peng, M., Zhao, W., Shi, X., Lai, D., Yin, E., Yan, Y., Yao, D., & Liu, T. (2023). Event‐related potential patterns of selective attention modulated by perceptual load. *Brain and Behavior*, *13*(3), e2907. <https://doi.org/10.1002/brb3.2907>

Cheng, Y., Rothman, J., & Cunnings, I. (2021). Parsing preferences and individual differences in nonnative sentence processing: Evidence from eye movements. *Applied Psycholinguistics*, *42*(1), 129--151. <https://doi.org/10.1017/S014271642000065X>

Cherici, A. (2023). The role of L1 and L2 in the acquisition of null subjects by Chinese learners of L3 Italian. *International Journal of Multilingualism*, *20*(3), 735--752. <https://doi.org/10.1080/14790718.2021.1977308>

Child, M. W. (2022). Transfer in L3 cognate language acquisition: The role of language background on instructed L3 Portuguese acquisition. *International Review of Applied Linguistics in Language Teaching*, *60*(2), 143--168. <https://doi.org/10.1515/iral-2017-0113>

Chmielewski, W. X., & Beste, C. (2019a). RETRACTED: Neurophysiological mechanisms underlying the modulation of cognitive control by simultaneous conflicts. *Cortex*, *115*, 216--230. <https://doi.org/10.1016/j.cortex.2019.02.006>

Chmielewski, W. X., & Beste, C. (2019b). Stimulus Feature Conflicts Enhance Motor Inhibitory Control Processes in the Lateral Prefrontal Cortex. *Journal of Cognitive Neuroscience*, *31*(9), 1430--1442. <https://doi.org/10.1162/jocn_a_01424>

Chmielewski, W. X., & Beste, C. (2019c). Stimulus-response recoding during inhibitory control is associated with superior frontal and parahippocampal processes. *NeuroImage*, *196*, 227--236. <https://doi.org/10.1016/j.neuroimage.2019.04.035>

Chmielewski, W. X., Tiedt, A., Bluschke, A., Dippel, G., Roessner, V., & Beste, C. (2018). Effects of multisensory stimuli on inhibitory control in adolescent ADHD: It is the content of information that matters. *NeuroImage: Clinical*, *19*, 527--537. <https://doi.org/10.1016/j.nicl.2018.05.019>

Cho, J., Iverson, M., Judy, T., Leal, T., & Shimanskaya, E. (2018). Introduction. In J. Cho, M. Iverson, T. Judy, T. Leal, & E. Shimanskaya (Eds.), *Studies in Bilingualism* (Vol. 55, pp. ix--xv). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.55.cho>

Chuang, Y., Bell, M. J., Banke, I., & Baayen, R. H. (2021). Bilingual and Multilingual Mental Lexicon: A Modeling Study With Linear Discriminative Learning. *Language Learning*, *71*(S1), 219--292. <https://doi.org/10.1111/lang.12435>

Citherlet, D., Boucher, O., Tremblay, J., Robert, M., Gallagher, A., Bouthillier, A., Lepore, F., & Nguyen, D. K. (2020). Spatiotemporal dynamics of auditory information processing in the insular cortex: An intracranial EEG study using an oddball paradigm. *Brain Structure and Function*, *225*(5), 1537--1559. <https://doi.org/10.1007/s00429-020-02072-z>

Clayson, P. E., Mcdonald, J. B., Park, B., Holbrook, A., Baldwin, S. A., Riesel, A., & Larson, M. J. (2023). Registered replication report of the construct validity of the error‐related negativity ( ERN ): A multi‐site study of task‐specific ERN correlations with internalizing and externalizing symptoms. *Psychophysiology*, e14496. <https://doi.org/10.1111/psyp.14496>

Clements, M., & Domínguez, L. (2018). Chapter 7. Testing the predictions of the Scalpel Model in L3/Ln acquisition: The acquisition of null and overt subjects in L3 Chinese. In J. Cho, M. Iverson, T. Judy, T. Leal, & E. Shimanskaya (Eds.), *Studies in Bilingualism* (Vol. 55, pp. 181--201). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.55.07cle>

Čok, T. (2023). *Cognitive Implications for Raising Cross-language Awareness in Foreign Language Acquisition*. Springer International Publishing. <https://doi.org/10.1007/978-3-031-27829-7>

Cui, Y., Engelmann, J. M., Gilbert, D. G., Waters, A. J., Cinciripini, P. M., & Robinson, J. D. (2019). The impact of nicotine dose and instructed dose on smokers' implicit attitudes to smoking cues: An ERP study. *Psychology of Addictive Behaviors*, *33*(8), 710--720. <https://doi.org/10.1037/adb0000523>

Culbertson, J., Franck, J., Braquet, G., Barrera Navarro, M., & Arnon, I. (2020). A learning bias for word order harmony: Evidence from speakers of non-harmonic languages. *Cognition*, *204*, 104392. <https://doi.org/10.1016/j.cognition.2020.104392>

Cuza, A., Jiao, J., & López-Otero, J. C. (2018). Does Typological Proximity Really Matter? Evidence from Mandarin and Brazilian Portuguese-Speaking Learners of Spanish. *Languages*, *3*(2), 13. <https://doi.org/10.3390/languages3020013>

Dahl, A., Listhaug, K. F., & Busterud, G. (2022). The role of L1 Norwegian and L2 English in the acquisition of verb placement in L3 German. In T. Leal, E. Shimanskaya, & C. A. Isabelli (Eds.), *Language Acquisition and Language Disorders* (Vol. 67, pp. 191--212). John Benjamins Publishing Company. <https://doi.org/10.1075/lald.67.08dah>

D'Alessandro, R. (2021). Syntactic Change in Contact: Romance. *Annual Review of Linguistics*, *7*(1), 309--328. <https://doi.org/10.1146/annurev-linguistics-011619-030311>

D'Angelo, F. (2023). *Teaching and Learning Third Languages*. Multilingual Matters. <https://doi.org/10.21832/DANGEL3078>

De Bruin, A., Hoversten, L. J., & Martin, C. D. (2023). Interference between non-native languages during trilingual language production. *Journal of Memory and Language*, *128*, 104386. <https://doi.org/10.1016/j.jml.2022.104386>

Debnath, R., & Wetzel, N. (2022). Processing of task‐irrelevant sounds during typical everyday activities in children. *Developmental Psychobiology*, *64*(7), e22331. <https://doi.org/10.1002/dev.22331>

DeLuca, V., Miller, D., Pliatsikas, C., & Rothman, J. (2019). Brain Adaptations and Neurological Indices of Processing in Adult Second Language Acquisition: Challenges for the Critical Period Hypothesis. In J. W. Schwieter & M. Paradis (Eds.), *The Handbook of the Neuroscience of Multilingualism* (1st ed., pp. 170--196). Wiley. <https://doi.org/10.1002/9781119387725.ch8>

DeLuca, V., Rothman, J., Bialystok, E., & Pliatsikas, C. (2019). Redefining bilingualism as a spectrum of experiences that differentially affects brain structure and function. *Proceedings of the National Academy of Sciences*, *116*(15), 7565--7574. <https://doi.org/10.1073/pnas.1811513116>

DeLuca, V., Rothman, J., Bialystok, E., & Pliatsikas, C. (2020). Duration and extent of bilingual experience modulate neurocognitive outcomes. *NeuroImage*, *204*, 116222. <https://doi.org/10.1016/j.neuroimage.2019.116222>

Demeter, E., Glassberg, B., Gamble, M. L., & Woldorff, M. G. (2022). Reward magnitude enhances early attentional processing of auditory stimuli. *Cognitive, Affective, & Behavioral Neuroscience*, *22*(2), 268--280. <https://doi.org/10.3758/s13415-021-00962-1>

Deng, Y., Choi, I., Shinn-Cunningham, B., & Baumgartner, R. (2019). Impoverished auditory cues limit engagement of brain networks controlling spatial selective attention. *NeuroImage*, *202*, 116151. <https://doi.org/10.1016/j.neuroimage.2019.116151>

Denhovska, N., Serratrice, L., & Payne, J. (2018). Frequency and working memory effects in incidental learning of a complex agreement pattern. *Lingua*, *207*, 49--70. <https://doi.org/10.1016/j.lingua.2018.02.009>

Department of English Language Education, Gyeongin National University of Education, Jo, K., Hong, S., & Kim, K. (2020). Cross-Linguistic Influence in the Use of Be in L3 English by L1-Chinese and L1-Russian Children in Korea. *English Teaching*, *75*(0), 35--53. <https://doi.org/10.15858/engtea.75.s1.202006.35>

Depestele, S., Ross, V., Verstraelen, S., Brijs, K., Brijs, T., Van Dun, K., & Meesen, R. (2020). The impact of cognitive functioning on driving performance of older persons in comparison to younger age groups: A systematic review. *Transportation Research Part F: Traffic Psychology and Behaviour*, *73*, 433--452. <https://doi.org/10.1016/j.trf.2020.07.009>

Depestele, S., Van Dun, K., Verstraelen, S., Ross, V., Van Hoornweder, S., Brijs, K., Brijs, T., Getzmann, S., & Meesen, R. (2023). Age-related changes in midfrontal theta activity during steering control: A driving simulator study. *Neurobiology of Aging*, *123*, 145--153. <https://doi.org/10.1016/j.neurobiolaging.2022.11.014>

Desmarais, M. (2023). Comparing two notions of transfer in third language phonological acquisition: A reanalysis of three studies. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 76--95). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.04des>

Di Pisa, G., Pereira Soares, S. M., & Rothman, J. (2021). Brain, mind and linguistic processing insights into the dynamic nature of bilingualism and its outcome effects. *Journal of Neurolinguistics*, *58*, 100965. <https://doi.org/10.1016/j.jneuroling.2020.100965>

Diaubalick, T., Eibensteiner, L., & Salaberry, M. R. (2023). Influence of L1/L2 linguistic knowledge on the acquisition of L3 Spanish past tense morphology among L1 German speakers. *International Journal of Multilingualism*, *20*(2), 329--346. <https://doi.org/10.1080/14790718.2020.1841204>

Długosz, K. (2021). Transfer effects in gender assignment and gender concord in L3 Swedish: A case study. *Moderna Språk*, *115*(4), 1--26. <https://doi.org/10.58221/mosp.v115i4.6745>

Długosz, K. (2023a). Grammatical gender assignment in L3 versus L4 Swedish: A pseudo-longitudinal study. *International Review of Applied Linguistics in Language Teaching*. <https://doi.org/10.1515/iral-2022-0207>

Długosz, K. (2023b). Processing gender agreement in an additional language: The more languages the better? *Second Language Research*, *39*(4), 997--1026. <https://doi.org/10.1177/02676583221113333>

Długosz, K. (2024a). Cross-linguistic influence in the comprehension of reflexive possessive pronouns in L3 and L4 Swedish. *International Journal of Bilingualism*, *28*(5), 828--844. <https://doi.org/10.1177/13670069231194341>

Długosz, K. (2024b). The accelerating effect of multilingualism on learning a new language grammar: The case of grammatical gender agreement. *XLinguae*, *17*(2), 216--230. <https://doi.org/10.18355/XL.2024.17.02.15>

Dmitrenko, V. (2019). Extending Oxford's (1990) Taxonomy for Multilingual Learners. In E. Vetter & U. Jessner (Eds.), *International Research on Multilingualism: Breaking with the Monolingual Perspective* (Vol. 35, pp. 187--214). Springer International Publishing. <https://doi.org/10.1007/978-3-030-21380-0_11>

Durand-López, E. M. (2024a). Working memory and L2 gender agreement processing in structural distance conditions. *Journal of Cultural Cognitive Science*, *8*(2), 121--137. <https://doi.org/10.1007/s41809-024-00143-9>

Durand-López, E. M. (2024b). Working memory training yields improvements in L2 morphosyntactic processing. *Language, Cognition and Neuroscience*, *39*(6), 757--772. <https://doi.org/10.1080/23273798.2024.2359560>

Dyson, B. J., Steward, B. A., Meneghetti, T., & Forder, L. (2020). Behavioural and neural limits in competitive decision making: The roles of outcome, opponency and observation. *Biological Psychology*, *149*, 107778. <https://doi.org/10.1016/j.biopsycho.2019.107778>

Dziubalska-Kolaczyk, K., & Wrembel, M. (2024). Chapter 16. A revised Natural Growth Theory of Acquisition: Evidence from L3 phonology. In E. Babatsouli (Ed.), *Studies in Bilingualism* (Vol. 67, pp. 426--449). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.67.16dzi>

Ecke, P. (2022). Chapter 6. Grammatical gender and article use in beginning learners of German. In D. Ayoun (Ed.), *Studies in Bilingualism* (Vol. 63, pp. 127--156). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.63.06eck>

Ecke, P., & Hall, C. J. (2021). The Parasitic Model: Lexical acquisition and its impact on morphosyntactic transfer. *Linguistic Approaches to Bilingualism*, *11*(1), 45--49. <https://doi.org/10.1075/lab.20088.eck>

Efeoglu, G., & Schroeder, C. (2021). Acquisition of Object Pronouns in EFL in Germany by Heritage Speakers of Turkish. *Sustainable Multilingualism*, *18*(1), 71--84. <https://doi.org/10.2478/sm-2021-0004>

Efeoglu, G., Yüksel, H. G., & Baran, S. (2020). Lexical cross-linguistic influence: A study of three multilingual learners of L3 English. *International Journal of Multilingualism*, *17*(4), 535--551. <https://doi.org/10.1080/14790718.2019.1620239>

Egurtzegi, A., Blasi, D. E., Bornkessel-Schlesewsky, I., Laka, I., Meyer, M., Bickel, B., & Sauppe, S. (2022). Cross-linguistic differences in case marking shape neural power dynamics and gaze behavior during sentence planning. *Brain and Language*, *230*, 105127. <https://doi.org/10.1016/j.bandl.2022.105127>

Ehlers, C. L., Phillips, E., Kim, C., Wills, D. N., Karriker-Jaffe, K. J., & Gilder, D. A. (2019). CR-19-0950: Event-related responses to alcohol-related stimuli in Mexican-American young adults: Relation to age, gender, comorbidity and "dark side" symptoms. *Drug and Alcohol Dependence*, *202*, 76--86. <https://doi.org/10.1016/j.drugalcdep.2019.06.001>

Eibensteiner, L. (2023). L3 acquisition of aspect: The influence of structural similarity, analytic L2 and general L3 proficiency. *International Review of Applied Linguistics in Language Teaching*, *61*(4), 1827--1858. <https://doi.org/10.1515/iral-2021-0220>

Eibensteiner, L. (2024). Complex transfer processes in multilingual language (L3/L~n~ ) acquisition of Spanish past tenses: The role of non-native language (L2) transfer. *International Journal of Multilingualism*, *21*(3), 1313--1331. <https://doi.org/10.1080/14790718.2022.2164768>

Elham Al-Makatrah. (2019). Markedness variability: The case of do-support. *Lingue e linguaggio*, *2*, 267--290. <https://doi.org/10.1418/95393>

Elvin, J. (2024). Phonological acquisition of Portuguese as a second and a third language. In A. Zampaulo, *The Routledge Handbook of Portuguese Phonology* (1st ed., pp. 350--364). Routledge. <https://doi.org/10.4324/9781003266648-21>

El-Zghir, R. K., Gabay, N. C., & Robinson, P. A. (2021). Modal-Polar Representation of Evoked Response Potentials in Multiple Arousal States. *Frontiers in Human Neuroscience*, *15*, 642479. <https://doi.org/10.3389/fnhum.2021.642479>

Engemann, H., & Radetzky, S. (2024). Cognate Facilitation in Child Third Language Learners in a Multilingual Setting. *Languages*, *9*(10), 310. <https://doi.org/10.3390/languages9100310>

Englert, C., Venagli, I., & Kupisch, T. (2024). When multilingualism is more than three: On the nature of gender transfer in L3+ acquisition. *Second Language Research*, 02676583241237763. <https://doi.org/10.1177/02676583241237763>

Enriquez-Geppert, S. (2019). Neurofeedback aus der Perspektive der Neurowissenschaften: Aktuelle Entwicklungen und Trends. *Psychotherapeut*, *64*(3), 186--193. <https://doi.org/10.1007/s00278-019-0351-3>

Erdocia, K., & Laka, I. (2018). Negative Transfer Effects on L2 Word Order Processing. *Frontiers in Psychology*, *9*, 337. <https://doi.org/10.3389/fpsyg.2018.00337>

Espi-Sanchis, G., & Cockcroft, K. (2022). Working memory and multilingualism: Balanced language proficiency predicts verbal working memory. *International Journal of Bilingual Education and Bilingualism*, *25*(8), 2976--2990. <https://doi.org/10.1080/13670050.2021.1997901>

Estaji, M. & Associate Professor of Applied Linguistics, Department of English Language and Literature, Faculty of Persian Literature and Foreign Languages, Allameh Tabataba'i University, Tehran, Iran. (2022). The Implementation of Self-Monitoring in Writing: Analyzing the Form and Content of EFL Learners' Annotations. *Language Related Research*, *13*(5), 197--222. <https://doi.org/10.52547/LRR.13.5.8>

Faerman, M. V., Ehgoetz Martens, K. A., Meehan, S. K., & Staines, W. R. (2024). Neural correlates of trait anxiety in sensory processing and distractor filtering. *Psychophysiology*, e14706. <https://doi.org/10.1111/psyp.14706>

Falk, Y., & Bardel, C. (2021). Transfer patterns in L3 learning discussed. *Linguistic Approaches to Bilingualism*, *11*(1), 50--53. <https://doi.org/10.1075/lab.20082.fal>

Falk, Y., & Bardel, C. (2024). The L2/L3 initial state, initial stages and judgement tasks: The role of intercomprehension when judging unknown languages. *Second Language Research*, 02676583231220785. <https://doi.org/10.1177/02676583231220785>

Fallah, N., & Jabbari, A. A. (2018). L3 acquisition of English attributive adjectives: Dominant language of communication matters for syntactic cross-linguistic influence. *Linguistic Approaches to Bilingualism*, *8*(2), 193--216. <https://doi.org/10.1075/lab.16003.fal>

Faustino Lacerda De Souza, R., Borges De Araujo Lima, L. A., Almeida Silveira Mendes, T. M., Soares Brandão, D., Andrés Laplagne, D., & Cordeiro De Sousa, M. B. (2022). Implicit motor imagery performance and cortical activity throughout the menstrual cycle. *Scientific Reports*, *12*(1), 21385. <https://doi.org/10.1038/s41598-022-25766-2>

Fernández Fuertes, R., & Sánchez Calderón, S. (2021). The syntactic status of English dative alternation structures in bilingual and in monolingual acquisition data. *Linguistic Approaches to Bilingualism*, *11*(6), 817--845. <https://doi.org/10.1075/lab.18093.fer>

Fernández-Berkes, É., & Flynn, S. (2020). Where DLC Meets Multilingual Syntactic Development. In J. Lo Bianco & L. Aronin (Eds.), *Dominant Language Constellations* (Vol. 47, pp. 57--74). Springer International Publishing. <https://doi.org/10.1007/978-3-030-52336-7_4>

Festman, J. (2021). Learning and Processing Multiple Languages: The More the Easier? *Language Learning*, *71*(S1), 121--162. <https://doi.org/10.1111/lang.12437>

Fingelkurts, A. A., Fingelkurts, A. A., & Neves, C. F. H. (2020). Neuro-assessment of leadership training. *Coaching: An International Journal of Theory, Research and Practice*, *13*(2), 107--145. <https://doi.org/10.1080/17521882.2019.1619796>

Fischer-Jbali, L. R., Montoro, C. I., Montoya, P., Halder, W., & Duschek, S. (2021). Central nervous activity during implicit processing of emotional face expressions in fibromyalgia syndrome. *Brain Research*, *1758*, 147333. <https://doi.org/10.1016/j.brainres.2021.147333>

Flores-Salgado, E., & Gutiérrez-Koyoc, A. F. (2024). Working Memory and Cross-Linguistic Influence on Vocabulary Acquisition. *Brain Sciences*, *14*(8), 796. <https://doi.org/10.3390/brainsci14080796>

Folyi, T., & Wentura, D. (2019). Involuntary sensory enhancement of gain- and loss-associated tones: A general relevance principle. *International Journal of Psychophysiology*, *138*, 11--26. <https://doi.org/10.1016/j.ijpsycho.2019.01.007>

Forcelini, J., & Sunderman, G. (2020). When More is Less: The Effect of a Third Language on a Second Language. *Hispania*, *103*(4), 489--500. <https://doi.org/10.1353/hpn.2020.0110>

Foryś-Nogala, M., Broniś, O., Opacki, M., & Otwinowska, A. (2023). Cross-linguistic influences, language proficiency and metalinguistic knowledge in L3 Italian subject placement. *International Journal of Multilingualism*, *20*(2), 308--328. <https://doi.org/10.1080/14790718.2020.1811710>

Franck, J., & Papadopoulou, D. (2022). L2 French learning by Eritrean refugee speakers of Tigrinya. *Bilingualism: Language and Cognition*, *25*(4), 631--644. <https://doi.org/10.1017/S1366728921001048>

Frankowsky, M., Ke, D., Zwitserlood, P., Michel, R., & Bölte, J. (2022). The interplay between classifier choice and animacy in Mandarin-Chinese noun phrases: An ERP study. *Language, Cognition and Neuroscience*, *37*(7), 866--882. <https://doi.org/10.1080/23273798.2022.2026420>

Franz, M., Schmidt, B., Hecht, H., Naumann, E., & Miltner, W. H. R. (2020). Suggested deafness during hypnosis and simulation of hypnosis compared to a distraction and control condition: A study on subjective experience and cortical brain responses. *PLOS ONE*, *15*(10), e0240832. <https://doi.org/10.1371/journal.pone.0240832>

Freichel, R., Zink, N., Chang, F. Y., Vera, J. D., Truong, H., Michelini, G., Loo, S. K., & Lenartowicz, A. (2024). Alpha event-related decreases during encoding in adults with ADHD -- An investigation of sustained attention and working memory processes. *Behavioural Brain Research*, *469*, 115003. <https://doi.org/10.1016/j.bbr.2024.115003>

Freunberger, D., Bylund, E., & Abrahamsson, N. (2022). Is It Time to Reconsider the 'Gold Standard' for Nativelikeness in ERP Studies on Grammatical Processing in a Second Language? A Critical Assessment Based on Qualitative Individual Differences. *Applied Linguistics*, *43*(3), 433--452. <https://doi.org/10.1093/applin/amab058>

Friedrich, J., Mückschel, M., & Beste, C. (2019). Physical intensity of stimuli modulates motor inhibition by affecting response selection processes in right inferior frontal regions. *Behavioural Brain Research*, *359*, 597--608. <https://doi.org/10.1016/j.bbr.2018.10.006>

Frolov, N., Pitsik, E., Maksimenko, V., & Hramov, A. (2023). Applying recurrence time entropy to identify changes in event-related potentials. *The European Physical Journal Special Topics*, *232*(1), 161--168. <https://doi.org/10.1140/epjs/s11734-022-00743-y>

Fukuta, J., & Yamashita, J. (2023). The complex relationship between conscious/unconscious learning and conscious/unconscious knowledge: The mediating effects of salience in form--meaning connections. *Second Language Research*, *39*(2), 425--446. <https://doi.org/10.1177/02676583211044950>

Fuster, C., & Neuser, H. (2020). Exploring intentionality in lexical transfer. *International Journal of Multilingualism*, *17*(4), 516--534. <https://doi.org/10.1080/14790718.2018.1559845>

Gabriel, C., & Grünke, J. (2018). Chapter 12. Focus, prosody, and subject positions in L3 Spanish: Analyzing data from German learners with Italian and European Portuguese as heritage languages. In M. García García & M. Uth (Eds.), *Studies in Language Companion Series* (Vol. 201, pp. 357--386). John Benjamins Publishing Company. <https://doi.org/10.1075/slcs.201.12gab>

Gabriele, A. (2021). Microvariation and transfer in L2 and L3 acquisition. *Second Language Research*, *37*(3), 453--458. <https://doi.org/10.1177/0267658320941063>

Gabriele, A., Alemán Bañón, J., Hoffman, L., Covey, L., Rossomondo, A., & Fiorentino, R. (2021). Examining variability in the processing of agreement in novice learners: Evidence from event-related potentials. *Journal of Experimental Psychology: Learning, Memory, and Cognition*, *47*(7), 1106--1140. <https://doi.org/10.1037/xlm0000983>

Gallardo, M., & Montrul, S. (2023). Property-by-property transfer in L3 Italian. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 236--271). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.10gal>

Gallo, F., & Abutalebi, J. (2024). The unique role of bilingualism among cognitive reserve-enhancing factors. *Bilingualism: Language and Cognition*, *27*(2), 287--294. <https://doi.org/10.1017/S1366728923000317>

Gantiva, C., Sotaquirá, M., Araujo, A., & Cuervo, P. (2020). Cortical processing of human and emoji faces: An ERP analysis. *Behaviour & Information Technology*, *39*(8), 935--943. <https://doi.org/10.1080/0144929X.2019.1632933>

García, V. B., & Martínez Martínez, S. (2024). "I Have Confidence in Screens." In C. Plaza-Lara, M. D. M. Ogea-Pozo, & C. Botella-Tejera, *Empirical Studies in Didactic Audiovisual Translation* (1st ed., pp. 129--151). Routledge. <https://doi.org/10.4324/9781003462194-11>

Geiss, M., Gumbsheimer, S., Lloyd-Smith, A., Schmid, S., & Kupisch, T. (2022). VOICE ONSET TIME IN MULTILINGUAL SPEAKERS: ITALIAN HERITAGE SPEAKERS IN GERMANY WITH L3 ENGLISH. *Studies in Second Language Acquisition*, *44*(2), 435--459. <https://doi.org/10.1017/S0272263121000280>

Geng, S., Quiñones, I., Gil-Robles, S., Pomposo Gastelu, I. C., Bermudez, G., Timofeeva, P., Molinaro, N., Carreiras, M., & Amoruso, L. (2023). "Neural dynamics supporting longitudinal plasticity of action naming across languages: MEG evidence from bilingual brain tumor patients." *Neuropsychologia*, *181*, 108494. <https://doi.org/10.1016/j.neuropsychologia.2023.108494>

Getzmann, S., Arnau, S., Karthaus, M., Reiser, J. E., & Wascher, E. (2018). Age-Related Differences in Pro-active Driving Behavior Revealed by EEG Measures. *Frontiers in Human Neuroscience*, *12*, 321. <https://doi.org/10.3389/fnhum.2018.00321>

Getzmann, S., Reiser, J. E., Karthaus, M., Rudinger, G., & Wascher, E. (2021). Measuring Correlates of Mental Workload During Simulated Driving Using cEEGrid Electrodes: A Test--Retest Reliability Analysis. *Frontiers in Neuroergonomics*, *2*, 729197. <https://doi.org/10.3389/fnrgo.2021.729197>

Gholamipourbarogh, N., Eggert, E., Münchau, A., Frings, C., & Beste, C. (2024). EEG tensor decomposition delineates neurophysiological principles underlying conflict-modulated action restraint and action cancellation. *NeuroImage*, *295*, 120667. <https://doi.org/10.1016/j.neuroimage.2024.120667>

Gil, L. A., & Müller, N. (2018). French Postverbal Subjects: A Comparison of Monolingual, Bilingual, Trilingual, and Multilingual French. *Languages*, *3*(3), 29. <https://doi.org/10.3390/languages3030029>

Ging-Jehli, N. R., Ratcliff, R., & Arnold, L. E. (2021). Improving neurocognitive testing using computational psychiatry---A systematic review for ADHD. *Psychological Bulletin*, *147*(2), 169--231. <https://doi.org/10.1037/bul0000319>

González Alonso, J., Alemán Bañón, J., DeLuca, V., Miller, D., Pereira Soares, S. M., Puig-Mayenco, E., Slaats, S., & Rothman, J. (2020). Event related potentials at initial exposure in third language acquisition: Implications from an artificial mini-grammar study. *Journal of Neurolinguistics*, *56*, 100939. <https://doi.org/10.1016/j.jneuroling.2020.100939>

González Alonso, J., & Duñabeitia, J. A. (2023). Family Attitudes towards Multilingualism in Bilingual Education Programs and Their Relationship with Academic Performance. *Behavioral Sciences*, *14*(1), 6. <https://doi.org/10.3390/bs14010006>

González Alonso, J., & Puig-Mayenco, E. (2021). You know more than you say: Methodological choices in L3 transfer research. *Linguistic Approaches to Bilingualism*, *11*(1), 54--59. <https://doi.org/10.1075/lab.20089.gon>

González Alonso, J., Puig-Mayenco, E., Fábregas, A., Chaouch-Orozco, A., & Rothman, J. (2021). On the status of transfer in adult third language acquisition of early bilinguals. *PLOS ONE*, *16*(3), e0247976. <https://doi.org/10.1371/journal.pone.0247976>

González Alonso, J., & Rothman, J. (2021). Avoiding the *cum hoc ergo propter hoc* fallacy: Comments and questions regarding Full Transfer Potential. *Second Language Research*, *37*(3), 423--428. <https://doi.org/10.1177/0267658320934135>

Gonzalez Fernandez, J. (2020). *Methodology for the Natural Acquisition of Second Languages*. Peter Lang D. <https://doi.org/10.3726/b16650>

Grey, S. (2020). What can artificial languages reveal about morphosyntactic processing in bilinguals? *Bilingualism: Language and Cognition*, *23*(1), 81--86. <https://doi.org/10.1017/S1366728919000567>

Grey, S. (2024). The Declarative / Procedural Model and Input Processing. In W. Wong & J. Barcroft, *The Routledge Handbook of Second Language Acquisition and Input Processing* (1st ed., pp. 134--149). Routledge. <https://doi.org/10.4324/9781003041412-13>

Grey, S., & Jackson, C. (2020). The Effects of Learners' Perceptions and Affective Factors on L2 Learning Outcomes. *The Canadian Modern Language Review*, *76*(1), 2--30. <https://doi.org/10.3138/cmlr.2018-0209>

Grey, S., Sanz, C., Morgan-Short, K., & Ullman, M. T. (2018). Bilingual and monolingual adults learning an additional language: ERPs reveal differences in syntactic processing. *Bilingualism: Language and Cognition*, *21*(5), 970--994. <https://doi.org/10.1017/S1366728917000426>

Grey, S., & Tagarelli, K. M. (2018). Psycholinguistic Methods. In A. Phakiti, P. De Costa, L. Plonsky, & S. Starfield (Eds.), *The Palgrave Handbook of Applied Linguistics Research Methodology* (pp. 287--312). Palgrave Macmillan UK. <https://doi.org/10.1057/978-1-137-59900-1_14>

Grossberg, S. (2021). A Neural Model of Intrinsic and Extrinsic Hippocampal Theta Rhythms: Anatomy, Neurophysiology, and Function. *Frontiers in Systems Neuroscience*, *15*, 665052. <https://doi.org/10.3389/fnsys.2021.665052>

Grundy, J. G., & Chung-Fat-Yim, A. (2023). Chapter 12. Domain-general electrophysiological changes associated with bilingualism. In G. Luk, J. A. E. Anderson, & J. G. Grundy (Eds.), *Studies in Bilingualism* (Vol. 64, pp. 245--271). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.64.12gru>

Gu, J. (2024). Digital Tools in Language Learning: Optimizing Memory and Attention for College Students. *International Journal of Human--Computer Interaction*, 1--11. <https://doi.org/10.1080/10447318.2024.2400384>

Gu, Q., & Adil, M. (2022). The L3 acquisition of English tense-aspect system by Uygur speakers with L2 Mandarin Chinese. *Forum for Linguistic Studies*, *4*(1), 116. <https://doi.org/10.18063/fls.v4i1.1459>

Gu, R. (2019). ERP Experimental Design. In L. Hu & Z. Zhang (Eds.), *EEG Signal Processing and Feature Extraction* (pp. 43--69). Springer Singapore. <https://doi.org/10.1007/978-981-13-9113-2_4>

Güntekin, B., Aktürk, T., Arakaki, X., Bonanni, L., Del Percio, C., Edelmayer, R., Farina, F., Ferri, R., Hanoğlu, L., Kumar, S., Lizio, R., Lopez, S., Murphy, B., Noce, G., Randall, F., Sack, A. T., Stocchi, F., Yener, G., Yıldırım, E., & Babiloni, C. (2022). Are there consistent abnormalities in event‐related EEG oscillations in patients with Alzheimer's disease compared to other diseases belonging to dementia? *Psychophysiology*, *59*(5), e13934. <https://doi.org/10.1111/psyp.13934>

Guo, W., & Jia, Z. (2019). Early attentive processing on forged and genuine exemplars by imitators: An ERP study. *Forensic Science International*, *297*, 335--341. <https://doi.org/10.1016/j.forsciint.2019.02.023>

Guo, Y., & Yuan, B. (2020). Facilitative transfer only?: L3 acquisition of Mandarin sentence-final particle clusters by English-Cantonese bilinguals. *Journal of Second Language Studies*, *3*(2), 261--289. <https://doi.org/10.1075/jsls.00013.guo>

Guo, Y., & Yuan, B. (2023). Asymmetric transfer and development of temporal-aspectual sentence-final particles in English-Cantonese bilinguals' L3 Mandarin grammars. *Linguistic Approaches to Bilingualism*, *13*(4), 576--606. <https://doi.org/10.1075/lab.20116.guo>

Guo, Y., & Yuan, B. (2024a). Disentangling cues of different domains in transfer and development in L3 acquisition: An investigation of L2/L3 Mandarin *yes-no* questions. *Bilingualism: Language and Cognition*, 1--13. <https://doi.org/10.1017/S1366728923000913>

Guo, Y., & Yuan, B. (2024b). How does a structurally similar background language influence L3 grammars? A study on the syntax of L2/L3 Mandarin [SI 21/3]. *International Journal of Multilingualism*, 1--17. <https://doi.org/10.1080/14790718.2024.2367590>

Guzmán Pitarch, J. R. (2021). The effect of L4 on translation students' L1/L2 writing scripts. *Language Value*, *14*(1), 1--32. <https://doi.org/10.6035/languagev.5804>

Hamrick, P., & Sachs, R. (2018). ESTABLISHING EVIDENCE OF LEARNING IN EXPERIMENTS EMPLOYING ARTIFICIAL LINGUISTIC SYSTEMS. *Studies in Second Language Acquisition*, *40*(1), 153--169. <https://doi.org/10.1017/S0272263116000474>

Han, Q., Tian, J. X., & Chen, H. C. (2023). L3 prosody: Cross-linguistic influence of prosodic features in Mandarin and English by Cantonese multilinguals. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 96--120). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.05han>

Haznedar, B. (2023). Teaching and Assessment in Young Learners' Classrooms: In D. Köksal, N. Kavaklı Ulutaş, & S. Arslan (Eds.), *Advances in Educational Technologies and Instructional Design* (pp. 136--155). IGI Global. <https://doi.org/10.4018/978-1-6684-5660-6.ch008>

Helms-Park, R., Petrescu, M. C., Pirvulescu, M., & Dronjic, V. (2022). Canadian-born trilingual children's narrative skills in their heritage language and Canada's official languages. *International Journal of Multilingualism*, 1--25. <https://doi.org/10.1080/14790718.2022.2059078>

Henriksen, N. (2021). 14 Second and third language acquisition of Romance phonology. In C. Gabriel, R. Gess, & T. Meisenburg (Eds.), *Manual of Romance Phonetics and Phonology* (pp. 435--461). De Gruyter. <https://doi.org/10.1515/9783110550283-015>

Hermas, A. (2020). Genericity in third language English: Acquisition pattern and transfer in ultimate attainment. *International Journal of Bilingualism*, *24*(2), 266--288. <https://doi.org/10.1177/1367006919826865>

Hermas, A. (2023). Genericity in L2 French and L3 English: A pragmatic deficit with a semantic consequence. *International Journal of Multilingualism*, *20*(2), 425--451. <https://doi.org/10.1080/14790718.2020.1820510>

Hetkamp, M., Bender, J., Rheindorf, N., Kowalski, A., Lindner, M., Knispel, S., Beckmann, M., Tagay, S., & Teufel, M. (2019). A Systematic Review of the Effect of Neurofeedback in Cancer Patients. *Integrative Cancer Therapies*, *18*, 1534735419832361. <https://doi.org/10.1177/1534735419832361>

Holmes, B. C., & Putnam, M. T. (2020). Mental representations in receptive multilingual grammars. *Linguistic Approaches to Bilingualism*, *10*(3), 309--314. <https://doi.org/10.1075/lab.00029.int>

Hong, X., Sun, J., Wang, J., Li, C., & Tong, S. (2020). Attention-related modulation of frontal midline theta oscillations in cingulate cortex during a spatial cueing Go/NoGo task. *International Journal of Psychophysiology*, *148*, 1--12. <https://doi.org/10.1016/j.ijpsycho.2019.11.011>

Hopp, H. (2019). Cross-linguistic influence in the child third language acquisition of grammar: Sentence comprehension and production among Turkish-German and German learners of English. *International Journal of Bilingualism*, *23*(2), 567--583. <https://doi.org/10.1177/1367006917752523>

Hopp, H., Jakisch, J., Sturm, S., Becker, C., & Thoma, D. (2020). Integrating multilingualism into the early foreign language classroom: Empirical and teaching perspectives. *International Multilingual Research Journal*, *14*(2), 146--162. <https://doi.org/10.1080/19313152.2019.1669519>

Hopp, H., & Lemmerth, N. (2018a). LEXICAL AND SYNTACTIC CONGRUENCY IN L2 PREDICTIVE GENDER PROCESSING. *Studies in Second Language Acquisition*, *40*(1), 171--199. <https://doi.org/10.1017/S0272263116000437>

Hopp, H., & Lemmerth, N. (2018b). LEXICAL AND SYNTACTIC CONGRUENCY IN L2 PREDICTIVE GENDER PROCESSING. *Studies in Second Language Acquisition*, *40*(1), 171--199. <https://doi.org/10.1017/S0272263116000437>

Hopp, H., Thoma, D., Kieseier, T., Jakisch, J., & Sturm, S. (2022). Early plurilingual foreign language teaching in mixed classrooms: Linguistic and metalinguistic predictors of foreign language development among majority-language and minority-language students in EFL classes. *System*, *108*, 102828. <https://doi.org/10.1016/j.system.2022.102828>

Hu, L., Xue, C., & Shao, J. (2020). ERP Research on Semantic Matching of Audio-visual Information in Interfaces in Quiet-Noise Situations. *2020 Information Communication Technologies Conference (ICTC)*, 323--327. <https://doi.org/10.1109/ICTC49638.2020.9123266>

Hu, R., Zhang, L., Meng, P., Meng, X., & Weng, M. (2022). The Neural Responses of Visual Complexity in the Oddball Paradigm: An ERP Study. *Brain Sciences*, *12*(4), 447. <https://doi.org/10.3390/brainsci12040447>

Huang, T., Loerts, H., & Steinkrauss, R. (2022). The impact of second- and third-language learning on language aptitude and working memory. *International Journal of Bilingual Education and Bilingualism*, *25*(2), 522--538. <https://doi.org/10.1080/13670050.2019.1703894>

Huang, T., Steinkrauss, R., & Verspoor, M. (2021). Variability as predictor in L2 writing proficiency. *Journal of Second Language Writing*, *52*, 100787. <https://doi.org/10.1016/j.jslw.2020.100787>

Huang, T., Steinkrauss, R., & Verspoor, M. (2022). Learning an L2 and L3 at the same time: Help or hinder? *International Journal of Multilingualism*, *19*(4), 566--582. <https://doi.org/10.1080/14790718.2020.1779726>

Huang, Y., Li, D., Ma, J., Ji, X., & Zhou, C. (2024). Bilinguals outperform trilinguals in implicit language aptitude: The mediating role of selective attention. *Journal of Multilingual and Multicultural Development*, 1--17. <https://doi.org/10.1080/01434632.2024.2392884>

Huang, Y., Wang, M., & Rao, H. (2024). Working memory as a partial mediator of the relationship between multilingualism and foreign language aptitude. *International Journal of Multilingualism*, *21*(1), 18--35. <https://doi.org/10.1080/14790718.2021.1993860>

Hudson, M. R., & Jones, N. C. (2022). Deciphering the code: Identifying true gamma neural oscillations. *Experimental Neurology*, *357*, 114205. <https://doi.org/10.1016/j.expneurol.2022.114205>

Hughes, C. J. L., Costley, J., & Lange, C. (2021). The Relationship between Attention and Extraneous Load. *Theory and Practice of Second Language Acquisition*, *7*(2), 61--82. <https://doi.org/10.31261/TAPSLA.9986>

Huo, S., Li, J., Guo, J., Yan, H., Deng, X., Liu, Y., & Zhao, J. (2023). Young Adults with Negative Body Image at Fatness Subscale Are More Restrained Than Normal Adults during a Chocolate Discounting Task. *International Journal of Environmental Research and Public Health*, *20*(12), 6122. <https://doi.org/10.3390/ijerph20126122>

Imaz Agirre, A., & García Mayo, M. D. P. (2018). Chapter 8. Proficiency and transfer effects in the acquisition of gender agreement by L2 and L3 English learners. In J. Cho, M. Iverson, T. Judy, T. Leal, & E. Shimanskaya (Eds.), *Studies in Bilingualism* (Vol. 55, pp. 203--227). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.55.08ima>

Irsara, M. (2020). Applying typological insights in a minority-language context: Motion event lexicalisations in Ladin, Italian, German and English texts compiled by Ladins. *Glottodidactica. An International Journal of Applied Linguistics*, *47*(1), 23--40. <https://doi.org/10.14746/gl.2020.47.1.02>

Isasi-Isasmendi, A., Sauppe, S., Andrews, C., Laka, I., Meyer, M., & Bickel, B. (2024). Incremental sentence processing is guided by a preference for agents: EEG evidence from Basque. *Language, Cognition and Neuroscience*, *39*(1), 76--97. <https://doi.org/10.1080/23273798.2023.2250023>

Ishikawa, K. (2019). Incidental and explicit learning of L2 derivational morphology and the nature of acquired knowledge. *Applied Psycholinguistics*, *40*(6), 1377--1404. <https://doi.org/10.1017/S0142716419000304>

Jabbari, A. A., Achard-Bayle, G., & Ablali, D. (2018). Acquisition of L3 French wh-question structure by Persian-English bilinguals. *Cogent Education*, *5*(1), 1524551. <https://doi.org/10.1080/2331186X.2018.1524551>

Jackson, D. O. (2019). The Potential Relationship Between Openness and Explicit Versus Implicit L2 Knowledge. *Journal of Psycholinguistic Research*, *48*(2), 289--306. <https://doi.org/10.1007/s10936-018-9603-6>

Jacobs, M., Dykens, E. M., & Key, A. P. (2018). Attentional rather than sensory differences characterize auditory processing in Williams syndrome. *Brain and Cognition*, *121*, 24--37. <https://doi.org/10.1016/j.bandc.2018.01.005>

Jacopo Saturno. (2023). *Transfer (or lack thereof) and the accusative case in L2 Polish*. Language Science Press. <https://doi.org/10.5281/ZENODO.10280612>

Jaekel, N., Schurig, M., & Lorenz, E. (2024). Moving beyond binary language status in research: Investigating early foreign language learning and linguistic distance. *Research Methods in Applied Linguistics*, *3*(3), 100151. <https://doi.org/10.1016/j.rmal.2024.100151>

Jamali, M., Jabbari, A. A., & Razmi, M. H. (2023). Acquisition of attributive adjectives and noun adjuncts by L3 learners of French and German: Further evidence for the typological primacy model (TPM). *International Review of Applied Linguistics in Language Teaching*, *61*(3), 851--876. <https://doi.org/10.1515/iral-2020-0013>

Jamous, R., Ghorbani, F., Mükschel, M., Münchau, A., Frings, C., & Beste, C. (2024). Neurophysiological principles underlying predictive coding during dynamic perception-action integration. *NeuroImage*, *301*, 120891. <https://doi.org/10.1016/j.neuroimage.2024.120891>

Javitt, D. C., Siegel, S. J., Spencer, K. M., Mathalon, D. H., Hong, L. E., Martinez, A., Ehlers, C. L., Abbas, A. I., Teichert, T., Lakatos, P., & Womelsdorf, T. (2020). A roadmap for development of neuro-oscillations as translational biomarkers for treatment development in neuropsychopharmacology. *Neuropsychopharmacology*, *45*(9), 1411--1422. <https://doi.org/10.1038/s41386-020-0697-9>

Jensen, I. N., Mitrofanova, N., Anderssen, M., Rodina, Y., Slabakova, R., & Westergaard, M. (2023). Crosslinguistic influence in L3 acquisition across linguistic modules. *International Journal of Multilingualism*, *20*(3), 717--734. <https://doi.org/10.1080/14790718.2021.1985127>

Jensen, I. N., & Westergaard, M. (2023). Syntax Matters: Exploring the Effect of Linguistic Similarity in Third Language Acquisition. *Language Learning*, *73*(2), 374--402. <https://doi.org/10.1111/lang.12525>

Jerath, R., Beveridge, C., & Jensen, M. (2019). On the Hierarchical Organization of Oscillatory Assemblies: Layered Superimposition and a Global Bioelectric Framework. *Frontiers in Human Neuroscience*, *13*, 426. <https://doi.org/10.3389/fnhum.2019.00426>

Jiang, C., Liu, F., Gong, Y., Cao, Y., & Chen, J. (2023). How do Chinese-English Bilinguals and Tibetan-Chinese-English Trilinguals Differ in Explicit and Implicit Aptitude? *Journal of Psycholinguistic Research*, *52*(3), 869--885. <https://doi.org/10.1007/s10936-022-09914-3>

Jiang, R., Xie, F., & Li, A. (2024). Effect of conscious conflict on the subliminal perception of table tennis players: From the electrophysiological evidence of ERP. *Cognitive Neurodynamics*, *18*(1), 85--94. <https://doi.org/10.1007/s11571-022-09883-2>

Jiao, J., Cuza, A., & López Otero, J. C. (2020). Chapter 11. The acquisition of personal a among Chinese-speaking L2 learners of Spanish: A case for syntactic complexity. In D. Pascual Y Cabo & I. Elola (Eds.), *Issues in Hispanic and Lusophone Linguistics* (Vol. 27, pp. 233--252). John Benjamins Publishing Company. <https://doi.org/10.1075/ihll.27.11jia>

Jitpaiboon, J., Rungswang, A., & Miyamoto, Y. (2024). Investigating Motivations of Learning Languages Other Than English: A Case of Learners of Japanese in Thailand. *rEFLections*, *31*(1), 63--89. <https://doi.org/10.61508/refl.v31i1.271377>

Jo, K., Kim, K., & Kim, H. (2021). Children's interpretation of negation and quantifier scope in L3 English. *Bilingualism: Language and Cognition*, *24*(3), 427--438. <https://doi.org/10.1017/S1366728920000395>

Johannessen, J. B., Lundquist, B., Rodina, Y., Tengesdal, E., Kaldhol, N. H., Türker, E., & Fyndanis, V. (2024). Cross-linguistic effects in grammatical gender assignment and predictive processing in L1 Greek, L1 Russian, and L1 Turkish speakers of Norwegian as a second language. *Second Language Research*, 02676583241227709. <https://doi.org/10.1177/02676583241227709>

Jouravlev, O., Mineroff, Z., Blank, I. A., & Fedorenko, E. (2021). The Small and Efficient Language Network of Polyglots and Hyper-polyglots. *Cerebral Cortex*, *31*(1), 62--76. <https://doi.org/10.1093/cercor/bhaa205>

Kachinske, I., & DeKeyser, R. (2024). The role of awareness in implicit and explicit knowledge. *International Review of Applied Linguistics in Language Teaching*. <https://doi.org/10.1515/iral-2022-0212>

Kaipa, R. M., & Wendelbo, S. (2023). Comparative analysis of morphosyntactic rule learning among monolingual, bilingual, and trilingual speakers: A study on Spanish preterite forms. *International Journal of Multilingualism*, 1--18. <https://doi.org/10.1080/14790718.2023.2256788>

Kałamała, P., Walther, J., Zhang, H., Diaz, M., Senderecka, M., & Wodniecka, Z. (2022). The use of a second language enhances the neural efficiency of inhibitory control: An ERP study. *Bilingualism: Language and Cognition*, *25*(1), 163--180. <https://doi.org/10.1017/S1366728921000389>

Kang, X., Matthews, S., Yip, V., & Wong, P. C. M. (2021). Language and nonlanguage factors in foreign language learning: Evidence for the learning condition hypothesis. *Npj Science of Learning*, *6*(1), 28. <https://doi.org/10.1038/s41539-021-00104-9>

Kanik, M. (2018). Maturational constraint or system preservation. *International Journal of Applied Linguistics*, *28*(3), 451--464. <https://doi.org/10.1111/ijal.12219>

Kanli, E. (2024). Salgo de casa? Salgo a casa? Salgo la casa? Analysis of the crosslinguistic influence on preposition use in motion verb constructions by multilingual German learners of Spanish. *Ampersand*, *13*, 100186. <https://doi.org/10.1016/j.amper.2024.100186>

Kaoo, L., & Upor, R. A. (2021). LEMMATIC INFLUENCE ON VOCABULARY ACQUISITION AMONG L3 ENGLISH LANGUAGE LEARNERS IN TANZANIA. *Indonesian Journal of Applied Linguistics*, *11*(1). <https://doi.org/10.17509/ijal.v11i1.34671>

Karamacoska, D., Barry, R. J., De Blasio, F. M., & Steiner, G. Z. (2019). EEG-ERP dynamics in a visual Continuous Performance Test. *International Journal of Psychophysiology*, *146*, 249--260. <https://doi.org/10.1016/j.ijpsycho.2019.08.013>

Karamacoska, D., Barry, R. J., & Steiner, G. Z. (2019). Using principal components analysis to examine resting state EEG in relation to task performance. *Psychophysiology*, *56*(5), e13327. <https://doi.org/10.1111/psyp.13327>

Karamacoska, D., Barry, R. J., Steiner, G. Z., Coleman, E. P., & Wilson, E. J. (2018). Intrinsic EEG and task-related changes in EEG affect Go/NoGo task performance. *International Journal of Psychophysiology*, *125*, 17--28. <https://doi.org/10.1016/j.ijpsycho.2018.01.015>

Kearney, B. E., & Lanius, R. A. (2022). The brain-body disconnect: A somatic sensory basis for trauma-related disorders. *Frontiers in Neuroscience*, *16*, 1015749. <https://doi.org/10.3389/fnins.2022.1015749>

Keating, G. D. (2022). The Effect of Age of Onset of Bilingualism on Gender Agreement Processing in Spanish as a Heritage Language. *Language Learning*, *72*(4), 1170--1208. <https://doi.org/10.1111/lang.12510>

Kenanidis, P., Dąbrowska, E., Llompart, M., & Pili-Moss, D. (2023). Can adults learn L2 grammar after prolonged exposure under incidental conditions? *PLOS ONE*, *18*(7), e0288989. <https://doi.org/10.1371/journal.pone.0288989>

Kenanidis, P., Llompart, M., Santos, S. F., & Dąbrowska, E. (2024). Redundancy can hinder adult L2 grammar learning: Evidence from case markers of varying salience levels. *Frontiers in Psychology*, *15*, 1368080. <https://doi.org/10.3389/fpsyg.2024.1368080>

Kholiq, A., Yulianto, B., & Suhartono, S. (2024). ROLE OF L1 AND L2 IN THE ACQUISITION OF BAHASA INDONESIA AS A THIRD LANGUAGE. *Issues in Language Studies*, *13*(1), 413--431. <https://doi.org/10.33736/ils.5567.2024>

Kim, H., Kim, K., & Jo, K. (2024). The role of crosslinguistic morphological congruency and L2 proficiency in the L3 acquisition of English plural marking. *International Journal of Multilingualism*, *21*(2), 1074--1091. <https://doi.org/10.1080/14790718.2022.2127735>

Kim, J. S., Lee, Y. J., & Shim, S.-H. (2021). What Event-Related Potential Tells Us about Brain Function: Child-Adolescent Psychiatric Perspectives. *Journal of the Korean Academy of Child and Adolescent Psychiatry*, *32*(3), 93--98. <https://doi.org/10.5765/jkacap.210012>

Kim, K., Hsieh, L.-T., Parvizi, J., & Ranganath, C. (2020). Neural repetition suppression effects in the human hippocampus. *Neurobiology of Learning and Memory*, *173*, 107269. <https://doi.org/10.1016/j.nlm.2020.107269>

Kim, K. M., & Fenn, K. M. (2020). SLEEP-DEPENDENT CONSOLIDATION OF SECOND LANGUAGE GRAMMAR KNOWLEDGE: THE ROLE OF AWARENESS. *Studies in Second Language Acquisition*, *42*(5), 1107--1120. <https://doi.org/10.1017/S0272263120000200>

Klassen, G., Ferreira, A., & Schwieter, J. W. (2023). The role of immersion learning in the acquisition and processing of L2 gender agreement. *Applied Linguistics Review*, *14*(2), 391--413. <https://doi.org/10.1515/applirev-2020-0038>

Kleimaker, A., Kleimaker, M., Bäumer, T., Beste, C., & Münchau, A. (2020). Gilles de la Tourette Syndrome---A Disorder of Action-Perception Integration. *Frontiers in Neurology*, *11*, 597898. <https://doi.org/10.3389/fneur.2020.597898>

Kliesch, M., Becker, R., & Hervais-Adelman, A. (2022). Global and localized network characteristics of the resting brain predict and adapt to foreign language learning in older adults. *Scientific Reports*, *12*(1), 3633. <https://doi.org/10.1038/s41598-022-07629-y>

Kolb, N., Mitrofanova, N., & Westergaard, M. (2022). Crosslinguistic influence in child L3 English: An empirical study on Russian-German heritage bilinguals. *International Journal of Bilingualism*, *26*(4), 476--501. <https://doi.org/10.1177/13670069211054891>

Kolb, N., Mitrofanova, N., & Westergaard, M. (2023). Structural similarity in third language acquisition. *Linguistic Approaches to Bilingualism*, *13*(5), 607--613. <https://doi.org/10.1075/lab.23037.kol>

Kong, S. (2023). The acquisition of L3 French present simple and present progressive by adult L1 Chinese speakers of L2 English. *International Review of Applied Linguistics in Language Teaching*, *61*(2), 655--689. <https://doi.org/10.1515/iral-2022-0178>

Konkuk University, Korea, Ahn, H.-D., Cho, Y., Hwang, J.-B., Lim, J. H., & Mao, C. (2022). The Modulating Role of Mean Dependency Distance in the Backward Transfer of L3 on the Interpretation of L2 Reflexives. *The Journal of AsiaTEFL*, *19*(3), 896--910. <https://doi.org/10.18823/asiatefl.2022.19.3.9.896>

Konkuk University, Korea, Ahn, H.-D., & Jang, H. (2019). The Role of L3 in the Interpretation of Articles with Definite Plurals in L2 English. *The Journal of AsiaTEFL*, *16*(1), 12--36. <https://doi.org/10.18823/asiatefl.2019.16.1.2.12>

Konkuk University, Korea, Ahn, H.-D., & Mao, C. (2019). Reverse transfer of L3 on the Interpretation of L2 Reflexives. *The Journal of AsiaTEFL*, *16*(4), 1323--1331. <https://doi.org/10.18823/asiatefl.2019.16.4.16.1323>

Kopečková, R., Gut, U., Wrembel, M., & Balas, A. (2023). Phonological cross-linguistic influence at the initial stages of L3 acquisition. *Second Language Research*, *39*(4), 1107--1131. <https://doi.org/10.1177/02676583221123994>

Korenar, M., Treffers-Daller, J., & Pliatsikas, C. (2023). Brain structure adapts dynamically to highly demanding bilingual experiences: Insights from interpreters and translators. *Ampersand*, *11*, 100148. <https://doi.org/10.1016/j.amper.2023.100148>

Kosonogov, V., Kovsh, E., & Vorobyeva, E. (2022). Event-Related Potentials during Verbal Recognition of Naturalistic Neutral-to-Emotional Dynamic Facial Expressions. *Applied Sciences*, *12*(15), 7782. <https://doi.org/10.3390/app12157782>

Kossowska, M., Szumowska, E., & Szwed, P. (2020). *The Psychology of Tolerance in Times of Uncertainty* (1st ed.). Routledge. <https://doi.org/10.4324/9780367821487>

Koulidobrova, E., & Pichler, D. C. (2021). Cripping the "Delay": Multilingualism-Related Consequences of Re-Labeling Language Deprivation Systems. *Frontiers in Communication*, *6*, 751457. <https://doi.org/10.3389/fcomm.2021.751457>

Kruse, M. (2024). Problem-solving activity during the foreign language writing process: A proposal for categorisation and visualisation of source use and a new take on fluency in multilingual writing. *Journal of Writing Research*, *16*(1), 129--161. <https://doi.org/10.17239/jowr-2024.16.01.05>

Kubota, M., Alonso, J. G., Anderssen, M., Jensen, I. N., Luque, A., Soares, S. M. P., Prystauka, Y., Vangsnes, Ø. A., Sandstedt, J. J., & Rothman, J. (2024). Bilectal Exposure Modulates Neural Signatures to Conflicting Grammatical Properties: Norway as a Natural Laboratory. *Language Learning*, *74*(2), 436--467. <https://doi.org/10.1111/lang.12608>

Kubota, M., Heycock, C., Sorace, A., & Rothman, J. (2020). Cross-Linguistic Influence on L2 Before and After Extreme Reduction in Input: The Case of Japanese Returnee Children. *Frontiers in Psychology*, *11*, 560874. <https://doi.org/10.3389/fpsyg.2020.560874>

Kumar, G. V., Kumar, N., Roy, D., & Banerjee, A. (2018). Segregation and Integration of Cortical Information Processing Underlying Cross-Modal Perception. *Multisensory Research*, *31*(5), 481--500. <https://doi.org/10.1163/22134808-00002574>

Kupisch, T., Soares, S. M. P., Puig‐Mayenco, E., & Rothman, J. (2021). Multilingualism and Chomsky's Generative Grammar. In N. Allott, T. Lohndal, & G. Rey (Eds.), *A Companion to Chomsky* (1st ed., pp. 232--242). Wiley. <https://doi.org/10.1002/9781119598732.ch15>

Kush, D., & Dahl, A. (2022). L2 transfer of L1 island-insensitivity: The case of Norwegian. *Second Language Research*, *38*(2), 315--346. <https://doi.org/10.1177/0267658320956704>

Kustubayeva, A., Kamzanova, A., Kudaibergenova, S., Pivkina, V., & Matthews, G. (2020). Major Depression and Brain Asymmetry in a Decision-Making Task with Negative and Positive Feedback. *Symmetry*, *12*(12), 2118. <https://doi.org/10.3390/sym12122118>

Kuzmina, E., Goral, M., Norvik, M., & Weekes, B. S. (2019). What Influences Language Impairment in Bilingual Aphasia? A Meta-Analytic Review. *Frontiers in Psychology*, *10*, 445. <https://doi.org/10.3389/fpsyg.2019.00445>

Labotka, D., Sabo, E., Bonais, R., Gelman, S. A., & Baptista, M. (2023). Testing the effects of congruence in adult multilingual acquisition with implications for creole genesis. *Cognition*, *235*, 105387. <https://doi.org/10.1016/j.cognition.2023.105387>

Lago, S., Mosca, M., & Stutter Garcia, A. (2021). The Role of Crosslinguistic Influence in Multilingual Processing: Lexicon Versus Syntax. *Language Learning*, *71*(S1), 163--192. <https://doi.org/10.1111/lang.12412>

Lago, S., Stone, K., Oltrogge, E., & Veríssimo, J. (2023). Possessive Processing in Bilingual Comprehension. *Language Learning*, *73*(3), 904--941. <https://doi.org/10.1111/lang.12556>

Lago, S., Stutter Garcia, A., & Felser, C. (2019). The role of native and non-native grammars in the comprehension of possessive pronouns. *Second Language Research*, *35*(3), 319--349. <https://doi.org/10.1177/0267658318770491>

Laiveniece, D., & Lauze, L. (2022). Students' Linguistic Attitude Towards Language Mistakes/Errors in Learning and Using a Foreign Language. *Sustainable Multilingualism*, *21*(1), 227--248. <https://doi.org/10.2478/sm-2022-0019>

Lee, A. H., & Lloyd, J. S. (2024). The effects of incidental learning and input frequency on the perception of non-native speech. *Second Language Research*, 02676583241249348. <https://doi.org/10.1177/02676583241249348>

Lee, K. M., Kang, S., Hong, S. H., & Moon, I. J. (2024). Effects of Metrical Context on the P1 Component. *Journal of Audiology and Otology*, *28*(3), 195--202. <https://doi.org/10.7874/jao.2023.00262>

Leivada, E., Westergaard, M., Duñabeitia, J. A., & Rothman, J. (2021). On the phantom-like appearance of bilingualism effects on neurocognition: (How) should we proceed? *Bilingualism: Language and Cognition*, *24*(1), 197--210. <https://doi.org/10.1017/S1366728920000358>

Leow, R. P. (2019). ISLA: How implicit or how explicit should it be? Theoretical, empirical, and pedagogical/curricular issues. *Language Teaching Research*, *23*(4), 476--493. <https://doi.org/10.1177/1362168818776674>

Li, Y. (2021). An investigation on the role of L2 proficiency in adult learners' L2 morphological performance. *International Journal of Applied Linguistics*, *31*(3), 421--437. <https://doi.org/10.1111/ijal.12339>

Libben, G., & Schwieter, J. W. (2019). Lexical Organization and Reorganization in the Multilingual Mind. In J. W. Schwieter & M. Paradis (Eds.), *The Handbook of the Neuroscience of Multilingualism* (1st ed., pp. 297--312). Wiley. <https://doi.org/10.1002/9781119387725.ch14>

Liebherr, M., Weiland-Breckle, H., Grewe, T., & Schumacher, P. B. (2018). Cognitive performance under motor demands -- On the influence of task difficulty and postural control. *Brain Research*, *1684*, 1--8. <https://doi.org/10.1016/j.brainres.2018.01.025>

Likhanov, M., Bogdanova, O., Alenina, E., Kolienko, T., & Kovas, Y. (2023). No evidence of a positive effect of learning Chinese language as an L2 on spatial ability. *Scientific Reports*, *13*(1), 1262. <https://doi.org/10.1038/s41598-022-26738-2>

Lin, B., Chen, Y., Li, B., Avitt, A., Guo, Y., Pan, L., & Huang, X. (2022). Spatial selectivity of the visual duration aftereffect in the sub-second range: An event-related potentials study. *Behavioural Brain Research*, *431*, 113950. <https://doi.org/10.1016/j.bbr.2022.113950>

Lin, L., Leung, A. W. S., Wu, J., & Zhang, L. (2020). Individual differences under acute stress: Higher cortisol responders performs better on N-back task in young men. *International Journal of Psychophysiology*, *150*, 20--28. <https://doi.org/10.1016/j.ijpsycho.2020.01.006>

Lin, W., Li, Z., Zhang, X., Gao, Y., & Lin, J. (2023). Electrophysiological evidence for the effectiveness of images versus text in warnings. *Scientific Reports*, *13*(1), 1278. <https://doi.org/10.1038/s41598-023-28230-x>

Lin, W., Lin, J., Yang, Y., Liao, J., Chen, W., & Mo, L. (2022). The difference in the warning effect of different warning signs. *International Journal of Occupational Safety and Ergonomics*, *28*(2), 890--900. <https://doi.org/10.1080/10803548.2020.1840733>

Linck, J. A., Clark, M., Bonilla, C. L., Golonka, E., Doughty, C. J., Mecham, T., & Burns, W. (2020). Autonomous Portuguese L3 learning through an adaptive platform. In K. V. Molsing, C. Becker Lopes Perna, & A. M. Tramunt Ibaños (Eds.), *Issues in Hispanic and Lusophone Linguistics* (Vol. 24, pp. 231--258). John Benjamins Publishing Company. <https://doi.org/10.1075/ihll.24.09lin>

Lindström, E., & Lubińska, D. (2022). Target-like and non-target-like conjunctive relations in L2 Swedish beginner writing. *Linguistics and Education*, *71*, 101073. <https://doi.org/10.1016/j.linged.2022.101073>

Lipińska, A. (2023). Crosslinguistic influence from the learners' perspective. *Colloquia Germanica Stetinensia*, *32*, 307--323. <https://doi.org/10.18276/cgs.2023.32-15>

Liu, C., Lin, Y., Ye, C., Yang, J., & He, W. (2023). Alpha ERS-ERD Pattern during Divergent and Convergent Thinking Depends on Individual Differences on Metacontrol. *Journal of Intelligence*, *11*(4), 74. <https://doi.org/10.3390/jintelligence11040074>

Liu, J., & Lin, J. (2021). A Cross-Linguistic Study of L3 Phonological Acquisition of Stop Contrasts. *Sage Open*, *11*(1), 2158244020985510. <https://doi.org/10.1177/2158244020985510>

Liu, X., Xu, X., & Wang, H. (2018). The effect of emotion on morphosyntactic learning in foreign language learners. *PLOS ONE*, *13*(11), e0207592. <https://doi.org/10.1371/journal.pone.0207592>

Liu, Y., & Dras, M. (2024). Using corpora from Natural Language Processing for investigating crosslinguistic influence. *Ampersand*, *12*, 100174. <https://doi.org/10.1016/j.amper.2024.100174>

Liu, Z. (2022). Mapping the research trends of third language acquisition: A bibliometric analysis based on Scopus. *Frontiers in Psychology*, *13*, 1021517. <https://doi.org/10.3389/fpsyg.2022.1021517>

Llama, R., & Cardoso, W. (2018). Revisiting (Non-)Native Influence in VOT Production: Insights from Advanced L3 Spanish. *Languages*, *3*(3), 30. <https://doi.org/10.3390/languages3030030>

Llinàs-Grau, M., & Bel, A. (2019). On the Acceptance of the Null That by Bilingual Catalan/Spanish L2 Learners of English. *Languages*, *4*(2), 30. <https://doi.org/10.3390/languages4020030>

Llop Naya, A., Puig-Mayenco, E., & Paradís, A. (2024). The acquisition of Polarity Items in L3/Ln Catalan by speakers of English, Italian, Portuguese and Spanish: Implications for L3/Ln development theorising and language teaching. *International Journal of Multilingualism*, 1--23. <https://doi.org/10.1080/14790718.2024.2367583>

Lloyd-Smith, A., Gyllstad, H., Kupisch, T., & Quaglia, S. (2021). Heritage language proficiency does not predict syntactic CLI into L3 English. *International Journal of Bilingual Education and Bilingualism*, *24*(3), 435--451. <https://doi.org/10.1080/13670050.2018.1472208>

Lohndal, T. (2021). Syntax of Heritage Languages. In S. Montrul & M. Polinsky (Eds.), *The Cambridge Handbook of Heritage Languages and Linguistics* (1st ed., pp. 644--667). Cambridge University Press. <https://doi.org/10.1017/9781108766340.029>

Lohndal, T., Rothman, J., Kupisch, T., & Westergaard, M. (2019). Heritage language acquisition: What it reveals and why it is important for formal linguistic theories. *Language and Linguistics Compass*, *13*(12), e12357. <https://doi.org/10.1111/lnc3.12357>

Long, A. (2022). Uncommonly Studied Language Pairs. In K. Geeslin, *The Routledge Handbook of Second Language Acquisition and Sociolinguistics* (1st ed., pp. 420--432). Routledge. <https://doi.org/10.4324/9781003017325-38>

Lorenz, E. (2022). *Crosslinguistic Influence in L3 Acquisition: Bilingual Heritage Speakers in Germany* (1st ed.). Routledge. <https://doi.org/10.4324/9781003134336>

Lorenz, E., Bonnie, R. J., Feindt, K., Rahbari, S., & Siemund, P. (2019). Cross-linguistic influence in unbalanced bilingual heritage speakers on subsequent language acquisition: Evidence from pronominal object placement in ditransitive clauses. *International Journal of Bilingualism*, *23*(6), 1410--1430. <https://doi.org/10.1177/1367006918791296>

Lorenz, E., Toprak-Yildiz, T. E., & Siemund, P. (2024). L3 English in the German secondary school context: Longitudinal development of bilingual heritage speakers' multilingual repertoire. *International Journal of Multilingualism*, 1--22. <https://doi.org/10.1080/14790718.2024.2345215>

Luan, X., Kuno, M., Sugawara, A., Kawasaki, Y., & Sugimori, E. (2024). The effect of previously acquired languages on third language acquisition. *Heliyon*, *10*(4), e26202. <https://doi.org/10.1016/j.heliyon.2024.e26202>

Luk, G. (2023). Justice and equity for whom? Reframing research on the "bilingual (dis)advantage." *Applied Psycholinguistics*, *44*(3), 301--315. <https://doi.org/10.1017/S0142716422000339>

Luk, G., & Rothman, J. (2022). Experience-based individual differences modulate language, mind and brain outcomes in multilinguals. *Brain and Language*, *228*, 105107. <https://doi.org/10.1016/j.bandl.2022.105107>

Luo, C., Biencinto López, C., & Ruiz, J. M. (2022). Motivación de los estudiantes chinos en el aprendizaje del español. *Hispania*, *105*(1), 67--89. <https://doi.org/10.1353/hpn.2022.0006>

Luo, J., Li, V. G., & Mok, P. P. K. (2020). The Perception of Cantonese Vowel Length Contrast by Mandarin Speakers. *Language and Speech*, *63*(3), 635--659. <https://doi.org/10.1177/0023830919879471>

Luque, A., & Covey, L. (2023). Factors Accounting for Individual Differences in Second Language Neurocognition. In K. Morgan-Short & J. G. Van Hell, *The Routledge Handbook of Second Language Acquisition and Neurolinguistics* (1st ed., pp. 274--286). Routledge. <https://doi.org/10.4324/9781003190912-25>

Lutz, N. D., Admard, M., Genzoni, E., Born, J., & Rauss, K. (2021). Occipital sleep spindles predict sequence learning in a visuo-motor task. *SLEEP*, *44*(8), zsab056. <https://doi.org/10.1093/sleep/zsab056>

Madashetty, S., Palaniswamy, H. P., & Rajashekhar, B. (2024). Investigating the impact of hearing loss on attentional networks among older individuals: An event-related potential study. *Cognitive Neurodynamics*. <https://doi.org/10.1007/s11571-024-10140-x>

Madeira, A. (2018). Inflected infinitives in L2 Portuguese. In A. L. Santos & A. Gonçalves (Eds.), *Issues in Hispanic and Lusophone Linguistics* (Vol. 17, pp. 321--360). John Benjamins Publishing Company. <https://doi.org/10.1075/ihll.17.11mad>

Madlener, K. (2018). Chapter 10. Do findings from artificial language learning generalize to second language classrooms? In A. E. Tyler, L. Ortega, M. Uno, & H. I. Park (Eds.), *Language Learning & Language Teaching* (Vol. 49, pp. 211--234). John Benjamins Publishing Company. <https://doi.org/10.1075/lllt.49.10mad>

Magliacano, A., Fiorenza, S., Estraneo, A., & Trojano, L. (2020). Eye blink rate increases as a function of cognitive load during an auditory oddball paradigm. *Neuroscience Letters*, *736*, 135293. <https://doi.org/10.1016/j.neulet.2020.135293>

Magnuson, J. R., Doesburg, S. M., & McNeil, C. J. (2021). Development and recovery time of mental fatigue and its impact on motor function. *Biological Psychology*, *161*, 108076. <https://doi.org/10.1016/j.biopsycho.2021.108076>

Maie, R., & DeKeyser, R. M. (2020). CONFLICTING EVIDENCE OF EXPLICIT AND IMPLICIT KNOWLEDGE FROM OBJECTIVE AND SUBJECTIVE MEASURES. *Studies in Second Language Acquisition*, *42*(2), 359--382. <https://doi.org/10.1017/S0272263119000615>

Mamede, A., Boffo, M., Noordzij, G., Denktaş, S., & Wieser, M. J. (2024). The effect of cognitive reappraisal on food craving and consumption: Does working memory capacity influence reappraisal ability? An event-related potential study. *Appetite*, *193*, 107112. <https://doi.org/10.1016/j.appet.2023.107112>

Marafioti, P. E. (2024). Regímenes latentes de error en el aprendizaje de la concordancia plural en ELE. *Forma y Función*, *37*(1). <https://doi.org/10.15446/fyf.v37n1.104617>

Marciszewska, A. A. (2021). L3 morphosyntactic processing among Polish--English bilinguals: Considering learners' level of bilingualism and language dominance. *Open Linguistics*, *7*(1), 353--371. <https://doi.org/10.1515/opli-2021-0015>

Mariani, N., Abdullah Al-Rawe, M. F., Al-Salami, A. A. A., & Kumar, T. (2024). The Impact of Bilingualism on Learning a Third Language: A Case Study of Iraqi Learners of Indonesian. *International Journal of Society, Culture and Language*, *12*(2). <https://doi.org/10.22034/ijscl.2023.2008408.3119>

Masaracchia, L., Fredes, F., Woolrich, M. W., & Vidaurre, D. (2023). Dissecting unsupervised learning through hidden Markov modeling in electrophysiological data. *Journal of Neurophysiology*, *130*(2), 364--379. <https://doi.org/10.1152/jn.00054.2023>

Mather, P.-A. (2020). Higher Education and the Multilingual Classroom: How Applied Linguistics Research Can Help Design Effective Teaching Strategies. In P.-A. Mather (Ed.), *Technology-enhanced Learning and Linguistic Diversity: Strategies and Approaches to Teaching Students in a 2nd or 3rd Language* (pp. 1--9). Emerald Publishing Limited. <https://doi.org/10.1108/978-1-83982-128-820201001>

McMillan, R., & Muthukumaraswamy, S. D. (2020). The neurophysiology of ketamine: An integrative review. *Reviews in the Neurosciences*, *31*(5), 457--503. <https://doi.org/10.1515/revneuro-2019-0090>

McPartland, J. C., Lerner, M. D., Bhat, A., Clarkson, T., Jack, A., Koohsari, S., Matuskey, D., McQuaid, G. A., Su, W.-C., & Trevisan, D. A. (2021). Looking Back at the Next 40 Years of ASD Neuroscience Research. *Journal of Autism and Developmental Disorders*, *51*(12), 4333--4353. <https://doi.org/10.1007/s10803-021-05095-5>

McWilliams, E. C., Barbey, F. M., Dyer, J. F., Islam, M. N., McGuinness, B., Murphy, B., Nolan, H., Passmore, P., Rueda-Delgado, L. M., & Buick, A. R. (2021). Feasibility of Repeated Assessment of Cognitive Function in Older Adults Using a Wireless, Mobile, Dry-EEG Headset and Tablet-Based Games. *Frontiers in Psychiatry*, *12*, 574482. <https://doi.org/10.3389/fpsyt.2021.574482>

Mercante, B., Enrico, P., & Deriu, F. (2023). Cognitive Functions following Trigeminal Neuromodulation. *Biomedicines*, *11*(9), 2392. <https://doi.org/10.3390/biomedicines11092392>

Mercante, B., Enrico, P., Ginatempo, F., Loi, N., & Deriu, F. (2023). Short-term transcutaneous trigeminal nerve stimulation does not affect visual oddball task and paired-click paradigm ERP responses in healthy volunteers. *Experimental Brain Research*, *241*(2), 327--339. <https://doi.org/10.1007/s00221-022-06525-1>

Mickan, A., & Lemhöfer, K. (2020). Tracking Syntactic Conflict between Languages over the Course of L2 Acquisition: A Cross-sectional Event-related Potential Study. *Journal of Cognitive Neuroscience*, *32*(5), 822--846. <https://doi.org/10.1162/jocn_a_01528>

Mickan, A., McQueen, J. M., & Lemhöfer, K. (2020). Between-language competition as a driving force in foreign language attrition. *Cognition*, *198*, 104218. <https://doi.org/10.1016/j.cognition.2020.104218>

Mihi Park, & Peck Jeeyoung. (2022). Beneficial effect of multilingualism in resolving L3 structural complexity: Attention shift from familiar cue to critical cue. *Linguistic Research*, *39*(null), 1--27. <https://doi.org/10.17250/KHISLI.39..202209.001>

Miller, D., DeLuca, V., Swanson, K., & Rothman, J. (2023). Neurolinguistic Methods and Generative Approaches to Second Language Acquisition. In K. Morgan-Short & J. G. Van Hell, *The Routledge Handbook of Second Language Acquisition and Neurolinguistics* (1st ed., pp. 177--190). Routledge. <https://doi.org/10.4324/9781003190912-17>

Mitrofanova, N., Leivada, E., & Westergaard, M. (2023). Crosslinguistic influence in L3 acquisition: Evidence from artificial language learning. *Linguistic Approaches to Bilingualism*, *13*(5), 717--742. <https://doi.org/10.1075/lab.22063.mit>

Monachino, A. D., Lopez, K. L., Pierce, L. J., & Gabard-Durnam, L. J. (2022). The HAPPE plus Event-Related (HAPPE+ER) software: A standardized preprocessing pipeline for event-related potential analyses. *Developmental Cognitive Neuroscience*, *57*, 101140. <https://doi.org/10.1016/j.dcn.2022.101140>

Montrul, S. (2019). The acquisition of differential object marking in Spanish by Romanian speakers. *Revista Española de Lingüística Aplicada/Spanish Journal of Applied Linguistics*, *32*(1), 185--219. <https://doi.org/10.1075/resla.17040.mon>

Montrul, S. (2023). Chapter 1 Heritage language development: Dominant language transfer and the sociopolitical context. In F. B. Romano (Ed.), *Studies in Italian as a Heritage Language* (pp. 5--32). De Gruyter. <https://doi.org/10.1515/9783110759587-002>

Montrul, S. A. (2018). Chapter 6. The Bottleneck Hypothesis extends to heritage language acquisition. In J. Cho, M. Iverson, T. Judy, T. Leal, & E. Shimanskaya (Eds.), *Studies in Bilingualism* (Vol. 55, pp. 149--177). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.55.06mon>

Montrul, S., Mason, S. A., & Armstrong, A. (2024). The Role of Language Experience in the Acquisition of Spanish Gender Agreement: A Study with Nonce Nouns. *Languages*, *9*(2), 45. <https://doi.org/10.3390/languages9020045>

Morales-Front, A., & Sanz, C. (2021). Piecemeal crosslinguistic influence and multilingualism. *Second Language Research*, *37*(3), 473--479. <https://doi.org/10.1177/0267658320943663>

Morand-Beaulieu, S., & Lavoie, M. E. (2019). Cognitive and motor event-related potentials in Tourette syndrome and tic disorders: A systematic review. *Clinical Neurophysiology*, *130*(6), 1041--1057. <https://doi.org/10.1016/j.clinph.2018.10.022>

Morand-Beaulieu, S., Perrault, M.-A., & Lavoie, M. E. (2022). Test-Retest Reliability of Event-Related Potentials Across Three Tasks. *Journal of Psychophysiology*, *36*(2), 100--117. <https://doi.org/10.1027/0269-8803/a000286>

Morris, M. B., Jack Rhodes, L., Borghetti, L., & Haubert, A. (2023). Vigilance end-spurt patterns in event-related potentials. *Brain Research*, *1812*, 148396. <https://doi.org/10.1016/j.brainres.2023.148396>

Mosca, M. (2019). Trilinguals' language switching: A strategic and flexible account. *Quarterly Journal of Experimental Psychology*, *72*(4), 693--716. <https://doi.org/10.1177/1747021818763537>

Mottarella, M., & Prat, C. S. (2023). Using Quantitative Electroencephalography (qEEG) to Investigate Second Language Learning. In K. Morgan-Short & J. G. Van Hell, *The Routledge Handbook of Second Language Acquisition and Neurolinguistics* (1st ed., pp. 31--45). Routledge. <https://doi.org/10.4324/9781003190912-5>

Mückschel, M., Ziemssen, T., & Beste, C. (2020). Properties of lower level processing modulate the actions of the norepinephrine system during response inhibition. *Biological Psychology*, *152*, 107862. <https://doi.org/10.1016/j.biopsycho.2020.107862>

Murphy, B., Aleni, A., Belaoucha, B., Dyer, J., & Nolan, H. (2018). Quantifying cognitive aging and performance with at-home gamified mobile EEG. *2018 International Workshop on Pattern Recognition in Neuroimaging (PRNI)*, 1--4. <https://doi.org/10.1109/PRNI.2018.8423954>

Murphy, E., Hoshi, K., & Benítez-Burraco, A. (2022). Subcortical syntax: Reconsidering the neural dynamics of language. *Journal of Neurolinguistics*, *62*, 101062. <https://doi.org/10.1016/j.jneuroling.2022.101062>

Mustile, M., Giocondo, F., Caligiore, D., Borghi, A. M., & Kourtis, D. (2021). Motor Inhibition to Dangerous Objects: Electrophysiological Evidence for Task-dependent Aversive Affordances. *Journal of Cognitive Neuroscience*, *33*(5), 826--839. <https://doi.org/10.1162/jocn_a_01690>

Mykhalchuk, N., Levchuk, P., Ivashkevych, E., & Nabochuk, A. (2023). Dynamic Models of Multilingualism on the Territory of Western Ukraine. *PSYCHOLINGUISTICS*, *33*(2), 114--144. <https://doi.org/10.31470/2309-1797-2023-33-2-114-144>

Nahum, M., & Bavelier, D. (2020). Video games as rich environments to foster brain plasticity. In *Handbook of Clinical Neurology* (Vol. 168, pp. 117--136). Elsevier. <https://doi.org/10.1016/B978-0-444-63934-9.00010-X>

Najjar, N. (2021). Studies on factors influencing syntactic transfer in L3 acquisition. *Studia Linguistica Universitatis Iagellonicae Cracoviensis*, *138*(2), 79--109. <https://doi.org/10.4467/20834624SL.21.009.13472>

Nathaniel, U., Eidelsztein, S., Geskin, K. G., Yamasaki, B. L., Nir, B., Dronjic, V., Booth, J. R., & Bitan, T. (2023). Decomposition in early stages of learning novel morphologically derived words: The impact of linear vs. non-linear structure. *Cognition*, *240*, 105604. <https://doi.org/10.1016/j.cognition.2023.105604>

Nejati, R., & Jabbari, M. (2023). EVALUATING THE VALIDITY OF MEARA AND ROGERS' VOCABULARY APTITUDE TEST: A RASCH MEASUREMENT MODEL ANALYSIS. *Issues in Language Studies*, *12*(2), 37--55. <https://doi.org/10.33736/ils.5290.2023>

Nelson, C., Krzysik, I., Lewandowska, H., & Wrembel, M. (2021). Multilingual learners' perceptions of cross-linguistic distances: A proposal for a visual psychotypological measure. *Language Awareness*, *30*(2), 176--194. <https://doi.org/10.1080/09658416.2021.1897132>

Nettinga, J., Naseem, S., Yakobi, O., Willoughby, T., & Danckert, J. (2024). Exploring EEG resting state as a function of boredom proneness in pre-adolescents and adolescents. *Experimental Brain Research*, *242*(1), 123--135. <https://doi.org/10.1007/s00221-023-06733-3>

Ocklenburg, S., Friedrich, P., Fraenz, C., Schlüter, C., Beste, C., Güntürkün, O., & Genç, E. (2018). Neurite architecture of the planum temporale predicts neurophysiological processing of auditory speech. *Science Advances*, *4*(7), eaar6830. <https://doi.org/10.1126/sciadv.aar6830>

O'Grady, W. (2022). Chapter 8. A calculus for L1 transfer. In A. G. Benati & J. W. Schwieter (Eds.), *Bilingual Processing and Acquisition* (Vol. 14, pp. 143--176). John Benjamins Publishing Company. <https://doi.org/10.1075/bpa.14.08ogr>

Orcasitas-Vicandi, M. (2020). Crosslinguistic influence and morphological awareness in English (third language) writing. *International Journal of Bilingualism*, *24*(4), 616--633. <https://doi.org/10.1177/1367006919852164>

Orcasitas-Vicandi, M. (2022a). Lexical crosslinguistic influence in Basque-Spanish bilinguals' English (L3) writing. *International Journal of Bilingual Education and Bilingualism*, *25*(2), 491--501. <https://doi.org/10.1080/13670050.2019.1701979>

Orcasitas-Vicandi, M. (2022b). Towards a multilingual approach in assessing writing: Holistic, analytic and cross-linguistic perspectives. *International Journal of Bilingual Education and Bilingualism*, *25*(6), 2186--2207. <https://doi.org/10.1080/13670050.2021.1894089>

Ortin, R., & Fernandez-Florez, C. (2019). Transfer of variable grammars in third language acquisition. *International Journal of Multilingualism*, *16*(4), 442--458. <https://doi.org/10.1080/14790718.2018.1550088>

Otwinowska, A. (2024). Cross-linguistic influence and language co-activation in acquiring L3 words: What empirical evidence do we have so far? *Second Language Research*, *40*(3), 765--783. <https://doi.org/10.1177/02676583231176371>

Ou, J., & Law, S.-P. (2018). Induced gamma oscillations index individual differences in speech sound perception and production. *Neuropsychologia*, *121*, 28--36. <https://doi.org/10.1016/j.neuropsychologia.2018.10.028>

Pan, J., Zhang, Y., & Zhang, W. (2023). Revisiting attending to form during meaning comprehension in learning Spanish as an additional foreign language. *Foreign Language Annals*, *56*(1), 214--231. <https://doi.org/10.1111/flan.12664>

Panther, F., Mattingley, W., Hay, J., Todd, S., King, J., & Keegan, P. J. (2024). Morphological segmentations of Non-Māori Speaking New Zealanders match proficient speakers. *Bilingualism: Language and Cognition*, *27*(1), 1--15. <https://doi.org/10.1017/S1366728923000329>

Paquet, P.-L. (2018). Influence of L1 Properties and Proficiency on the Acquisition of Gender Agreement. *Journal of Language and Education*, *4*(1), 92--104. <https://doi.org/10.17323/2411-7390-2018-4-1-92-104>

Park, M. (2022). Chapter 4. Cross-linguistic influence in the acquisition of L3 variation: A comparison of speech and writing. In R. Bayley, D. R. Preston, & X. Li (Eds.), *Studies in Language Variation* (Vol. 28, pp. 71--96). John Benjamins Publishing Company. <https://doi.org/10.1075/silv.28.04par>

Park, M., & García Mayo, M. D. P. (2023). Comprehension of English articles by Korean learners of L2 English and L3 Spanish. *International Review of Applied Linguistics in Language Teaching*. <https://doi.org/10.1515/iral-2022-0152>

Park, M., & Starr, R. L. (2020). The acquisition of L3 variation among early bilinguals: The roles of L2 experience, home language and linguistic factors. *Linguistic Approaches to Bilingualism*, *10*(5), 657--689. <https://doi.org/10.1075/lab.17066.par>

Parrish, K. (2022). The Categorization of L3 Vowels Near First Exposure by Spanish-English Bilinguals. *Languages*, *7*(3), 226. <https://doi.org/10.3390/languages7030226>

Parrish, K. (2024a). Statistical Insignificance is not wholesale transfer in L3 Acquisition: An approximate replication of Rothman (2011). *Studies in Second Language Acquisition*, 1--18. <https://doi.org/10.1017/S0272263124000342>

Parrish, K. (2024b). The production of L3 stop-initial words by Spanish/English bilinguals. *International Journal of Multilingualism*, *21*(1), 131--148. <https://doi.org/10.1080/14790718.2022.2060234>

Pathak, L. S., Vulchanova, M., Pathak, P., & Mishra, R. K. (2024). Trilingual parallel processing: Do the dominant languages grab all the attention? *Bilingualism: Language and Cognition*, 1--18. <https://doi.org/10.1017/S1366728924000257>

Patience, M. (2018). Acquisition of the Tap-Trill Contrast by L1 Mandarin--L2 English--L3 Spanish Speakers. *Languages*, *3*(4), 42. <https://doi.org/10.3390/languages3040042>

Patience, M., & Qian, W. (2022). The Role of Task Complexity and Dominant Articulatory Routines in the Acquisition of L3 Spanish. *Languages*, *7*(2), 90. <https://doi.org/10.3390/languages7020090>

Pavlovskaya, N., Riches, N., & Young-Scholten, M. (2024). Chapter 8. First exposure to Russian word forms by adult English speakers: Disentangling language‑specific and language‑universal factors. In L. Hracs (Ed.), *Language Acquisition and Language Disorders* (Vol. 69, pp. 191--224). John Benjamins Publishing Company. <https://doi.org/10.1075/lald.69.08pav>

Payne, B. R., Ng, S., Shantz, K., & Federmeier, K. D. (2020). Event-related brain potentials in multilingual language processing: The N's and P's. In *Psychology of Learning and Motivation* (Vol. 72, pp. 75--118). Elsevier. <https://doi.org/10.1016/bs.plm.2020.03.003>

Pehlivanoglu, D., Myers, E., & Ebner, N. C. (2020). -Phasic Model of xytocin (): A systematic conceptual review of oxytocin-related ERP research. *Biological Psychology*, *154*, 107917. <https://doi.org/10.1016/j.biopsycho.2020.107917>

Pélissier{, M. (2020). *Comparing ERPs between native speakers and second language learners: Dealing with individual variability*. Zenodo. <https://doi.org/10.5281/ZENODO.4032282>

Peña-Acuña, B., & Crismán-Pérez, R. (2022). Research on Papua, a digital tool with artificial intelligence in favor of learning and linguistic attitudes towards the learning of the English language in students of Spanish language as L1. *Frontiers in Psychology*, *13*, 1019278. <https://doi.org/10.3389/fpsyg.2022.1019278>

Pereira Soares, S. M., Kubota, M., Rossi, E., & Rothman, J. (2021). Determinants of bilingualism predict dynamic changes in resting state EEG oscillations. *Brain and Language*, *223*, 105030. <https://doi.org/10.1016/j.bandl.2021.105030>

Pereira Soares, S. M., Kupisch, T., & Rothman, J. (2022). Testing Potential Transfer Effects in Heritage and Adult L2 Bilinguals Acquiring a Mini Grammar as an Additional Language: An ERP Approach. *Brain Sciences*, *12*(5), 669. <https://doi.org/10.3390/brainsci12050669>

Pereira Soares, S. M., Prystauka, Y., DeLuca, V., Poch, C., & Rothman, J. (2024). Brain correlates of attentional load processing reflect degree of bilingual engagement: Evidence from EEG. *NeuroImage*, *298*, 120786. <https://doi.org/10.1016/j.neuroimage.2024.120786>

Pereira Soares, S. M., Prystauka, Y., DeLuca, V., & Rothman, J. (2022). Type of bilingualism conditions individual differences in the oscillatory dynamics of inhibitory control. *Frontiers in Human Neuroscience*, *16*, 910910. <https://doi.org/10.3389/fnhum.2022.910910>

Pereira Soares, S. M., & Rothman, J. (2021). Cognitive states in third language acquisition and beyond: Theoretical and methodological paths forward. *Linguistic Approaches to Bilingualism*, *11*(1), 89--95. <https://doi.org/10.1075/lab.20080.per>

Pereyron, L., & Alves, U. K. (2020). Multi-directionality in language transfer: Development of the vowel system of Brazilian Portuguese as a second (L2) or third language (L3). In K. V. Molsing, C. Becker Lopes Perna, & A. M. Tramunt Ibaños (Eds.), *Issues in Hispanic and Lusophone Linguistics* (Vol. 24, pp. 83--106). John Benjamins Publishing Company. <https://doi.org/10.1075/ihll.24.04per>

Pérez-Valverde, C., Ruiz-Cecilia, R., Medina-Sánchez, L., & Guijarro-Ojeda, J. R. (2021). Coping with Challenges in Teaching Foreign Languages to Children with Mild Intellectual Disabilities: Stakeholders' Perspectives. *Mathematics*, *9*(8), 906. <https://doi.org/10.3390/math9080906>

Perpiñán, S., & Montrul, S. (2023). Does your regional variety help you acquire an additional language?: Spanish differential object marking in Northern and Southern Italians. *Linguistic Approaches to Bilingualism*, *13*(5), 663--692. <https://doi.org/10.1075/lab.22057.per>

PhD candidate, Department of Foreign Languages, Isfahan (Khorasgan) Branch, Islamic Azad University, Isfahan, Iran, maryam.ghezlou@gmail.com, Ghezlou, M., Koosha, M., Assoc. Prof., Department of Foreign Languages, Isfahan (Khorasgan) Branch, Islamic Azad University, Isfahan, Iran, mansourkoosha@yahoo.com, Lotfi, A. R., & Asst. Prof., Department of Foreign Languages, Isfahan (Khorasgan) Branch, Islamic Azad University, Isfahan, Iran, lotfi.ahmadreza@gmail.com. (2019). Cross-linguistic Influence in the L3 Acquisition of English Adjective Properties by Azeri-Persian Bilinguals. *International Journal of Instruction*, *12*(1), 1299--1318. <https://doi.org/10.29333/iji.2019.12183a>

Pichler, D. C., & Koulidobrova, E. (2023). The Role of Modality in L2 Learning: The Importance of Learners Acquiring a Second Sign Language (M2L2 and M1L2 Learners). *Language Learning*, *73*(S1), 197--233. <https://doi.org/10.1111/lang.12607>

Picoral, A., & Carvalho, A. M. (2020). The Acquisition of Preposition + Article Contractions in L3 Portuguese among Different L1-Speaking Learners: A Variationist Approach. *Languages*, *5*(4), 45. <https://doi.org/10.3390/languages5040045>

Pirvulescu, M., Hill, V., Nacif, N., Helms-Park, R., & Petrescu, M. (2022). The acquisition of adverbs in child L3 French in Canada. *Glossa: A Journal of General Linguistics*, *7*(1). <https://doi.org/10.16995/glossa.5721>

Pitsik, E. N. (2022). Recurrence quantification analysis detects P300 in single-trial EEG. In B. N. Khlebtsov & D. E. Postnov (Eds.), *Computational Biophysics and Nanobiophotonics* (p. 40). SPIE. <https://doi.org/10.1117/12.2626711>

Pitsik, N. E. (2022). Recurrence Quantification Analysis of P300 Event-Related Potential on Single-Trial EEG. *Bulletin of the Russian Academy of Sciences: Physics*, *86*(2), 211--215. <https://doi.org/10.3103/S1062873822020241>

Poeste, M., Müller, N., & Arnaus Gil, L. (2019). Code-mixing and language dominance: Bilingual, trilingual and multilingual children compared. *International Journal of Multilingualism*, *16*(4), 459--491. <https://doi.org/10.1080/14790718.2019.1569017>

Popp, F., Dallmer-Zerbe, I., Philipsen, A., & Herrmann, C. S. (2019). Challenges of P300 Modulation Using Transcranial Alternating Current Stimulation (tACS). *Frontiers in Psychology*, *10*, 476. <https://doi.org/10.3389/fpsyg.2019.00476>

Prela, L., Llompart, M., & Dąbrowska, E. (2022). Aptitude and experience as predictors of grammatical proficiency in adult Greek-English bilinguals. *Frontiers in Psychology*, *13*, 1062821. <https://doi.org/10.3389/fpsyg.2022.1062821>

Převrátilová, S. (2023). One Mind, Many Languages: Czech as an Additional Language in Plurilingual Repertoires. *Sustainable Multilingualism*, *23*(1), 91--120. <https://doi.org/10.2478/sm-2023-0014>

Prystauka, Y., DeLuca, V., Luque, A., Voits, T., & Rothman, J. (2023). Cognitive Neuroscience Perspectives on Language Acquisition and Processing. *Brain Sciences*, *13*(12), 1613. <https://doi.org/10.3390/brainsci13121613>

Puig-Mayenco, E., González Alonso, J., & Rothman, J. (2020). A systematic review of transfer studies in third language acquisition. *Second Language Research*, *36*(1), 31--64. <https://doi.org/10.1177/0267658318809147>

Puig-Mayenco, E., & Marsden, H. (2018). Polarity-item *anything* in L3 English: Where does transfer come from when the L1 is Catalan and the L2 is Spanish? *Second Language Research*, *34*(4), 487--515. <https://doi.org/10.1177/0267658317747926>

Puig-Mayenco, E., Miller, D., & Rothman, J. (2018). Chapter 9. Language dominance and transfer selection in L3 acquisition: Evidence from sentential negation and negative quantifiers in L3 English. In J. Cho, M. Iverson, T. Judy, T. Leal, & E. Shimanskaya (Eds.), *Studies in Bilingualism* (Vol. 55, pp. 229--260). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.55.09pui>

Puig-Mayenco, E., & Rothman, J. (2020). Low proficiency does not mean *ab initio*: A methodological footnote for linguistic transfer studies. *Language Acquisition*, *27*(2), 217--226. <https://doi.org/10.1080/10489223.2019.1677668>

Puig-Mayenco, E., Rothman, J., & Tubau, S. (2022). Language dominance in the previously acquired languages modulates rate of third language (L3) development over time: A longitudinal study. *International Journal of Bilingual Education and Bilingualism*, *25*(5), 1641--1664. <https://doi.org/10.1080/13670050.2020.1792408>

Qin, T., Fias, W., Van De Weghe, N., & Huang, H. (2024). Differentiating Everyday Map Tasks: Unique Attention-Related Eye Movements and Electrophysiological Signatures of Map Use. *Annals of the American Association of Geographers*, *114*(7), 1604--1624. <https://doi.org/10.1080/24694452.2024.2353845>

Quiñones, I., Amoruso, L., Pomposo Gastelu, I. C., Gil-Robles, S., & Carreiras, M. (2021). What Can Glioma Patients Teach Us about Language (Re)Organization in the Bilingual Brain: Evidence from fMRI and MEG. *Cancers*, *13*(11), 2593. <https://doi.org/10.3390/cancers13112593>

Quiñones, I., Gisbert-Muñoz, S., Amoruso, L., Manso-Ortega, L., Mori, U., Bermudez, G., Robles, S. G., Pomposo, I., & Carreiras, M. (2024). Unveiling the neuroplastic capacity of the bilingual brain: Insights from healthy and pathological individuals. *Brain Structure and Function*. <https://doi.org/10.1007/s00429-024-02846-9>

Rafeekh, R., Krishna, P. P., Kapiley, K., & Mishra, R. K. (2021). The effects of short-term L2 training on components of executive control in Indian bilinguals. *Cognitive Processing*, *22*(2), 339--351. <https://doi.org/10.1007/s10339-021-01014-9>

Raine, L. B., Kao, S.-C., Pindus, D., Westfall, D. R., Shigeta, T. T., Logan, N., Cadenas-Sanchez, C., Li, J., Drollette, E. S., Pontifex, M. B., Khan, N. A., Kramer, A. F., & Hillman, C. H. (2018). A Large-Scale Reanalysis of Childhood Fitness and Inhibitory Control. *Journal of Cognitive Enhancement*, *2*(2), 170--192. <https://doi.org/10.1007/s41465-018-0070-7>

Ramos Feijoo, J., & García Mayo, M. D. P. (2023). The acquisition of relative clauses by Spanish-Basque learners of L3 English: Does dominance play a role? *International Review of Applied Linguistics in Language Teaching*, *61*(3), 1051--1081. <https://doi.org/10.1515/iral-2021-0054>

Rashid Izullah, F., Koivisto, M., Nieminen, V., Luimula, M., & Hämäläinen, H. (2022). Aging and sleep deprivation affect different neurocognitive stages of spatial information processing during a virtual driving task -- An ERP study. *Transportation Research Part F: Traffic Psychology and Behaviour*, *89*, 399--406. <https://doi.org/10.1016/j.trf.2022.07.001>

Reisian, E., Jabbari, A., Fazilatfar, A., & Rezai, M. J. (2023). Acquisition of L3 English Attributive Adjectives by Arabic-Persian and Persian-Arabic Bilinguals. *Applied Research on English Language*, *12*(4). <https://doi.org/10.22108/are.2024.138102.2115>

Roberts, L., González Alonso, J., Pliatsikas, C., & Rothman, J. (2018). Evidence from neurolinguistic methodologies: Can it actually inform linguistic/language acquisition theories and translate to evidence-based applications? *Second Language Research*, *34*(1), 125--143. <https://doi.org/10.1177/0267658316644010>

Rockholt, M. M., Kenefati, G., Doan, L. V., Chen, Z. S., & Wang, J. (2023). In search of a composite biomarker for chronic pain by way of EEG and machine learning: Where do we currently stand? *Frontiers in Neuroscience*, *17*, 1186418. <https://doi.org/10.3389/fnins.2023.1186418>

Rosales, C., & Torres, J. (2024). The role of metalinguistic knowledge in third-language development among heritage and late bilinguals. *International Journal of Bilingualism*, 13670069241229161. <https://doi.org/10.1177/13670069241229161>

Rose, M. C., Brooks, P. J., Lodhi, A. K., & Cortez, A. (2024). Benefits of Testing and Production for Learning Turkish As a New Language. *Language Learning*, *74*(2), 365--401. <https://doi.org/10.1111/lang.12602>

Rosen, R. S. (2018). Longitudinal L3 Acquisition of American Sign Language Motion Verbs: A Case Study of Changes and Persistencies in Prior Language Influence. *Sign Language Studies*, *18*(2), 266--299. <https://doi.org/10.1353/sls.2018.0003>

Ross, V., Vossen, A. Y., Smulders, F. T. Y., Ruiter, R. A. C., Brijs, T., Brijs, K., Wets, G., & Jongen, E. M. M. (2018). Measuring working memory load effects on electrophysiological markers of attention orienting during a simulated drive. *Ergonomics*, *61*(3), 429--443. <https://doi.org/10.1080/00140139.2017.1353708>

Rossi, E., Pereira Soares, S. M., Prystauka, Y., Nakamura, M., & Rothman, J. (2023). Riding the (brain) waves! Using neural oscillations to inform bilingualism research. *Bilingualism: Language and Cognition*, *26*(1), 202--215. <https://doi.org/10.1017/S1366728922000451>

Rossi, E., Voits, T., & DeLuca, V. (2023). Using Structural Neuroimaging to Investigate Second Language. In K. Morgan-Short & J. G. Van Hell, *The Routledge Handbook of Second Language Acquisition and Neurolinguistics* (1st ed., pp. 59--71). Routledge. <https://doi.org/10.4324/9781003190912-7>

Rothman, J. (2024). Harnessing the bilingual descent down the mountain of life: Charting novel paths for Cognitive and Brain Reserves research. *Bilingualism: Language and Cognition*, 1--9. <https://doi.org/10.1017/S1366728924000026>

Rothman, J., Alonso, J. G., & Miller, D. (2018). The Acquisition of Second Language Spanish Morphosyntax. In K. L. Geeslin (Ed.), *The Cambridge Handbook of Spanish Linguistics* (1st ed., pp. 689--715). Cambridge University Press. <https://doi.org/10.1017/9781316779194.032>

Rothman, J., González Alonso, J., & Puig-Mayenco, E. (2019). *Third Language Acquisition and Linguistic Transfer* (1st ed.). Cambridge University Press. <https://doi.org/10.1017/9781316014660>

Rothman, J., & Slabakova, R. (2018). THE GENERATIVE APPROACH TO SLA AND ITS PLACE IN MODERN SECOND LANGUAGE STUDIES. *Studies in Second Language Acquisition*, *40*(2), 417--442. <https://doi.org/10.1017/S0272263117000134>

Royle, P., & Steinhauer, K. (2023). Neural Correlates of Morphology Computation and Representation. In M. Grimaldi, E. Brattico, & Y. Shtyrov (Eds.), *Language Electrified* (Vol. 202, pp. 447--503). Springer US. <https://doi.org/10.1007/978-1-0716-3263-5_14>

Sadeghi, K. (2022). *Talking About Second Language Acquisition*. Springer International Publishing. <https://doi.org/10.1007/978-3-030-99758-8>

Saez-Fajardo, S. (2023). The language learning strategies of multilinguals: The influence of age of acquisition in early bilingualism. *International Journal of Multilingualism*, 1--18. <https://doi.org/10.1080/14790718.2023.2241484>

Safavi, S. M., Lopour, B., & Chou, P. H. (2018). Reducing the Computational Complexity of EEG Source Localization With Cortical Patch Decomposition and Optimal Electrode Selection. *IEEE Transactions on Biomedical Engineering*, *65*(10), 2298--2310. <https://doi.org/10.1109/TBME.2018.2793882>

Salaberry, R. (2020). *The conceptualisation of knowledge about aspect: From monolingual to multilingual representations*. Zenodo. <https://doi.org/10.5281/ZENODO.4138737>

Samara, A. (2022). Artificial Language Learning Methods as a Tool for Sociolinguistic Research. In K. Geeslin, *The Routledge Handbook of Second Language Acquisition and Sociolinguistics* (1st ed., pp. 249--260). Routledge. <https://doi.org/10.4324/9781003017325-23>

Sánchez, L. (2020). *Multilingualism from a language acquisition perspective*. Zenodo. <https://doi.org/10.5281/ZENODO.4138735>

Sánchez-Moguel, S. M., Baravalle, R., González-Salinas, S., Rosso, O. A., Fernández, T., & Montani, F. (2022). Abnormal EEG signal energy in the elderly: A wavelet analysis of event-related potentials during a stroop task. *Journal of Neuroscience Methods*, *376*, 109608. <https://doi.org/10.1016/j.jneumeth.2022.109608>

Sarah Von Grebmer Zu Wolfsthurn. (2022). Does your native language matter? Neural correlates of typological similarity in non-native production. *Lingue e linguaggio*, *1*, 143--169. <https://doi.org/10.1418/104453>

Saturno, J. (2022). Production of inflectional morphology in intercomprehension-based language teaching: The case of Slavic languages. *International Journal of Multilingualism*, *19*(3), 383--401. <https://doi.org/10.1080/14790718.2020.1730379>

Savalle, E., Pillette, L., Won, K., Argelaguet, F., Lécuyer, A., & J-M Macé, M. (2024). Towards electrophysiological measurement of presence in virtual reality through auditory oddball stimuli. *Journal of Neural Engineering*, *21*(4), 046015. <https://doi.org/10.1088/1741-2552/ad5cc2>

Savelieva, T., & Rodina, Y. (2022). Cross-linguistic influence in the acquisition of articles in L3 English by Danish-Russian bilingual children. *Journal of Second Language Studies*, *5*(2), 235--265. <https://doi.org/10.1075/jsls.21025.rod>

Scalise, E., Stahnke, J., & Müller, N. (2021). Parameter setting and acceleration: Subject omissions in a trilingual child with special reference to French. *Language, Interaction and Acquisition*, *12*(1), 157--184. <https://doi.org/10.1075/lia.20011.sca>

Schepens, J., Van Hout, R., & Jaeger, T. F. (2020). Big data suggest strong constraints of linguistic similarity on adult language learning. *Cognition*, *194*, 104056. <https://doi.org/10.1016/j.cognition.2019.104056>

Schiller, N. O. (2019). Evidence for syntactic feature transfer between two languages. *Linguistic Approaches to Bilingualism*, *9*(6), 883--887. <https://doi.org/10.1075/lab.19058.sch>

Schindler, S., Bruchmann, M., Gathmann, B., Moeck, R., & Straube, T. (2021). Effects of low-level visual information and perceptual load on P1 and N170 responses to emotional expressions. *Cortex*, *136*, 14--27. <https://doi.org/10.1016/j.cortex.2020.12.011>

Schindler, S., Bruchmann, M., & Straube, T. (2022). Feature-based attention interacts with emotional picture content during mid-latency and late ERP processing stages. *Biological Psychology*, *170*, 108310. <https://doi.org/10.1016/j.biopsycho.2022.108310>

Schindler, S., Busch, N., Bruchmann, M., Wolf, M., & Straube, T. (2022). Early ERP functions are indexed by lateralized effects to peripherally presented emotional faces and scrambles. *Psychophysiology*, *59*(2), e13959. <https://doi.org/10.1111/psyp.13959>

Schindler, S., Richter, T. S., Bruchmann, M., Busch, N. A., & Straube, T. (2022). Effects of task load, spatial attention, and trait anxiety on neuronal responses to fearful and neutral faces. *Psychophysiology*, *59*(11), e14114. <https://doi.org/10.1111/psyp.14114>

Schirmer, A., Wijaya, M., Wu, E., & Penney, T. B. (2019). Vocal threat enhances visual perception as a function of attention and sex. *Social Cognitive and Affective Neuroscience*, *14*(7), 727--735. <https://doi.org/10.1093/scan/nsz044>

Schneider, J. M., Behboudi, M. H., & Maguire, M. J. (2024). The Necessity of Taking Culture and Context into Account When Studying the Relationship between Socioeconomic Status and Brain Development. *Brain Sciences*, *14*(4), 392. <https://doi.org/10.3390/brainsci14040392>

Schreiter, M. L., & Beste, C. (2020). Inflexible adjustment of expectations affects cognitive-emotional conflict control in adolescents with autism spectrum disorder. *Cortex*, *130*, 231--245. <https://doi.org/10.1016/j.cortex.2020.06.002>

Schreiter, M. L., Chmielewski, W. X., & Beste, C. (2018). How socioemotional setting modulates late-stage conflict resolution processes in the lateral prefrontal cortex. *Cognitive, Affective, & Behavioral Neuroscience*, *18*(3), 521--535. <https://doi.org/10.3758/s13415-018-0585-5>

Schreiter, M. L., Chmielewski, W. X., Mückschel, M., Ziemssen, T., & Beste, C. (2019). How the depth of processing modulates emotional interference -- evidence from EEG and pupil diameter data. *Cognitive, Affective, & Behavioral Neuroscience*, *19*(5), 1231--1246. <https://doi.org/10.3758/s13415-019-00732-0>

Schreiter, M. L., Chmielewski, W. X., Ward, J., & Beste, C. (2019). How non-veridical perception drives actions in healthy humans: Evidence from synaesthesia. *Philosophical Transactions of the Royal Society B: Biological Sciences*, *374*(1787), 20180574. <https://doi.org/10.1098/rstb.2018.0574>

Schwartz, B. D., & Sprouse, R. A. (2021a). In defense of 'copying and restructuring.' *Second Language Research*, *37*(3), 489--493. <https://doi.org/10.1177/0267658320975831>

Schwartz, B. D., & Sprouse, R. A. (2021b). Making models, making predictions. *Linguistic Approaches to Bilingualism*, *11*(1), 116--129. <https://doi.org/10.1075/lab.00032.sch>

Schwartz, B. D., & Sprouse, R. A. (2021c). The Full Transfer/Full Access model and L3 cognitive states. *Linguistic Approaches to Bilingualism*, *11*(1), 1--29. <https://doi.org/10.1075/lab.20055.sch>

Seidel, A., Ghio, M., Studer, B., & Bellebaum, C. (2021). Illusion of control affects ERP amplitude reductions for auditory outcomes of self‐generated actions. *Psychophysiology*, *58*(5), e13792. <https://doi.org/10.1111/psyp.13792>

Shaktawat, D. (2024). The Effect of Indian Contact and Glaswegian Contact on the Phonetic Backward Transfer of Glaswegian English (L2) on Hindi and Indian English (L1). *Languages*, *9*(4), 118. <https://doi.org/10.3390/languages9040118>

Shanghai International Studies University, Ding, Y., Wang, T., & Macau University of Science and Technology. (2023). Análisis de la correlación del rendimiento de aprendizaje entre segunda lengua (L2) y tercera lengua (L3): El caso de estudiantes chinos. *México y La Cuenca Del Pacífico*, *12*(35), 111--130. <https://doi.org/10.32870/mycp.v12i35.828>

Shantz, K., & Tanner, D. (2020). Electrophysiology finds no inherent delay for grammatical gender retrieval in non-native production. *Bilingualism: Language and Cognition*, *23*(1), 98--118. <https://doi.org/10.1017/S1366728918001232>

Sheehan, M., Paciorek, A., & Williams, J. (2018). Case/agreement matching: Evidence for a cognitive bias. *Glossa: A Journal of General Linguistics*, *3*(1). <https://doi.org/10.5334/gjgl.413>

Sherif, M. A., Cortes‐Briones, J. A., Ranganathan, M., & Skosnik, P. D. (2018). Cannabinoid--glutamate interactions and neural oscillations: Implications for psychosis. *European Journal of Neuroscience*, *48*(8), 2890--2902. <https://doi.org/10.1111/ejn.13800>

Shimeng Xu, E., & Chun Man Wong, P. (2023). First Language/Second Language Crosslinguistic Influence on Third Language Acquisition via Neurocognitive Memory Systems. In K. Morgan-Short & J. G. Van Hell, *The Routledge Handbook of Second Language Acquisition and Neurolinguistics* (1st ed., pp. 314--325). Routledge. <https://doi.org/10.4324/9781003190912-29>

Siemund, P., & Lorenz, E. (2024). Chapter 5. Multilingual advantages: On the relationship between type of bilingualism and language knowledge. In K. K. Grohmann (Ed.), *Studies in Bilingualism* (Vol. 66, pp. 123--151). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.66.05sie>

Siemund, P., Lorenz, E., & Toprak-Yildiz, T. E. (2024). The impact of heritage language proficiency on English as an additional language: Disentangling language and cognition. *International Journal of Multilingualism*, *21*(4), 2131--2149. <https://doi.org/10.1080/14790718.2023.2228340>

Sittiprapaporn, P., & Suyajai, P. (2022). Topographical distribution of the human brain to Plukenetia volubilis-based omega-3,6,9 enriched egg consumption. *IAES International Journal of Artificial Intelligence (IJ-AI)*, *11*(4), 1426. <https://doi.org/10.11591/ijai.v11.i4.pp1426-1438>

Slabakova, R. (2021). Does Full Transfer Endure in L3A? *Linguistic Approaches to Bilingualism*, *11*(1), 96--102. <https://doi.org/10.1075/lab.20087.sla>

Slabakova, R. (2023). A shared linguistic system of multilingual representations. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 29--48). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.02sla>

Sokhadze, E. M., Shaban, M., El-Baz, A. S., Tasman, A., Sears, L., & Casanova, M. F. (2023). Event-related potentials and gamma oscillations in EEG as functional diagnostic biomarkers and outcomes in autism spectrum disorder treatment research. In *Neural Engineering Techniques for Autism Spectrum Disorder, Volume 2* (pp. 297--319). Elsevier. <https://doi.org/10.1016/B978-0-12-824421-0.00022-9>

Sokolova, M., & Slabakova, R. (2019). L3 Sentence Processing: Language-Specific or Phenomenon-Sensitive? *Languages*, *4*(3), 54. <https://doi.org/10.3390/languages4030054>

Sokolova, M., & Slabakova, R. (2022). A different type of RC attachment resolution: Comparing bilingual and trilingual processing. In T. Leal, E. Shimanskaya, & C. A. Isabelli (Eds.), *Language Acquisition and Language Disorders* (Vol. 67, pp. 287--314). John Benjamins Publishing Company. <https://doi.org/10.1075/lald.67.12sok>

Sokolova, M. Y., & Levandovski, M. (2023). Relative Clause Processing and Attachment Resolution across Languages: Tatar--Russian--English Trilinguals. *Languages*, *9*(1), 18. <https://doi.org/10.3390/languages9010018>

Spinner, P., Foote, R., & Upor, R. A. (2018). Gender and number processing in second language Swahili. *Linguistic Approaches to Bilingualism*, *8*(4), 446--476. <https://doi.org/10.1075/lab.16042.spi>

Spinner, P., & Gass, S. M. (2019). *Using Judgments in Second Language Acquisition Research* (1st ed.). Routledge. <https://doi.org/10.4324/9781315463377>

Sprouse, R. A. (2024). Non-canonical word orders. In T. Ionin, S. Montrul, & R. Slabakova, *The Routledge Handbook of Second Language Acquisition, Morphosyntax, and Semantics* (1st ed., pp. 382--396). Routledge. <https://doi.org/10.4324/9781003412373-33>

Stadt, R., Hulk, A., & Sleeman, P. (2018). The role of L2 exposure in L3A: A comparative study between third and fourth year secondary school students in the Netherlands. In J. Berns, H. Jacobs, & D. Nouveau (Eds.), *Romance Languages and Linguistic Theory* (Vol. 13, pp. 279--296). John Benjamins Publishing Company. <https://doi.org/10.1075/rllt.13.17sta>

Stadt, R., Hulk, A., & Sleeman, P. (2020a). *L1 Dutch vs L2 English and the initial stages of L3 French acquisition*. Zenodo. <https://doi.org/10.5281/ZENODO.4138749>

Stadt, R., Hulk, A., & Sleeman, P. (2020b). L2 Influence in L3 Acquisition: The Role of the L3. In A. Trotzke & T. Kupisch (Eds.), *Formal Linguistics and Language Education* (Vol. 43, pp. 203--221). Springer International Publishing. <https://doi.org/10.1007/978-3-030-39257-4_11>

Stetie, N. A. (2021). Modelos de procesamiento sintáctico y sus implicaciones para el estudio del lenguaje / Syntactic processing models and their implications for the study of language. *REVISTA DE ESTUDOS DA LINGUAGEM*, *29*(3), 2117. <https://doi.org/10.17851/2237-2083.29.3.2117-1262>

Stoehr, A., Jevtović, M., De Bruin, A., & Martin, C. D. (2024). Phonetic and Lexical Crosslinguistic Influence in Early Spanish--Basque--English Trilinguals. *Language Learning*, *74*(2), 332--364. <https://doi.org/10.1111/lang.12598>

Stoll, E. A. (2024). The Mechanics Underpinning Non-Deterministic Computation in Cortical Neural Networks. *AppliedMath*, *4*(3), 806--827. <https://doi.org/10.3390/appliedmath4030043>

Stringer, D. (2021). Commitment in L3 relationships: Sacred vows or polyamory? *Second Language Research*, *37*(3), 495--500. <https://doi.org/10.1177/0267658320988045>

Suwazono, S., Arao, H., Ueda, Y., & Maedou, S. (2021). Event-related potentials using the auditory novel paradigm in patients with myotonic dystrophy. *Journal of Neurology*, *268*(8), 2900--2907. <https://doi.org/10.1007/s00415-021-10465-1>

Suzuki, Y. (2021). Individual differences in memory predict changes in breakdown and repair fluency but not speed fluency: A short-term fluency training intervention study. *Applied Psycholinguistics*, *42*(4), 969--995. <https://doi.org/10.1017/S0142716421000187>

Syed, N. A., & Bibi, S. (2024). VOT for plosives in the indigenous languages of Balochistan: Implications for adult learners of English. *Journal of Second Language Studies*, *7*(1), 157--192. <https://doi.org/10.1075/jsls.23002.sye>

Tajari, S. N., Gholami, S., Rostami, R., Trabelsi, K., & Taheri, M. (2023). The effect of perceptual-motor exercise on temporal dynamics of cognitive inhibition control in children with developmental coordination disorder. *Mental Health and Physical Activity*, *24*, 100495. <https://doi.org/10.1016/j.mhpa.2022.100495>

Takacs, A., Zink, N., Wolff, N., Münchau, A., Mückschel, M., & Beste, C. (2020). Connecting EEG signal decomposition and response selection processes using the theory of event coding framework. *Human Brain Mapping*, *41*(10), 2862--2877. <https://doi.org/10.1002/hbm.24983>

Tammenga-Helmantel, M., & Maijala, M. (2018a). Sequences in German grammar teaching: An analysis of Dutch, Finnish, and global textbooks. *International Review of Applied Linguistics in Language Teaching*, *56*(1), 45--78. <https://doi.org/10.1515/iral-2015-0070>

Tammenga-Helmantel, M., & Maijala, M. (2018b). Sequences in German grammar teaching: An analysis of Dutch, Finnish, and global textbooks. *International Review of Applied Linguistics in Language Teaching*, *56*(1), 45--78. <https://doi.org/10.1515/iral-2015-0070>

Tao, L., Wang, G., Zhu, M., & Cai, Q. (2021). Bilingualism and domain-general cognitive functions from a neural perspective: A systematic review. *Neuroscience & Biobehavioral Reviews*, *125*, 264--295. <https://doi.org/10.1016/j.neubiorev.2021.02.029>

Tararova, O., Black, M., Wang, Q., & Blong, K. (2023). Gender Agreement in L3 Spanish Production among Speakers of Typologically Different Languages. *Languages*, *8*(1), 18. <https://doi.org/10.3390/languages8010018>

Tavakol, M., Tavakoli, M., & Ketabi, S. (2022). The impact of linguistic background on the nature of classroom dyadic interactions: Evidence from L2 and L3 learners of English as a foreign language. *International Multilingual Research Journal*, *16*(1), 1--26. <https://doi.org/10.1080/19313152.2021.1929761>

Testa, M. (2020). Exploring the Relation Between Psychotypologies and Article Acquisition. *PSYCHOLINGUISTICS*, *27*(2), 252--289. <https://doi.org/10.31470/2309-1797-2020-27-2-252-289>

Timofeeva, P., Quiñones, I., Geng, S., De Bruin, A., Carreiras, M., & Amoruso, L. (2023). Behavioral and oscillatory signatures of switch costs in highly proficient bilinguals. *Scientific Reports*, *13*(1), 7725. <https://doi.org/10.1038/s41598-023-34895-1>

Tomić, A., & Kaan, E. (2022). Oscillatory brain responses to processing code-switches in the presence of others. *Brain and Language*, *231*, 105139. <https://doi.org/10.1016/j.bandl.2022.105139>

Travers, W. (2022). 10 Inside the L3 Classroom: Learner Reflections on University-level Foreign Language Classes for Bilinguals in the United States. In A. Krulatz, G. Neokleous, & A. Dahl (Eds.), *Theoretical and Applied Perspectives on Teaching Foreign Languages in Multilingual Settings* (pp. 170--185). Multilingual Matters. <https://doi.org/10.21832/9781788926423-015>

Tribushinina, E., Boz, B., Aalbers, V., & Blom, E. (2024). Revisiting bilingual foreign language learning advantages: The role of extramural exposure. *International Journal of Bilingualism*, 13670069231224542. <https://doi.org/10.1177/13670069231224542>

Tribushinina, E., & Mackaaij, M. (2023). Bilingual advantages in foreign language learning: Evidence from primary-school pupils with developmental language disorder. *Frontiers in Education*, *8*, 1264120. <https://doi.org/10.3389/feduc.2023.1264120>

Trumbo, M. C., Jones, A. P., Robert, B. M., Trumbo, D., & Matzen, L. E. (2022). A Method of Developing Video Stimuli that Are Amenable to Neuroimaging Analysis: An EEG Pilot Study. In D. D. Schmorrow & C. M. Fidopiastis (Eds.), *Augmented Cognition* (Vol. 13310, pp. 183--201). Springer International Publishing. <https://doi.org/10.1007/978-3-031-05457-0_16>

Udry, I., & Berthele, R. (2024). Young learners' academic self-concepts for L2/L3 French and English. *International Journal of Multilingualism*, 1--18. <https://doi.org/10.1080/14790718.2023.2301094>

Umejima, K., Flynn, S., & Sakai, K. L. (2021). Enhanced activations in syntax-related regions for multilinguals while acquiring a new language. *Scientific Reports*, *11*(1), 7296. <https://doi.org/10.1038/s41598-021-86710-4>

Uth, M., & García García, M. (2018). Chapter 1. Introduction: Core issues of focus realization in Romance. In M. García García & M. Uth (Eds.), *Studies in Language Companion Series* (Vol. 201, pp. 1--30). John Benjamins Publishing Company. <https://doi.org/10.1075/slcs.201.01uth>

Vahid, A., Bluschke, A., Roessner, V., Stober, S., & Beste, C. (2019). Deep Learning Based on Event-Related EEG Differentiates Children with ADHD from Healthy Controls. *Journal of Clinical Medicine*, *8*(7), 1055. <https://doi.org/10.3390/jcm8071055>

Vahid, A., Mückschel, M., Stober, S., Stock, A.-K., & Beste, C. (2020). Applying deep learning to single-trial EEG data provides evidence for complementary theories on action control. *Communications Biology*, *3*(1), 112. <https://doi.org/10.1038/s42003-020-0846-z>

Vallerossa, F. (2024). 'I think mangiò might be passé simple': Exploring multilingual learners' reflections on past tense verb morphology. *International Journal of Multilingualism*, *21*(1), 112--130. <https://doi.org/10.1080/14790718.2022.2036159>

Vallerossa, F., & Bardel, C. (2023). Always trust your gut?: A case study on the differential impact of French as L1/L2 on Italian L3 tense-aspect judgments. *Language, Interaction and Acquisition*, *14*(1), 41--74. <https://doi.org/10.1075/lia.22020.val>

Vallerossa, F., Gudmundson, A., Bergström, A., & Bardel, C. (2023). Learning aspect in Italian as additional language. The role of second languages. *International Review of Applied Linguistics in Language Teaching*, *61*(3), 1139--1171. <https://doi.org/10.1515/iral-2021-0033>

Van Baal, Y. (2023). Definiteness marking in American Norwegian: A unique pattern among the Scandinavian languages. *The Journal of Comparative Germanic Linguistics*, *27*(1), 1. <https://doi.org/10.1007/s10828-023-09149-z>

Van De Ruit, M., & Ghosh, A. (2022). Can you hear me now? Momentary increase in smartphone usage enhances neural processing of task-irrelevant sound tones. *Neuroimage: Reports*, *2*(4), 100131. <https://doi.org/10.1016/j.ynirp.2022.100131>

Van De Ven, M., Voeten, M., Steenbeek-Planting, E. G., & Verhoeven, L. (2018a). Transfer of decoding skills in early foreign language reading. *Learning and Individual Differences*, *62*, 1--11. <https://doi.org/10.1016/j.lindif.2018.01.005>

Van De Ven, M., Voeten, M., Steenbeek-Planting, E. G., & Verhoeven, L. (2018b). Transfer of decoding skills in early foreign language reading. *Learning and Individual Differences*, *62*, 1--11. <https://doi.org/10.1016/j.lindif.2018.01.005>

Van Dijk, C., Dijkstra, T., & Unsworth, S. (2022). Cross-linguistic influence during online sentence processing in bilingual children. *Bilingualism: Language and Cognition*, *25*(4), 691--704. <https://doi.org/10.1017/S1366728922000050>

Van Tessel, E., & Bril, M. (2021). French as a foreign language in the Netherlands: An L2 or an L3? A study on crosslinguistic influences from Dutch and English. *Linguistics in the Netherlands*, *38*, 114--127. <https://doi.org/10.1075/avt.00056.tes>

Vanhove, J. (2019). Metalinguistic knowledge about the native language and language transfer in gender assignment. *Studies in Second Language Learning and Teaching*, *9*(2), 397--419. <https://doi.org/10.14746/ssllt.2019.9.2.7>

Vargas, J. C., & García Mayo, M. D. P. (2022). Lexical Crosslinguistic Influence in L3 Spanish by Tagalog--English Bilinguals. *Languages*, *7*(3), 213. <https://doi.org/10.3390/languages7030213>

Vastano, R., & Widerstrom-Noga, E. (2023). Event-related potentials during mental rotation of body-related stimuli in spinal cord injury population. *Neuropsychologia*, *179*, 108447. <https://doi.org/10.1016/j.neuropsychologia.2022.108447>

Veezhinathan, M., Geethanjali, B., Sakthivel, S., & AnanthaNarayanan, R. (2023). Evaluating cognitive load during lexical decision tasks for monolinguals and bilinguals using EEG. In M. Murugappan (Ed.), *Affective Computing in Healthcare* (pp. 2-1-2--32). IOP Publishing. <https://doi.org/10.1088/978-0-7503-5182-9ch2>

Vera, J. D., Freichel, R., Michelini, G., Loo, S. K., & Lenartowicz, A. (2024). A Network Approach to Understanding the Role of Executive Functioning and Alpha Oscillations in Inattention and Hyperactivity-Impulsivity Symptoms of ADHD. *Journal of Attention Disorders*, *28*(10), 1357--1367. <https://doi.org/10.1177/10870547241253999>

Voits, T., DeLuca, V., & Abutalebi, J. (2022). The Nuance of Bilingualism as a Reserve Contributor: Conveying Research to the Broader Neuroscience Community. *Frontiers in Psychology*, *13*, 909266. <https://doi.org/10.3389/fpsyg.2022.909266>

Voits, T., DeLuca, V., Hao, J., Elin, K., Abutalebi, J., Duñabeitia, J. A., Berglund, G., Gabrielsen, A., Rook, J., Thomsen, H., Waagen, P., & Rothman, J. (2024). Degree of multilingual engagement modulates resting state oscillatory activity across the lifespan. *Neurobiology of Aging*, *140*, 70--80. <https://doi.org/10.1016/j.neurobiolaging.2024.04.009>

Von Grebmer Zu Wolfsthurn, S., Pablos, L., & Schiller, N. O. (2021). Noun-phrase production as a window to language selection: An ERP study. *Neuropsychologia*, *162*, 108055. <https://doi.org/10.1016/j.neuropsychologia.2021.108055>

Wach, A. (2018). Trilingual Learners' Awareness of the Role of L1 in Learning Target Language Grammar. In M. Pawlak & A. Mystkowska-Wiertelak (Eds.), *Challenges of Second and Foreign Language Education in a Globalized World* (pp. 209--226). Springer International Publishing. <https://doi.org/10.1007/978-3-319-66975-5_13>

Wakabayashi, S. (2023). Generative grammar. In L. Wei, Z. Hua, & J. Simpson, *The Routledge Handbook of Applied Linguistics* (2nd ed., pp. 336--349). Routledge. <https://doi.org/10.4324/9781003082644-28>

Walter, D. R., Fischer, G., & Cai, J. (2024). The effect of cue length and position on noticing and learning of determiner agreement pairings: Evidence from a cue-balanced artificial vocabulary learning task. *PLOS ONE*, *19*(7), e0302355. <https://doi.org/10.1371/journal.pone.0302355>

Wand, A. (2023). *Segregation in Language Education: The Case of South Tyrol, Italy*. Springer International Publishing. <https://doi.org/10.1007/978-3-031-32747-6>

Wang, C., Shen, H., Zhu, J., Manman, N., Liao, L., Jiang, K., & Dong, X. (2023). Recognition memory for pictures in children with ADHD: An event-related potential study. *International Journal of Neuroscience*, *133*(5), 555--566. <https://doi.org/10.1080/00207454.2021.1936518>

Wang, L., Zhang, J., Liu, T., Chen, D., Yang, D., Go, R., Wu, J., & Yan, T. (2022). Prediction of Cognitive Task Activations via Resting-State Functional Connectivity Networks: An EEG Study. *IEEE Transactions on Cognitive and Developmental Systems*, *14*(1), 181--188. <https://doi.org/10.1109/TCDS.2020.3031604>

Wang, M., Tokimoto, S., Song, G., Ueno, T., Koizumi, M., & Kiyama, S. (2022). Different Neural Responses for Unfinished Sentence as a Conventional Indirect Refusal Between Native and Non-native Speakers: An Event-Related Potential Study. *Frontiers in Psychology*, *13*, 806023. <https://doi.org/10.3389/fpsyg.2022.806023>

Wang, T., & Yang, J. (2024). The semantic access mechanism of L3 Spanish words: Evidence from a cross-linguistic priming effect by Chinese native speakers. *Review of Cognitive Linguistics*. <https://doi.org/10.1075/rcl.00175.wan>

Wang, Y., Tang, Z., Zhang, X., & Yang, L. (2022). Auditory and cross-modal attentional bias toward positive natural sounds: Behavioral and ERP evidence. *Frontiers in Human Neuroscience*, *16*, 949655. <https://doi.org/10.3389/fnhum.2022.949655>

Wang, Z., & Xu, C. (2024). Language transfers in third language acquisition of Chinese by intermediate level German and English native speakers: Evidence from a behavioral experiment online. *Frontiers in Psychology*, *15*, 1358603. <https://doi.org/10.3389/fpsyg.2024.1358603>

Ward, D. F. B., & Lo, Y. Y. (2023). Incidental development of implicit and explicit grammar knowledge from reading: The case of lower-intermediate learners of English. *System*, *116*, 103094. <https://doi.org/10.1016/j.system.2023.103094>

Wascher, E., Arnau, S., Gutberlet, I., Karthaus, M., & Getzmann, S. (2018). Evaluating Pro- and Re-Active Driving Behavior by Means of the EEG. *Frontiers in Human Neuroscience*, *12*, 205. <https://doi.org/10.3389/fnhum.2018.00205>

Wei, Y., Okazaki, Y. O., So, R. H. Y., Chu, W. C. W., & Kitajo, K. (2019). Motion sickness-susceptible participants exposed to coherent rotating dot patterns show excessive N2 amplitudes and impaired theta-band phase synchronization. *NeuroImage*, *202*, 116028. <https://doi.org/10.1016/j.neuroimage.2019.116028>

Westergaard, M. (2021a). L3 acquisition and crosslinguistic influence as co-activation: Response to commentaries on the keynote 'Microvariation in multilingual situations: The importance of property-by-property acquisition.' *Second Language Research*, *37*(3), 501--518. <https://doi.org/10.1177/02676583211007897>

Westergaard, M. (2021b). Microvariation in multilingual situations: The importance of property-by-property acquisition. *Second Language Research*, *37*(3), 379--407. <https://doi.org/10.1177/0267658319884116>

Westergaard, M. (2021c). The plausibility of wholesale vs. Property-by-property transfer in L3 acquisition. *Linguistic Approaches to Bilingualism*, *11*(1), 103--108. <https://doi.org/10.1075/lab.20091.wes>

White, L. (2021). Choosing between theories: Can L3 acquisition really decide? *Second Language Research*, *37*(3), 429--433. <https://doi.org/10.1177/0267658320941047>

White, L. (2024). Verb movement. In T. Ionin, S. Montrul, & R. Slabakova, *The Routledge Handbook of Second Language Acquisition, Morphosyntax, and Semantics* (1st ed., pp. 341--354). Routledge. <https://doi.org/10.4324/9781003412373-30>

Wicht, C. A., De Pretto, M., Mouthon, M., & Spierer, L. (2022). Neural correlates of expectations-induced effects of caffeine intake on executive functions. *Cortex*, *150*, 61--84. <https://doi.org/10.1016/j.cortex.2022.02.004>

Wilang, J. D. (2024). Exploring the Mindsets of Thai Undergraduate Students: A Comprehensive Study of General and Language-Related Beliefs. *Sage Open*, *14*(2), 21582440241262952. <https://doi.org/10.1177/21582440241262952>

Wolff, N., & Beste, C. (2020). Short-term Smartphone App--Based Focused Attention Meditation Diminishes Cognitive Flexibility. *Journal of Cognitive Neuroscience*, *32*(8), 1484--1496. <https://doi.org/10.1162/jocn_a_01564>

Wolff, N., Chmielewski, W. X., Beste, C., & Roessner, V. (2018). Working memory load affects repetitive behaviour but not cognitive flexibility in adolescent autism spectrum disorder. *The World Journal of Biological Psychiatry*, *19*(7), 509--520. <https://doi.org/10.1080/15622975.2017.1296973>

Wolff, N., Gussek, P., Stock, A., & Beste, C. (2018). Effects of high‐dose ethanol intoxication and hangover on cognitive flexibility. *Addiction Biology*, *23*(1), 503--514. <https://doi.org/10.1111/adb.12470>

Wolff, N., Mückschel, M., Ziemssen, T., & Beste, C. (2018). The role of phasic norepinephrine modulations during task switching: Evidence for specific effects in parietal areas. *Brain Structure and Function*, *223*(2), 925--940. <https://doi.org/10.1007/s00429-017-1531-y>

Woll, N. (2018). Investigating dimensions of metalinguistic awareness: What think-aloud protocols revealed about the cognitive processes involved in positive transfer from L2 to L3. *Language Awareness*, *27*(1--2), 167--185. <https://doi.org/10.1080/09658416.2018.1432057>

Woll, N. (2019). Investigating Positive Lexical Transfer from English (L2) to German (L3) by Quebec Francophones. In E. Vetter & U. Jessner (Eds.), *International Research on Multilingualism: Breaking with the Monolingual Perspective* (Vol. 35, pp. 103--123). Springer International Publishing. <https://doi.org/10.1007/978-3-030-21380-0_7>

Woll, N., Paquet, P.-L., & Wouters, I. (2024). Language as a vehicle or as a resource? Exploring the nature of metalinguistic reflection in plurilingual consciousness-raising tasks. *Journal of Multilingual and Multicultural Development*, *45*(9), 3906--3925. <https://doi.org/10.1080/01434632.2022.2134398>

Wrembel, M. (2021a). Multilingual acquisition property by property: A view from a wider perspective. *Second Language Research*, *37*(3), 441--447. <https://doi.org/10.1177/0267658320935167>

Wrembel, M. (2021b). Transfer vs. dynamic cross-linguistic interactions: Exploring alternative avenues in L3 research. *Linguistic Approaches to Bilingualism*, *11*(1), 109--115. <https://doi.org/10.1075/lab.20092.wre>

Wu, L., Chen, Y., Liu, X., Fang, P., Feng, T., Sun, K., Ren, L., Liang, W., Lu, H., Lin, X., Li, Y., Wang, L., Li, C., Zhang, T., Ni, C., & Wu, S. (2022). The influence of job burnout on the attention ability of army soldiers and officers: Evidence from ERP. *Frontiers in Neuroscience*, *16*, 992537. <https://doi.org/10.3389/fnins.2022.992537>

Wu, S., Liu, D., & Li, Z. (2023). Testing the Bottleneck Hypothesis: Chinese EFL learners' knowledge of morphology and syntax across proficiency levels. *Second Language Research*, *39*(4), 1191--1217. <https://doi.org/10.1177/02676583221128520>

Xiang, J., & Yuan, B. (2020). Definiteness constraint on subjects in L2 and L3 Mandarin grammars: Empirical evidence concerning the source of transfer in L3 acquisition. *Journal of Second Language Studies*, *3*(2), 233--260. <https://doi.org/10.1075/jsls.00012.xia>

Xiaobao, W. (2024). *Trilingual Education of Uyghur Children: Phonological Awareness, Language Acquisition and Literacy Development* (1st ed.). Routledge. <https://doi.org/10.4324/9781003473596>

Xu, E. S., Matthews, S., Yip, V., & Wong, P. C. M. (2024). Memory systems modulate crosslinguistic influence on third language morphosyntactic acquisition. *PLOS ONE*, *19*(7), e0304572. <https://doi.org/10.1371/journal.pone.0304572>

Xu, X., Nie, X., Zhang, J., & Xu, T. (2023). Multi-Level Attention Recognition of EEG Based on Feature Selection. *International Journal of Environmental Research and Public Health*, *20*(4), 3487. <https://doi.org/10.3390/ijerph20043487>

Xu, Y., Yuan, Y., Xie, X., Tan, H., & Guan, L. (2022). Romantic feedbacks influence self-relevant processing: The moderating effects of sex difference and facial attractiveness. *Current Psychology*, *41*(7), 4145--4157. <https://doi.org/10.1007/s12144-021-02114-7>

Yang, Y. (2023). The Correlation Between English and French Proficiency of Chinese Trilingual Learners. *Chinese Journal of Applied Linguistics*, *46*(3), 404--423. <https://doi.org/10.1515/CJAL-2023-0305>

Yee, J., Yap, N. T., Korenar, M., Saddy, J. D., & Pliatsikas, C. (2024). Subcortical restructuring as a function of multilingualism: Insights from monolinguals, bilinguals, trilinguals and quadrilinguals. *Bilingualism: Language and Cognition*, *27*(4), 715--728. <https://doi.org/10.1017/S136672892300086X>

Yener, G., Hünerli-Gündüz, D., Yıldırım, E., Aktürk, T., Başar-Eroğlu, C., Bonanni, L., Del Percio, C., Farina, F., Ferri, R., Güntekin, B., Hajós, M., Ibáñez, A., Jiang, Y., Lizio, R., Lopez, S., Noce, G., Parra, M. A., Randall, F., Stocchi, F., & Babiloni, C. (2022). Treatment effects on event-related EEG potentials and oscillations in Alzheimer's disease. *International Journal of Psychophysiology*, *177*, 179--201. <https://doi.org/10.1016/j.ijpsycho.2022.05.008>

You, E. (2024). The cross-linguistic influence of L1 Korean and L2 English in L3 Spanish syntactic processing. *Onomázein Revista de Lingüística Filología y Traducción*, *63*, 37--54. <https://doi.org/10.7764/onomazein.63.03>

Yu, L., Wang, X., Lyu, Y., Ding, L., Jia, J., Tong, S., & Guo, X. (2020). Electrophysiological Evidences for the Rotational Uncertainty Effect in the Hand Mental Rotation: An ERP and ERS/ERD Study. *Neuroscience*, *432*, 205--215. <https://doi.org/10.1016/j.neuroscience.2020.02.040>

Zaharchuk, H. A., & Karuza, E. A. (2021). Multilayer networks: An untapped tool for understanding bilingual neurocognition. *Brain and Language*, *220*, 104977. <https://doi.org/10.1016/j.bandl.2021.104977>

Zahler, S. L. (2022). Measuring Individual Differences. In K. Geeslin, *The Routledge Handbook of Second Language Acquisition and Sociolinguistics* (1st ed., pp. 237--248). Routledge. <https://doi.org/10.4324/9781003017325-22>

Zanesco, J., Tipura, E., Posada, A., Clément, F., & Pegna, A. J. (2019). Seeing is believing: Early perceptual brain processes are modified by social feedback. *Social Neuroscience*, *14*(5), 519--529. <https://doi.org/10.1080/17470919.2018.1511470>

Zawiszewski, A., & Laka, I. (2020). Bilinguals processing noun morphology: Evidence for the Language Distance Hypothesis from event-related potentials. *Journal of Neurolinguistics*, *55*, 100908. <https://doi.org/10.1016/j.jneuroling.2020.100908>

Zen, E. L. (2018). A Preliminary Evidence of Transfer in the Acquisition of Sentential Negation of English in Multilingual Indonesian Children in School Contexts. *3L The Southeast Asian Journal of English Language Studies*, *24*(3), 155--167. <https://doi.org/10.17576/3L-2018-2403-12>

Zen, E. L. (2020). Role of Regional Language Background and Speech Styles on the Production of Voice Onset Time (VOT) in English among Indonesian Multilinguals. *Indonesian Journal of Applied Linguistics*, *10*(2), 359--368. <https://doi.org/10.17509/ijal.v10i2.28604>

Zenia, N. Z., Dizaji, L. G., & Hu, Y. (2023). Effect of Machine Reliability on the Cognitive Processes of the Task Performance. *2023 IEEE International Conference on Systems, Man, and Cybernetics (SMC)*, 3241--3246. <https://doi.org/10.1109/SMC53992.2023.10394070>

Zeynali Hamied, R., & Modirkhamene, S. (2024). EFL learners' short-term and long-term memory: Does learning additional languages matter? *International Journal of Multilingualism*, 1--15. <https://doi.org/10.1080/14790718.2023.2294955>

Zhang, G., Li, X., & Cong, F. (2020). Objective Extraction of Evoked Event-Related Oscillation from Time-Frequency Representation of Event-Related Potentials. *Neural Plasticity*, *2020*, 1--20. <https://doi.org/10.1155/2020/8841354>

Zhang, L. (2022). ¿Pollo o Bollo? Acquisition of Voicing Contrast by Chinese Learners of L3 Spanish. *Hispania*, *105*(4), 595--613. <https://doi.org/10.1353/hpn.2022.0118>

Zhang, L., Morales-Front, A., & Sanz, C. (2023). Dynamics in cross-linguistic influence: Evidence from VOT development of Mandarin-English bilingual learners of L3 Spanish. In M. M. Brown-Bousfield, S. Flynn, & É. Fernández-Berkes (Eds.), *Studies in Bilingualism* (Vol. 65, pp. 121--149). John Benjamins Publishing Company. <https://doi.org/10.1075/sibil.65.06zha>

Zhang, X., Guo, F., Li, S., Li, M., & Chen, H. (2018). Consumers' different neural activity and attitude to the leading brand and imitator. *Journal of Neuroscience, Psychology, and Economics*, *11*(3), 166--181. <https://doi.org/10.1037/npe0000077>

Zhang, Z., Ma, F., & Guo, T. (2023). Proactive and reactive language control in bilingual language production revealed by decoding sustained potentials and electroencephalography oscillations. *Human Brain Mapping*, *44*(15), 5065--5078. <https://doi.org/10.1002/hbm.26433>

Zhao, C., Kormos, J., Rebuschat, P., & Suzuki, S. (2021). The role of modality and awareness in language learning. *Applied Psycholinguistics*, *42*(3), 703--737. <https://doi.org/10.1017/S0142716421000023>

Zhao, Q., Li, H., Hu, B., Li, Y., Gillebert, C. R., Mantini, D., & Liu, Q. (2018a). Neural Correlates of Drug-Related Attentional Bias in Heroin Dependence. *Frontiers in Human Neuroscience*, *11*, 646. <https://doi.org/10.3389/fnhum.2017.00646>

Zhao, Q., Li, H., Hu, B., Li, Y., Gillebert, C. R., Mantini, D., & Liu, Q. (2018b). Neural Correlates of Drug-Related Attentional Bias in Heroin Dependence. *Frontiers in Human Neuroscience*, *11*, 646. <https://doi.org/10.3389/fnhum.2017.00646>

Zhou, S., Luo, J., Yu, T., Li, D., Yin, Y., & Tang, X. (2020). Towards a neural model of creative evaluation in advertising: An electrophysiological study. *Scientific Reports*, *10*(1), 21958. <https://doi.org/10.1038/s41598-020-79044-0>

Zhou, X. (Emily), Huang, X., & He, J. (2020). Translanguaging in L3 Spanish Classrooms: Practices and Attitudes. *Círculo de Lingüística Aplicada a La Comunicación*, *84*, 65--75. <https://doi.org/10.5209/clac.71996>

Zhu, L., Ma, Q., Bai, X., & Hu, L. (2020). Mechanisms behind hazard perception of warning signs: An EEG study. *Transportation Research Part F: Traffic Psychology and Behaviour*, *69*, 362--374. <https://doi.org/10.1016/j.trf.2020.02.001>

Zhu, Y., & Mok, P. (2024). Cross-linguistic influences on the production of third language consonant clusters by L1 Cantonese--L2 English--L3 German trilinguals. *International Journal of Multilingualism*, *21*(3), 1700--1717. <https://doi.org/10.1080/14790718.2023.2208866>

Zibin, A., Allawama, A., Akayleh, M., & Naimat, K. (2024). Investigating Arabic-speaking EFL learners' understanding of French gender markers: A typological primacy model approach to a third language. *Cogent Arts & Humanities*, *11*(1), 2328898. <https://doi.org/10.1080/23311983.2024.2328898>

Zink, N., Bensmann, W., Arning, L., Beste, C., & Stock, A.-K. (2019). Apolipoprotein ε4 is associated with better cognitive control allocation in healthy young adults. *NeuroImage*, *185*, 274--285. <https://doi.org/10.1016/j.neuroimage.2018.10.046>

Zink, N., Stock, A.-K., Vahid, A., & Beste, C. (2018). On the Neurophysiological Mechanisms Underlying the Adaptability to Varying Cognitive Control Demands. *Frontiers in Human Neuroscience*, *12*, 411. <https://doi.org/10.3389/fnhum.2018.00411>

Zink, N., Zhang, R., Chmielewski, W. X., Beste, C., & Stock, A.-K. (2019). Detrimental effects of a high-dose alcohol intoxication on sequential cognitive flexibility are attenuated by practice. *Progress in Neuro-Psychopharmacology and Biological Psychiatry*, *89*, 97--108. <https://doi.org/10.1016/j.pnpbp.2018.08.034>

Żychliński, S., Skałba, A., Wrembel, M., & Kaźmierski, K. (2023). How syntactic gradience in L1 affects L3 acquisition: A longitudinal study. *Linguistic Approaches to Bilingualism*. <https://doi.org/10.1075/lab.23011.zyc>

Zyzik, E., & Marqués-Pascual, L. (2018). Practice with Formulaic Sequences: Can It Promote the Incidental Learning of Grammar? In C. Jones (Ed.), *Practice in Second Language Learning* (1st ed., pp. 55--78). Cambridge University Press. <https://doi.org/10.1017/9781316443118.005>

水英姚. (2021). 香港大专生普通话学习中"了"的偏误分析: 对体习得普遍趋势和多语教学的启示. *Chinese as a Second Language Research*, *10*(1), 131--154. <https://doi.org/10.1515/caslar-2021-0006>

</div>

</div>
