---
title: What's in a fluke? The problem of trust and distrust
author: ''
date: '2020-06-25'
slug: whats-in-a-fluke
categories:
  - viewpoint
tags: [fluke, false positive, false negative, perception, bias, discrimination, trust, distrust]
subtitle: ''
summary: "The label 'fluke' may in principle be skewed by the eye of the beholder, the mind of the perceiver and the availability or lack of data."
authors: []
featured: no
image:
  caption: "'Esperanto classes advertisement on a sunny morning' - Pablo Bernabeu (CC BY 4.0)"
  focal_point: ''
  preview_only: no
projects: []
---


<br>

*Fluke* is a popular term for the statistical concepts of false positive or false negative results (more commonly used for false positives). A *false positive* occurs when a result that does not exist in reality is observed in an analysis due to a methodological error (be it experimental, statistical, or otherwise). Conversely, a *false negative* occurs when a genuine result is not observed in an analysis, due to the same kind of error. The concept of fluke is defined by its opposite: a truthful, accurate result.

The label 'fluke' is ubiquitous where statistics is applied, from medicine to psychology and from sociology to politics.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">When I won in 2018, many dismissed our victory as a “fluke.”<br><br>Our win was treated as an aberration, or bc my opponent “didn’t try.”<br><br>So from the start, tonight’s race was important to me.<br><br>Tonight we are proving that the people’s movement in NY isn’t an accident. It‘s a mandate.</p>&mdash; Alexandria Ocasio-Cortez (@AOC) <a href="https://twitter.com/AOC/status/1275618050134474761?ref_src=twsrc%5Etfw">June 24, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<br>

## What's in the label 'fluke'---or what could there be?

AOC's tweet points at two main types of reactions to her results in the previous elections. The first type is dismissal, on the grounds of a fluke or a weak opposition. The other reaction is plain 'aberration'. A few weeks earlier, Mark Leibovich had also delved into this issue in The New York Times (May 4, 2020, https://nyti.ms/2YsJ9fb):

> She believed misconceptions had taken hold about her: that she was angry and strident. That she was naïve. “That I just don’t know how this town works,” she said. “That I’m stupid. Or I’m lucky. That was a big thing the Democrats were saying. That I was a fluke. Which is basically just 10 different ways of saying she’s not supposed to be here.”

The seemingly objective term 'fluke', with its statistical underpinning, seems to be susceptible to biased uses. We may then have to ask: Have other electoral results, comparable to AOC's, been equally studied for signs of a fluke? Why is a certain result perceived as a fluke in the first place? From perceptual to cognitive and historical biases, people's judgements  are susceptible to visual mistakes (Zamboni, Ledgeway, McGraw, & Schluppeck, 2016), confirmation bias (Rajsic, Taylor, & Pratt, 2018) and biased records (Hug, 2003).

In summary, the label 'fluke' may in principle be skewed by:

<div style = 'padding-left: 20px;'>

<i class="fas fa-eye"></i> &nbsp; the eye of the beholder

<i class="fas fa-brain"></i> &nbsp; the mind of the perceiver

<i class="far fa-newspaper"></i> &nbsp; the availability or lack of data

</div>

<br>

## Trust and distrust

Problems associated with the reliance on trust and distrust have become patent even in fields that are relatively regulated against arbitrary decisions, such as higher education and academia (Barber, Hayes, Johnson, Márquez-Magaña, & 10,234 signatories, 2020; Milkman, Akinola, & Chugh, 2012, 2015).

<br>

## References

Barber, P. H., Hayes, T. B., Johnson, T. L., Márquez-Magaña, L., & 10,234 signatories (2020). Systemic racism in higher education. *Science, 369*, 6510, 1440-1441. https://doi.org/10.1126/science.abd7140

Hug, S. (2003). Selection Bias in Comparative Research: The Case of Incomplete Data Sets. *Political Analysis, 11*(3), 255-274. https://doi.org/10.1093/pan/mpg014

Milkman, K. L., Akinola, M., & Chugh, D. (2012). Temporal distance and discrimination: an audit study in academia. *Psychological Science, 23*(7), 710–717. https://doi.org/10.1177/0956797611434539

_____ (2015).  What happens before? A field experiment exploring how pay and representation differentially shape bias on the pathway into organizations. *Journal of Applied Psychology, 100*(6), 1678–1712. https://doi.org/10.1037/apl0000022

Rajsic, J., Taylor, J. E. T., & Pratt, J. (2018) Out of sight, out of mind: Matching bias underlies confirmatory visual search. *Attention, Perception, & Psychophysics, 79*, 498–507. https://doi.org/10.3758/s13414-016-1259-4

Zamboni, E., Ledgeway, T., McGraw, P. V., & Schluppeck, D. (2016). Do perceptual biases emerge early or late in visual processing? Decision-biases in motion perception. *Proceedings of the Royal Society B: Biological Sciences, 283*(1833), 20160263. https://doi.org/10.1098/rspb.2016.0263

<br>
