name: Update CV from OSF

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download CV from OSF
      run: |
        # Download the CV from OSF
        curl -L -o temp-cv.pdf https://osf.io/download/84ktq
        
        # Check if download was successful
        if [ ! -f temp-cv.pdf ]; then
          echo "Failed to download CV from OSF"
          exit 1
        fi
        
        # Check if it's a valid PDF
        if ! file temp-cv.pdf | grep -q "PDF"; then
          echo "Downloaded file is not a valid PDF"
          exit 1
        fi
        
        # Move to final location in static directory
        mv temp-cv.pdf static/cv-pablo-bernabeu.pdf
        
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet static/cv-pablo-bernabeu.pdf; then
          echo "No changes detected in CV"
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "CV has been updated"
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if changed
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add static/cv-pablo-bernabeu.pdf
        git commit -m "Automated CV update from OSF"
        git push